// nextjs/template/src/core/common/filter/filterIndex.tsx
import Link from "next/link";
import { DatePicker, Select } from "antd";
import {
  Amount,
  Department,
  Designation,
  Doctor,
  Status,
} from "../selectOption";
import CommonSelect from "../common-select/commonSelect";

const FilterIndexComponent = () => {
  const getModalContainer = () => {
    const modalElement = document.getElementById("modal-datepicker");
    return modalElement ? modalElement : document.body; // Fallback to document.body if modalElement is null
  };
  return (
    <>
      <form action="#">
        <div className="filter-body pb-0">
          <div className="mb-3">
            <div className="d-flex align-items-center justify-content-between">
              <label className="form-label mb-1">Doctor</label>
              <Link href="#" className="link-primary mb-1">
                Reset
              </Link>
            </div>
            <CommonSelect
              options={Doctor}
              className="select"
              defaultValue={Doctor[0]}
            />
          </div>
          <div className="mb-3">
            <div className="d-flex align-items-center justify-content-between">
              <label className="form-label">Designation</label>
              <Link href="#" className="link-primary mb-1">
                Reset
              </Link>
            </div>
            <CommonSelect
              options={Designation}
              className="select"
              defaultValue={Designation[0]}
            />
          </div>
          <div className="mb-3">
            <div className="d-flex align-items-center justify-content-between">
              <label className="form-label">Department</label>
              <Link href="#" className="link-primary mb-1">
                Reset
              </Link>
            </div>
            <CommonSelect
              options={Department}
              className="select"
              defaultValue={Department[0]}
            />
          </div>
          <div className="mb-3">
            <label className="form-label mb-1 text-dark fs-14 fw-medium">
              Date<span className="text-danger">*</span>
            </label>
            <div className="input-icon-end position-relative">
              <DatePicker
                className="form-control datetimepicker"
                format={{
                  format: "DD-MM-YYYY",
                  type: "mask",
                }}
                getPopupContainer={getModalContainer}
                placeholder="DD-MM-YYYY"
                suffixIcon={null}
              />
              <span className="input-icon-addon">
                <i className="ti ti-calendar" />
              </span>
            </div>
          </div>
          <div className="mb-3">
            <div className="d-flex align-items-center justify-content-between">
              <label className="form-label">Amount</label>
              <Link href="#" className="link-primary mb-1">
                Reset
              </Link>
            </div>
            <CommonSelect
              options={Amount}
              className="select"
              defaultValue={Amount[0]}
            />
          </div>
          <div className="mb-3">
            <div className="d-flex align-items-center justify-content-between">
              <label className="form-label">Status</label>
              <Link href="#" className="link-primary mb-1">
                Reset
              </Link>
            </div>
            <CommonSelect
              options={Status}
              className="select"
              defaultValue={Status[0]}
            />
          </div>
        </div>
        <div className="filter-footer d-flex align-items-center justify-content-end border-top">
          <Link
            href="#"
            className="btn btn-light btn-md me-2 fw-medium"
            id="close-filter"
          >
            Close
          </Link>
          <button type="submit" className="btn btn-primary btn-md fw-medium">
            Filter
          </button>
        </div>
      </form>
    </>
  );
};

export default FilterIndexComponent;

// vue/template/src/components/common-component/filter-index.vue
<template>
     <form action="#">
        <div class="filter-body pb-0">
            <div class="mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <label class="form-label mb-1">Doctor</label>
                    <a href="javascript:void(0);" class="link-primary mb-1">Reset</a>
                </div>
                <vue-multiselect
                    v-model="selected"
                    :options="Doctor"
                    :multiple="true"
                    label="name"
                    track-by="id"
                />
            </div>
            <div class="mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <label class="form-label">Designation</label>
                    <a href="javascript:void(0);" class="link-primary mb-1">Reset</a>
                </div>
                <vue-multiselect
                    v-model="selectedOne"
                    :options="Designation"
                    :multiple="true"
                    label="name"
                    track-by="id"
                />
            </div>
            <div class="mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <label class="form-label">Department</label>
                    <a href="javascript:void(0);" class="link-primary mb-1">Reset</a>
                </div>
                <vue-multiselect
                    v-model="selectedTwo"
                    :options="Department"
                    :multiple="true"
                    label="name"
                    track-by="id"
                />
            </div>
            <div class="mb-3">
                <label class="form-label mb-1 text-dark fs-14 fw-medium">Date<span class="text-danger">*</span></label>
                <div class="input-icon-end position-relative">  
                    <a-date-picker v-model="valueOne" class="form-control datetimepicker" placeholder="dd/mm/yyyy" />
                </div>
            </div>
            <div class="mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <label class="form-label">Amount</label>
                    <a href="javascript:void(0);" class="link-primary mb-1">Reset</a>
                </div>
                <vue-multiselect
                    v-model="selectedThree"
                    :options="Amount"
                    :multiple="true"
                    label="name"
                    track-by="id"
                />
            </div>
            <div class="mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <label class="form-label">Status</label>
                    <a href="javascript:void(0);" class="link-primary mb-1">Reset</a>
                </div>
                <vue-multiselect
                    v-model="selectedFour"
                    :options="Status"
                    :multiple="true"
                    label="name"
                    track-by="id"
                />
            </div>
        </div>
        <div class="filter-footer d-flex align-items-center justify-content-end border-top">
            <a href="javascript:void(0);" class="btn btn-light btn-md me-2 fw-medium" id="close-filter">Close</a>
            <button type="submit" class="btn btn-primary btn-md fw-medium">Filter</button>
        </div>
    </form>
</template>

<script>
import { ref } from 'vue';
const valueOne = ref();
export default {
    data() {
        return {
            valueOne,
            selected: [],
            selectedOne: [],
            selectedTwo: [],
            selectedThree: [],
            selectedFour: [],
            Doctor: [
                {id: 1, name: 'Dr. Mick Thompson'},
                {id: 2, name: 'Dr. Sarah Johnson'},
                {id: 3, name: 'Dr. Emily Carter'},
                {id: 4, name: 'Dr. David Lee'},
                {id: 5, name: 'Dr. Anna Kim'},
            ],
            Designation: [
                {id: 1, name: 'Cardiologist'},
                {id: 2, name: 'Orthopedic Surgeon'},
                {id: 3, name: 'Pediatrician'},
                {id: 4, name: 'Gynecologist'},
            ],
            Department: [
                {id: 1, name: 'Cardiology'},
                {id: 2, name: 'Orthopedics'},
                {id: 3, name: 'Pediatrics'},
            ],
            Amount: [
                {id: 1, name: '$501 - $1000'},
                {id: 2, name: '$501 - $1100'},
                {id: 3, name: '$701 - $1200'},
            ],
            Status: [
                {id: 1, name: 'Available'},
                {id: 2, name: 'Unavailable'},
            ],
        };
    },
    methods: {
        addTag (newTag) {
            const tag = {
                name: newTag,
                code: newTag.substring(0, 2) + Math.floor((Math.random() * 10000000))
            }
            this.options.push(tag)
            this.value.push(tag)
        }
    },
};
</script>
