// nextjs/template/src/components/pages/settings/website-settings/seo-setup-settings/seoSetupSettings.tsx
"use client";

import Link from "next/link";
import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar";
import { useState } from "react";
import TagInput from "@/core/common/Taginput";

const SeoSetupSettingsComponent = () => {
  const [tags, setTags] = useState<string[]>(["Admin", "Clinic", "Management"]);
  const handleTagsChange = (newTags: string[]) => {
    setTags(newTags);
  };

  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content" id="profilePage">
          {/* Page Header */}
          <div className="mb-3 border-bottom pb-3">
            <h4 className="fw-bold mb-0">Settings</h4>
          </div>
          {/* End Page Header */}
          <div className="card">
            <div className="card-body p-0">
              <div className="settings-wrapper d-flex">
                {/* Start Settings Sidebar */}
                <SettingsSidebar />
                {/* End Settings Sidebar */}
                <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div className="card-header border-bottom px-0 mx-3">
                    <h5 className="fw-bold">SEO Setup</h5>
                  </div>
                  <div className="card-body px-0 mx-3">
                    <form>
                      {/* start row */}
                      <div className="row border-bottom mb-3">
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Meta Title
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <input type="text" className="form-control" />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Meta Description
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <textarea
                                className="form-control"
                                rows={3}
                                defaultValue={""}
                              />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Keywords
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <TagInput
                                initialTags={tags}
                                onTagsChange={handleTagsChange}
                              />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                      {/* start row */}
                      <div className="row border-bottom mb-3">
                        <div className="mb-3">
                          <h5 className="fw-bold mb-0">SEO Setup - OG Meta</h5>
                        </div>
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Meta Title
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <input type="text" className="form-control" />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Meta Description
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <textarea
                                className="form-control"
                                rows={3}
                                defaultValue={""}
                              />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-2">
                              <label className="form-label mb-0">
                                Keywords
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-10">
                              <TagInput
                                initialTags={tags}
                                onTagsChange={handleTagsChange}
                              />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                      <div className="d-flex align-items-center justify-content-end">
                        <Link href="#" className="btn btn-light me-3">
                          Cancel
                        </Link>
                        <Link href="#" className="btn btn-primary">
                          Save Changes
                        </Link>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default SeoSetupSettingsComponent;

// angular/template/src/app/features/settings/website-settings/seo-setup-settings/seo-setup-settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TagInputModule } from 'ngx-chips';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-seo-setup-settings',
  templateUrl: './seo-setup-settings.component.html',
  styleUrls: ['./seo-setup-settings.component.scss'],
  imports: [CommonModule,TagInputModule,FormsModule]
})
export class SeoSetupSettingsComponent {
  tags=['Admin', 'Clinic', 'Management']
}


                                <div class="card-header border-bottom px-0 mx-3">
                                    <h5 class="fw-bold">SEO Setup</h5>
                                </div>
                                <div class="card-body px-0 mx-3">
                                    <form>

                                        <!-- start row -->
                                        <div class="row border-bottom mb-3">
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Meta Title </label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <input type="text" class="form-control">
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Meta Description</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3"></textarea>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Keywords</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <tag-input [ngModelOptions]="{standalone: true}" [(ngModel)]="tags" [placeholder]="'Add new'"></tag-input>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                        </div>
                                        <!-- end row -->

                                        <!-- start row -->
                                        <div class="row border-bottom mb-3">
                                            <div class="mb-3">
                                                <h5 class="fw-bold mb-0">SEO Setup - OG Meta</h5>
                                            </div>
                                            
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Meta Title </label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <input type="text" class="form-control">
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Meta Description</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3"></textarea>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Keywords</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <tag-input [ngModelOptions]="{standalone: true}" [(ngModel)]="tags" [placeholder]="'Add new'"></tag-input>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                        </div>
                                        <!-- end row -->

                                        <div class="d-flex align-items-center justify-content-end">
                                            <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                                            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                                        </div>
                                    </form>
                                </div>
