// vue/template/src/views/pages/doctor/doctors-reviews.vue
<template>
    <doctor-header></doctor-header>
    <doctor-sidebar></doctor-sidebar>

    <!-- ========================
        Start Page Content
    ========================= -->
        
    <div class="page-wrapper">

        <!-- Start Content -->
        <div class="content">

            <!-- Start Page Header -->
            <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3 mb-3 border-1 border-bottom">
                <div class="flex-grow-1">
                    <h4 class="fw-bold mb-0"> Reviews </h4>
                </div>
                <div class="text-end">
                    <!-- dropdown-->
                    <div class="dropdown me-1">
                        <a href="javascript:void(0);" class="btn btn-md fw-normal border bg-white rounded text-dark d-inline-flex align-items-center fs-14"  data-bs-toggle="dropdown">
                            Export<i class="ti ti-chevron-down ms-2"></i>
                        </a>
                        <ul class="dropdown-menu p-2">
                            <li>
                                <a class="dropdown-item" href="#">Download as PDF</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Download as Excel</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- End Page Header -->

            
            <div class=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                <div class="search-set mb-3">
                    <div class="d-flex align-items-center flex-wrap gap-2">
                        <div class="table-search d-flex align-items-center mb-0">
                            <div class="search-input">
                                <a href="javascript:void(0);" class="btn-searchset"></a>
                                <input
                                    type="text"
                                    class="form-control"
                                    placeholder="Search"
                                    v-model="searchQuery"
                                />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
                    
                    <div class="dropdown me-2">
                        <a href="javascript:void(0);" class="bg-white border rounded btn btn-md text-dark fs-14 py-1 align-items-center d-flex fw-normal" data-bs-toggle="dropdown" data-bs-auto-close="outside">
                            <i class="ti ti-filter text-gray-5 me-1"></i>Filters
                        </a>
                        <div class="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown p-0" id="filter-dropdown">
                            <div class="d-flex align-items-center justify-content-between border-bottom filter-header">
                                <h4 class="mb-0 fw-bold">Filter</h4>
                                <div class="d-flex align-items-center">
                                    <a href="javascript:void(0);" class="link-danger text-decoration-underline">Clear All</a>
                                </div>
                            </div>
                           <filter-index></filter-index>
                        </div>
                    </div>

                    <div class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14" data-bs-toggle="dropdown">
                            <span  class="me-1"> Sort By : </span>  Recent
                        </a>
                        <ul class="dropdown-menu  dropdown-menu-end p-2">
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Recent</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Oldest</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <a-table class="table table-nowrap datatable" :columns="columns" :data-source="filteredPages">
                    <template #bodyCell="{ column, record }">
                        <template v-if="column.key === 'Reviewed_By'">
                            <div class="d-flex align-items-center">
                                <a href="javascript:void(0);" class="avatar avatar-sm me-2">
                                    <img :src="getImageUrl(record.Image)" alt="product" class="rounded-circle">
                                </a>
                                <a href="javascript:void(0);">{{record.Reviewed_By}}</a>
                            </div>
                        </template>
                        <template v-if="column.key === 'Ratings'">
                            <div class="star-ratings d-flex align-items-center">
                                <i class="ti ti-star-filled fs-14 text-warning"></i>
                                <i class="ti ti-star-filled fs-14 text-warning"></i>
                                <i class="ti ti-star-filled fs-14 text-warning"></i>
                                <i class="ti ti-star-filled fs-14 text-warning"></i>
                                <i class="ti ti-star-filled fs-14 text-warning"></i>
                            </div>
                        </template>
                    </template>
                </a-table>
            </div>
            
        </div>
        <!-- End Content -->
            <!-- Footer Start -->
        <div class="footer text-center bg-white p-2 border-top">
            <p class="text-dark mb-0">2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All Rights Reserved</p>
        </div>
        <!-- Footer End -->

    </div>

    <!-- ========================
        End Page Content
    ========================= -->
</template>

<script>
const columns = [
  {
    title: "Reviewed By",
    dataIndex: "Reviewed_By",
    key: "Reviewed_By",
    sorter: {
      compare: (a, b) =>
        a.Reviewed_By.toLowerCase() > b.Reviewed_By.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "Review",
    dataIndex: "Review",
    sorter: {
      compare: (a, b) =>
        a.Review.toLowerCase() > b.Review.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "Ratings",
    dataIndex: "Ratings",
    key: "Ratings",
    sorter: {
      compare: (a, b) => (a.Ratings.toLowerCase() > b.Ratings.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) => (a.Date.toLowerCase() > b.Date.toLowerCase() ? -1 : 1),
    },
  },
];

const data = [
 {
   "Reviewed_By": "Alberto Ripley",
   "Image": "user-33.jpg",
   "Review": "The clinic was well-organized, and I didn’t have to wait long.",
   "Ratings": "",
   "Date": "30 Apr 2025"
 },
 {
   "Reviewed_By": "Susan Babin",
   "Image": "user-01.jpg",
   "Review": "Dr. Mick explained everything in simple terms and made sure I understood my condition and treatm.",
   "Ratings": "",
   "Date": "15 Apr 2025"
 },
 {
   "Reviewed_By": "Carol Lam",
   "Image": "user-02.jpg",
   "Review": "From the front desk to the consultation, everything was smooth. Dr. Mick and his staff were friend.",
   "Ratings": "",
   "Date": "02 Apr 2025"
 },
 {
   "Reviewed_By": "Marsha Noland",
   "Image": "user-04.jpg",
   "Review": "While the doctor was knowledgeable, I felt a bit rushed during my visit. I would’ve appreciated.",
   "Ratings": "",
   "Date": "27 Mar 2025"
 },
 {
   "Reviewed_By": "Irma Armstrong",
   "Image": "user-05.jpg",
   "Review": "This is helpful information! If anyone has ongoing symptoms, don’t hesitate to speak to a licensed",
   "Ratings": "",
   "Date": "12 Mar 2025"
 },
 {
   "Reviewed_By": "Jesus Adams",
   "Image": "user-07.jpg",
   "Review": "Very professional and caring staff. I felt heard and understood throughout my treatment.",
   "Ratings": "",
   "Date": "05 Mar 2025"
 },
 {
   "Reviewed_By": "Ezra Belcher",
   "Image": "user-08.jpg",
   "Review": "The doctors took time to explain everything clearly. I left feeling informed and reassured.",
   "Ratings": "",
   "Date": "19 Feb 2025"
 },
 {
   "Reviewed_By": "Glen Lentz",
   "Image": "user-10.jpg",
   "Review": "Exceptional care from start to finish. The clinic is clean, organized, and patient-focused.",
   "Ratings": "",
   "Date": "16 Feb 2025"
 },
 {
   "Reviewed_By": "Bernard Griffith",
   "Image": "user-12.jpg",
   "Review": "Booking was easy, the team was punctual, and I received excellent medical attention..",
   "Ratings": "",
   "Date": "01 Feb 2025"
 },
 {
   "Reviewed_By": "John Elsass",
   "Image": "user-14.jpg",
   "Review": "Great experience! The doctor truly listened and provided personalized advice.",
   "Ratings": "",
   "Date": "20 Jas 2025"
 }
]

export default {
    data(){
        return{
            searchQuery: "",
            data,
            columns,
        }
    },
    methods: {
        getImageUrl(imageName) {
            return new URL(`/src/assets/img/users/${imageName}`, import.meta.url).href;
        },
    },
    computed: {
        filteredPages() {
            const query = this.searchQuery.toLowerCase();
            return this.data.filter((record) => {
                return (
                    record.Reviewed_By.toLowerCase().includes(query) ||
                    record.Review.toLowerCase().includes(query) ||
                    record.Ratings.toLowerCase().includes(query) ||
                    record.Date.toLowerCase().includes(query) 
                );
            });
        },
    },
}
</script>

// nextjs/template/src/components/pages/doctor/doctors-reviews/doctorsReviews.tsx
"use client";


import { useState } from "react";
import {
  Amount,
  Department,
  Designation,
  Doctor,
  Status,
} from "@/core/common/selectOption";
import { DatePicker } from "antd";
import SearchInput from "@/core/common/dataTable/dataTableSearch";
import { DoctorReviewsData } from "@/core/json/doctorReviewsData";
import Datatable from "@/core/common/dataTable";
import ImageWithBasePath from "@/core/imageWithBasePath";
import Link from "next/link";
import CommonSelect from "@/core/common/common-select/commonSelect";

const DoctorsReviewsComponent = () => {
  const data = DoctorReviewsData;
  const columns = [
    {
      title: "Reviewed By",
      dataIndex: "Reviewed_By",
      render: (text: any, render: any) => (
        <div className="d-flex align-items-center">
          <Link href="#" className="avatar avatar-sm me-2">
            <ImageWithBasePath
              src={`assets/img/users/${render.img}`}
              alt="product"
              className="rounded-circle"
            />
          </Link>
          <Link href="#">{text}</Link>
        </div>
      ),
      sorter: (a: any, b: any) => a.Reviewed_By.length - b.Reviewed_By.length,
    },
    {
      title: "Review",
      dataIndex: "Review",
      sorter: (a: any, b: any) => a.Review.length - b.Review.length,
    },
    {
      title: "Ratings",
      dataIndex: "Ratings",
      render: () => (
        <div className="star-ratings d-flex align-items-center">
          <i className="ti ti-star-filled fs-14 text-warning" />
          <i className="ti ti-star-filled fs-14 text-warning" />
          <i className="ti ti-star-filled fs-14 text-warning" />
          <i className="ti ti-star-filled fs-14 text-warning" />
          <i className="ti ti-star-filled fs-14 text-warning" />
        </div>
      ),
      sorter: (a: any, b: any) => a.Ratings.length - b.Ratings.length,
    },
    {
      title: "Date",
      dataIndex: "Date",
      sorter: (a: any, b: any) => a.Date.length - b.Date.length,
    },
  ];
  const [searchText, setSearchText] = useState<string>("");

  const handleSearch = (value: string) => {
    setSearchText(value);
  };

  const getModalContainer = () => {
    const modalElement = document.getElementById("modal-datepicker");
    return modalElement ? modalElement : document.body; // Fallback to document.body if modalElement is null
  };
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Start Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3 mb-3 border-1 border-bottom">
            <div className="flex-grow-1">
              <h4 className="fw-bold mb-0"> Reviews </h4>
            </div>
            <div className="text-end">
              {/* dropdown*/}
              <div className="dropdown me-1">
                <Link
                  href="#"
                  className="btn btn-md fw-normal border bg-white rounded text-dark d-inline-flex align-items-center fs-14"
                  data-bs-toggle="dropdown"
                >
                  Export
                  <i className="ti ti-chevron-down ms-2" />
                </Link>
                <ul className="dropdown-menu p-2">
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as PDF
                    </Link>
                  </li>
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as Excel
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          {/* End Page Header */}
          <div className=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
            <div className="search-set mb-3">
              <div className="d-flex align-items-center flex-wrap gap-2">
                <div className="table-search d-flex align-items-center mb-0">
                  <div className="search-input">
                    <SearchInput value={searchText} onChange={handleSearch} />
                  </div>
                </div>
              </div>
            </div>
            <div className="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
              <div className="dropdown me-2">
                <Link
                  href="#"
                  className="bg-white border rounded btn btn-md text-dark fs-14 py-1 align-items-center d-flex fw-normal"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                >
                  <i className="ti ti-filter text-gray-5 me-1" />
                  Filters
                </Link>
                <div
                  className="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown p-0"
                  id="filter-dropdown"
                >
                  <div className="d-flex align-items-center justify-content-between border-bottom filter-header">
                    <h4 className="mb-0 fw-bold">Filter</h4>
                    <div className="d-flex align-items-center">
                      <Link
                        href="#"
                        className="link-danger text-decoration-underline"
                      >
                        Clear All
                      </Link>
                    </div>
                  </div>
                  <form action="#">
                    <div className="filter-body pb-0">
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label mb-1">Doctor</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                            options={Doctor}
                            className="select"
                            defaultValue={Doctor[0]}
                          />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Designation</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                            options={Designation}
                            className="select"
                            defaultValue={Designation[0]}
                          />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Department</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                            options={Department}
                            className="select"
                            defaultValue={Department[0]}
                          />
                      </div>
                      <div className="mb-3">
                        <label className="form-label mb-1 text-dark fs-14 fw-medium">
                          Date<span className="text-danger">*</span>
                        </label>
                        <div className="input-icon-end position-relative">
                          <DatePicker
                            className="form-control datetimepicker"
                            format={{
                              format: "DD-MM-YYYY",
                              type: "mask",
                            }}
                            getPopupContainer={getModalContainer}
                            placeholder="DD-MM-YYYY"
                            suffixIcon={null}
                          />
                          <span className="input-icon-addon">
                            <i className="ti ti-calendar" />
                          </span>
                        </div>
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Amount</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                            options={Amount}
                            className="select"
                            defaultValue={Amount[0]}
                          />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Status</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                            options={Status}
                            className="select"
                            defaultValue={Status[0]}
                          />
                      </div>
                    </div>
                    <div className="filter-footer d-flex align-items-center justify-content-end border-top">
                      <Link
                        href="#"
                        className="btn btn-light btn-md me-2 fw-medium"
                        id="close-filter"
                      >
                        Close
                      </Link>
                      <button
                        type="submit"
                        className="btn btn-primary btn-md fw-medium"
                      >
                        Filter
                      </button>
                    </div>
                  </form>
                </div>
              </div>
              <div className="dropdown">
                <Link
                  href="#"
                  className="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                  data-bs-toggle="dropdown"
                >
                  <span className="me-1"> Sort By : </span> Recent
                </Link>
                <ul className="dropdown-menu  dropdown-menu-end p-2">
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Recent
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Oldest
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className="table-responsive">
            <Datatable
              columns={columns}
              dataSource={data}
              Selection={false}
              searchText={searchText}
            />
          </div>
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default DoctorsReviewsComponent;
