// nextjs/template/src/components/pages/settings/clinic-settings/invoice-settings/invoiceSettings.tsx
"use client";


import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar";
import { Invoice_Roundoff } from "@/core/common/selectOption";
import CommonSelect from "@/core/common/common-select/commonSelect";
import DefaultEditor from "react-simple-wysiwyg";
import Link from "next/link";

const InvoiceSettingsComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content" id="profilePage">
          {/* Page Header */}
          <div className="mb-3 border-bottom pb-3">
            <h4 className="fw-bold mb-0">Settings</h4>
          </div>
          {/* End Page Header */}
          <div className="card">
            <div className="card-body p-0">
              <div className="settings-wrapper d-flex">
                {/* Start Settings Sidebar */}
                <SettingsSidebar />
                {/* End Settings Sidebar */}
                <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div className="card-header border-bottom px-0 mx-3">
                    <h5 className="fw-bold">Invoice Settings</h5>
                  </div>
                  <div className="card-body px-0 mx-3">
                    <form>
                      {/* start row */}
                      <div className="row border-bottom mb-3">
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-3">
                              <label className="form-label mb-0">
                                Invoice Image
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-9">
                              <input type="file" className="form-control" />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-3">
                              <label className="form-label mb-0">
                                Invoice Prefix
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-4">
                              <input type="text" className="form-control" />
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-3">
                              <label className="form-label mb-0">
                                Invoice Roundoff
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-4">
                              <CommonSelect
                                options={Invoice_Roundoff}
                                className="select"
                                defaultValue={Invoice_Roundoff[0]}
                              />
                            </div>
                            {/* end col */}
                            <div className="col-lg-5">
                              <div className="form-check form-switch ps-0">
                                <input
                                  className="form-check-input m-0"
                                  type="checkbox"
                                  defaultChecked
                                />
                              </div>
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-3">
                              <label className="form-label mb-0">
                                Show Company Details
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-8">
                              <div className="form-check form-switch ps-0">
                                <input
                                  className="form-check-input m-0"
                                  type="checkbox"
                                  defaultChecked
                                />
                              </div>
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                        <div className="col-lg-12">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-lg-3">
                              <label className="form-label mb-0">
                                Invoice Terms
                              </label>
                            </div>
                            {/* end col */}
                            <div className="col-lg-9">
                              <div className="editor three-line">
                                <DefaultEditor />
                              </div>
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                      <div className="d-flex align-items-center justify-content-end">
                        <Link href="#" className="btn btn-light me-3">
                          Cancel
                        </Link>
                        <Link href="#" className="btn btn-primary">
                          Save Changes
                        </Link>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default InvoiceSettingsComponent;

// angular/template/src/app/features/settings/app-settings/invoice-settings/invoice-settings.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-invoice-settings',
  templateUrl: './invoice-settings.component.html',
  styleUrls: ['./invoice-settings.component.scss'],
  imports:[CommonModule,MatSelectModule]
})
export class InvoiceSettingsComponent {

}

                            <div class="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                                <div class="card-header border-bottom px-0 mx-3">
                                    <h5 class="fw-bold">Invoice Settings</h5>
                                </div>
                                <div class="card-body px-0 mx-3">
                                    <form>

                                        <!-- start row -->
                                        <div class="row border-bottom mb-3">
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-3">
                                                        <label class="form-label mb-0">Invoice Image</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-9">
                                                        <input type="file" class="form-control">
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-3">
                                                    <label class="form-label mb-0">Invoice Prefix</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-4">
                                                    <input type="text" class="form-control">
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-3">
                                                    <label class="form-label mb-0">Invoice Roundoff</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-4">
                                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                                        <mat-option value="1">Select</mat-option>
                                                        <mat-option value="1">Mar 18 2025</mat-option>
                                                        <mat-option value="1">2025 Mar 18</mat-option>
                                                    </mat-select>
                                                </div><!-- end col -->
                                                <div class="col-lg-5">
                                                    <div class="form-check form-switch ps-0">
                                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                                    </div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-3">
                                                    <label class="form-label mb-0">Show Company Details</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-8">
                                                    <div class="form-check form-switch ps-0">
                                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                                    </div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-3">
                                                    <label class="form-label mb-0">Invoice Terms</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-9">
                                                    <div class="editor three-line"></div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                        </div>
                                        <!-- end row -->

                                        <div class="d-flex align-items-center justify-content-end">
                                            <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                                            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
