// angular/template/src/app/features/administration/reports/income-report/income-report.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { PaginationService, tablePageSize } from '../../../../../../src/app/shared/custom-pagination/pagination.service';
import { DataService } from '../../../../../../src/app/shared/data/data.service';
import { apiResultFormat, pageSelection, reports } from '../../../../../../src/app/shared/models/models';
import { routes } from '../../../../../../src/app/shared/routes/routes';
import { CommonModule } from '@angular/common';
import { MatSelectModule } from '@angular/material/select';
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
import { MatSortModule } from '@angular/material/sort';
import { FormsModule } from '@angular/forms';
import { MultiSelectModule } from 'primeng/multiselect';
import { TagInputModule } from 'ngx-chips';

@Component({
  selector: 'app-income-report',
  templateUrl: './income-report.component.html',
  styleUrls: ['./income-report.component.scss'],
  imports:[CommonModule ,MatSelectModule,BsDatepickerModule,MatSortModule,FormsModule,MultiSelectModule,TagInputModule]
})
export class IncomeReportComponent {
  routes=routes
  tags=['Received', 'Pending'];
  tags1=['PayPal', 'Cheque'];
    bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();
public pageSize = 10;
public tableData: reports[] = [];
public tableDataCopy: reports[] = [];
public actualData: reports[] = [];
public currentPage = 1;
public skip = 0;
public limit: number = this.pageSize;
public serialNumberArray: number[] = [];
public totalData = 0;
public pageSelection: pageSelection[] = [];
dataSource!: MatTableDataSource<reports>;
public searchDataValue = '';
public row=true;
constructor(
  private data: DataService,
  private router: Router,
  private pagination: PaginationService
) {
      this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];

  this.data.getIncomeReport().subscribe((apiRes: apiResultFormat) => {
    this.actualData = apiRes.data;
    this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
      if (this.router.url == this.routes.incomeReport) {
        this.getTableData({ skip: res.skip, limit: res.limit });
        this.pageSize = res.pageSize;
      }
    });
  });
}
private getTableData(pageOption: pageSelection): void {
  this.data.getIncomeReport().subscribe((apiRes: apiResultFormat) => {
    this.tableData = [];
    this.tableDataCopy = [];
    this.serialNumberArray = [];
    this.totalData = apiRes.totalData;
    apiRes.data.map((res: reports, index: number) => {
      const serialNumber = index + 1;
      if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
        res.sNo = serialNumber;
        this.tableData.push(res);
        this.tableDataCopy.push(res);
        this.serialNumberArray.push(serialNumber);
      }
    });
    this.dataSource = new MatTableDataSource<reports>(this.actualData);
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  });
}

public searchData(value: string): void {
  this.searchDataValue = value.trim().toLowerCase();
  this.dataSource.filter = this.searchDataValue;
  this.tableData = this.dataSource.filteredData;
  this.row = this.tableData.length > 0;

  if (this.searchDataValue !== '') {
    // Handle filtered data
    this.pagination.calculatePageSize.next({
      totalData: this.tableData.length,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.tableData.map((_, i) => i + 1), // Generates serials like [1, 2, 3...]
    });
  } else {
    // Handle reset to full data
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  }
}

public sortData(sort: Sort) {
  const data = this.tableData.slice();

  if (!sort.active || sort.direction === '') {
    this.tableData = data;
  } else {
    this.tableData = data.sort((a, b) => {
      const aValue = (a as never)[sort.active];

      const bValue = (b as never)[sort.active];
      return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
    });
  }
}
public changePageSize(pageSize: number): void {
  this.pageSelection = [];
  this.limit = pageSize;
  this.skip = 0;
  this.currentPage = 1;
  this.pagination.tablePageSize.next({
    skip: this.skip,
    limit: this.limit,
    pageSize: this.pageSize,
  });
}
}

            <!-- Start Content -->
            <div class="content">

                <!-- Start Page Header -->
                <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 mb-3 pb-3 border-bottom">
                    <div class="flex-grow-1">
                        <h4 class="fw-bold mb-0">Income Report</h4>
                    </div>
                    <div class="text-end d-flex">
                        <!-- dropdown-->
                        <div class="dropdown me-1">
							<a href="javascript:void(0);" class="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"  data-bs-toggle="dropdown">
								Export<i class="ti ti-chevron-down ms-2"></i>
							</a>
							<ul class="dropdown-menu p-2">
								<li>
									<a class="dropdown-item" href="javascript:void(0);">Download as PDF</a>
								</li>
								<li>
									<a class="dropdown-item" href="javascript:void(0);">Download as Excel</a>
								</li>
							</ul>
						</div>
                    </div>
				</div>
				<!-- End Page Header -->

                <!-- row start -->
                <div class="row">

                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">
                         <div class="card shadow-sm flex-fill w-100">
                             <div class="card-body">
                                 <div class="d-flex justify-content-between mb-2">
                                     <div>
                                         <p class="mb-1 text-truncate">Total Clinic Income</p>
                                         <h6 class="mb-0 fw-bold">$18,750</h6>
                                     </div>
                                     <span class="avatar avatar-lg bg-soft-primary text-primary rounded-circle flex-shrink-0"><i class="ti ti-currency-dollar fs-24"></i></span>
                                 </div>
                                 <div class="progress mb-2 progress-sm">
                                     <div class="progress-bar bg-primary" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                 </div>
                                 <p class="mb-0 fs-13"><span class="text-success"><i class="ti ti-arrow-up-right me-1"></i>5.62%</span> from last month</p>
                             </div>
                         </div>
                    </div>
                    <!-- col end -->
 
                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">
                         <div class="card shadow-sm flex-fill w-100">
                             <div class="card-body">
                                 <div class="d-flex justify-content-between mb-2">
                                     <div>
                                         <p class="mb-1 text-truncate">Doctor Fees Collected</p>
                                         <h6 class="mb-0 fw-bold">$7,000</h6>
                                     </div>
                                     <span class="avatar avatar-lg bg-soft-success text-success rounded-circle flex-shrink-0"><i class="ti ti-stethoscope fs-24"></i></span>
                                 </div>
                                 <div class="progress mb-2 progress-sm">
                                     <div class="progress-bar bg-success" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                 </div>
                                 <p class="mb-0 fs-13"><span class="text-success"><i class="ti ti-arrow-up-right me-1"></i>11.4%</span> from last month</p>
                             </div>
                         </div>
                    </div>
                    <!-- col end -->
 
                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">
                         <div class="card shadow-sm flex-fill w-100">
                             <div class="card-body">
                                 <div class="d-flex justify-content-between mb-2">
                                     <div>
                                         <p class="mb-1 text-truncate">Medicine Sales</p>
                                         <h6 class="mb-0 fw-bold">$6,250</h6>
                                     </div>
                                     <span class="avatar avatar-lg bg-soft-warning text-warning rounded-circle flex-shrink-0"><i class="ti ti-pill fs-24"></i></span>
                                 </div>
                                 <div class="progress mb-2 progress-sm">
                                     <div class="progress-bar bg-warning" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                 </div>
                                 <p class="mb-0 fs-13"><span class="text-success"><i class="ti ti-arrow-up-right me-1"></i>8.52%</span> from last month</p>
                             </div>
                         </div>
                    </div>
                    <!-- col end -->
 
                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">
                         <div class="card shadow-sm flex-fill w-100">
                             <div class="card-body">
                                 <div class="d-flex justify-content-between mb-2">
                                     <div>
                                         <p class="mb-1 text-truncate">Lab Revenue</p>
                                         <h6 class="mb-0 fw-bold">$5,500</h6>
                                     </div>
                                     <span class="avatar avatar-lg bg-soft-danger text-danger rounded-circle flex-shrink-0"><i class="ti ti-flask fs-24"></i></span>
                                 </div>
                                 <div class="progress mb-2 progress-sm">
                                     <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                 </div>
                                 <p class="mb-0 fs-13"><span class="text-danger"><i class="ti ti-arrow-down-right me-1"></i>7.45%</span> from last month</p>
                             </div>
                         </div>
                    </div>
                    <!-- col end -->
 
                 </div>     
                 <!-- row end -->

                 <div class="card">
                    <div class="card-body">

                        <!-- start row -->
                         <div class="row row-gap-2">
                            <div class="col-md-6">
                                <div class="mb-0">
                                    <label class="form-label">Date</label>
                                    <div class="input-group position-relative">
                                        <input type="text" class="form-control date-range bookingrange rounded-end bg-white" bsDaterangepicker [(ngModel)]="bsRangeValue" name="time" [bsConfig]="{ adaptivePosition: true }" placeholder="20 Apr 25 - 20 Apr 25">
                                        <span class="input-icon-addon fs-14 text-dark">
                                            <i class="ti ti-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-6">
                                <div class="mb-0">
                                    <label class="form-label">Received From</label>
                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="1">Alberto Ripley</mat-option>
                                        <mat-option value="1">Susan Babin</mat-option>
                                        <mat-option value="1">Martin Lisa</mat-option>
                                        <mat-option value="1">Stella Mary</mat-option>
                                        <mat-option value="1">Carol Lam</mat-option>
                                    </mat-select>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-6">
                                <div class="mb-0">
                                    <label class="form-label">Payment Method</label>
                                    <tag-input [ngModelOptions]="{standalone: true}" [(ngModel)]="tags1" [placeholder]="'Add new'"></tag-input>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-6">
                                <div class="mb-0">
                                    <label class="form-label">Status</label>
                                    <tag-input [ngModelOptions]="{standalone: true}" [(ngModel)]="tags" [placeholder]="'Add new'"></tag-input>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-12">
                                <div class="d-flex align-items-center justify-content-end">
                                    <a href="javascript:void(0);" class="btn btn-dark"><i class="ti ti-player-play me-1"></i>Run Report</a>
                                </div>
                            </div><!-- end col -->
                         </div>
                        <!-- end row -->

                    </div><!-- end card body -->
                 </div><!-- end card -->

                <div class="table-responsive">
                   <table matSort (matSortChange)="sortData($event)" class="table table-nowrap dataTable datatable">
                        <thead class="thead-light">
                            <tr>
                                <th>Income</th>
                                <th>Amount</th>
                                <th>Date</th>
                                <th>Received From</th>
                                <th>Payment Method</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (data of tableData;track data){
                            <tr>
                                <td>{{data.income}}</td>
                                <td><p class="text-dark fw-medium">{{data.amount}}</p></td>
                                <td>{{data.date}}</td>
                                <td><p class="text-dark fw-medium">{{data.receivedFrom}}</p></td>
                                <td>{{data.paymentMethod}}</td>
                                <td><span class="badge px-2 py-1 fs-13 fw-medium"
                                    [ngClass]="data.status==='Pending'?'badge-soft-warning border border-warning':'badge-soft-success border border-success'">{{data.status}}</span></td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                                
            </div>
            <!-- End Content -->

// nextjs/template/src/components/pages/administration-modules/reports/income-report/incomeReport.tsx
"use client";

import { IcomeReportData } from "@/core/json/incomeReportData";
import Datatable from "@/core/common/dataTable";
import PredefinedDatePicker from "@/core/common/datePicker";
import { Received_From } from "@/core/common/selectOption";
import CommonSelect from "@/core/common/common-select/commonSelect";
import { useState } from "react";
import TagInput from "@/core/common/Taginput";
import Link from "next/link";

const IncomeReportComponent = () => {
  const data = IcomeReportData;
  const columns = [
    {
      title: "Income",
      dataIndex: "Income",
      sorter: (a: any, b: any) => a.Income.length - b.Income.length,
    },
    {
      title: "Amount",
      dataIndex: "Amount",
      render: (text: any) => <p className="text-dark fw-medium">{text}</p>,
      sorter: (a: any, b: any) => a.Amount.length - b.Amount.length,
    },
    {
      title: "Date",
      dataIndex: "Date",
      sorter: (a: any, b: any) => a.Date.length - b.Date.length,
    },
    {
      title: "Received From",
      dataIndex: "ReceivedFrom",
      render: (text: any) => <p className="text-dark fw-medium">{text}</p>,
      sorter: (a: any, b: any) => a.ReceivedFrom.length - b.ReceivedFrom.length,
    },
    {
      title: "Payment Method",
      dataIndex: "PaymentMethod",
      sorter: (a: any, b: any) =>
        a.PaymentMethod.length - b.PaymentMethod.length,
    },
    {
      title: "Status",
      dataIndex: "Status",
      render: (text: string) => (
        <span
          className={`badge ${
            text === "Received"
              ? "badge-soft-success border-success"
              : "border-warning badge-soft-warning"
          }  border  px-2 py-1 fs-13 fw-medium`}
        >
          {text}
        </span>
      ),
      sorter: (a: any, b: any) => a.Status.length - b.Status.length,
    },
  ];

  const [tags, setTags] = useState<string[]>(["PayPal", "Cheque"]);
  const handleTagsChange = (newTags: string[]) => {
    setTags(newTags);
  };
  const [tags2, setTags2] = useState<string[]>(["Received", "Pending"]);
  const handleTagsChange2 = (newTags: string[]) => {
    setTags2(newTags);
  };

  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Start Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 mb-3 pb-3 border-bottom">
            <div className="flex-grow-1">
              <h4 className="fw-bold mb-0">Income Report</h4>
            </div>
            <div className="text-end d-flex">
              {/* dropdown*/}
              <div className="dropdown me-1">
                <Link
                  href="#"
                  className="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"
                  data-bs-toggle="dropdown"
                >
                  Export
                  <i className="ti ti-chevron-down ms-2" />
                </Link>
                <ul className="dropdown-menu p-2">
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as PDF
                    </Link>
                  </li>
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as Excel
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          {/* End Page Header */}
          {/* row start */}
          <div className="row">
            {/* col start */}
            <div className="col-xl-3 col-md-6 d-flex">
              <div className="card shadow-sm flex-fill w-100">
                <div className="card-body">
                  <div className="d-flex justify-content-between mb-2">
                    <div>
                      <p className="mb-1 text-truncate">Total Clinic Income</p>
                      <h6 className="mb-0 fw-bold">$18,750</h6>
                    </div>
                    <span className="avatar avatar-lg bg-soft-primary text-primary rounded-circle flex-shrink-0">
                      <i className="ti ti-currency-dollar fs-24" />
                    </span>
                  </div>
                  <div className="progress mb-2 progress-sm">
                    <div
                      className="progress-bar bg-primary"
                      role="progressbar"
                      style={{ width: "75%" }}
                      aria-valuenow={25}
                      aria-valuemin={0}
                      aria-valuemax={100}
                    />
                  </div>
                  <p className="mb-0 fs-13">
                    <span className="text-success">
                      <i className="ti ti-arrow-up-right me-1" />
                      5.62%
                    </span>
                    from last month
                  </p>
                </div>
              </div>
            </div>
            {/* col end */}
            {/* col start */}
            <div className="col-xl-3 col-md-6 d-flex">
              <div className="card shadow-sm flex-fill w-100">
                <div className="card-body">
                  <div className="d-flex justify-content-between mb-2">
                    <div>
                      <p className="mb-1 text-truncate">
                        Doctor Fees Collected
                      </p>
                      <h6 className="mb-0 fw-bold">$7,000</h6>
                    </div>
                    <span className="avatar avatar-lg bg-soft-success text-success rounded-circle flex-shrink-0">
                      <i className="ti ti-stethoscope fs-24" />
                    </span>
                  </div>
                  <div className="progress mb-2 progress-sm">
                    <div
                      className="progress-bar bg-success"
                      role="progressbar"
                      style={{ width: "75%" }}
                      aria-valuenow={25}
                      aria-valuemin={0}
                      aria-valuemax={100}
                    />
                  </div>
                  <p className="mb-0 fs-13">
                    <span className="text-success">
                      <i className="ti ti-arrow-up-right me-1" />
                      11.4%
                    </span>
                    from last month
                  </p>
                </div>
              </div>
            </div>
            {/* col end */}
            {/* col start */}
            <div className="col-xl-3 col-md-6 d-flex">
              <div className="card shadow-sm flex-fill w-100">
                <div className="card-body">
                  <div className="d-flex justify-content-between mb-2">
                    <div>
                      <p className="mb-1 text-truncate">Medicine Sales</p>
                      <h6 className="mb-0 fw-bold">$6,250</h6>
                    </div>
                    <span className="avatar avatar-lg bg-soft-warning text-warning rounded-circle flex-shrink-0">
                      <i className="ti ti-pill fs-24" />
                    </span>
                  </div>
                  <div className="progress mb-2 progress-sm">
                    <div
                      className="progress-bar bg-warning"
                      role="progressbar"
                      style={{ width: "75%" }}
                      aria-valuenow={25}
                      aria-valuemin={0}
                      aria-valuemax={100}
                    />
                  </div>
                  <p className="mb-0 fs-13">
                    <span className="text-success">
                      <i className="ti ti-arrow-up-right me-1" />
                      8.52%
                    </span>
                    from last month
                  </p>
                </div>
              </div>
            </div>
            {/* col end */}
            {/* col start */}
            <div className="col-xl-3 col-md-6 d-flex">
              <div className="card shadow-sm flex-fill w-100">
                <div className="card-body">
                  <div className="d-flex justify-content-between mb-2">
                    <div>
                      <p className="mb-1 text-truncate">Lab Revenue</p>
                      <h6 className="mb-0 fw-bold">$5,500</h6>
                    </div>
                    <span className="avatar avatar-lg bg-soft-danger text-danger rounded-circle flex-shrink-0">
                      <i className="ti ti-flask fs-24" />
                    </span>
                  </div>
                  <div className="progress mb-2 progress-sm">
                    <div
                      className="progress-bar bg-danger"
                      role="progressbar"
                      style={{ width: "25%" }}
                      aria-valuenow={25}
                      aria-valuemin={0}
                      aria-valuemax={100}
                    />
                  </div>
                  <p className="mb-0 fs-13">
                    <span className="text-danger">
                      <i className="ti ti-arrow-down-right me-1" />
                      7.45%
                    </span>
                    from last month
                  </p>
                </div>
              </div>
            </div>
            {/* col end */}
          </div>
          {/* row end */}
          <div className="card">
            <div className="card-body">
              {/* start row */}
              <div className="row row-gap-2">
                <div className="col-md-6">
                  <div className="mb-0">
                    <label className="form-label">Date</label>
                    <div className="position-relative report-rangepicker">
                      <PredefinedDatePicker />
                      <span className="input-icon-addon fs-14 text-dark">
                        <i className="ti ti-calendar" />
                      </span>
                    </div>
                  </div>
                </div>
                {/* end col */}
                <div className="col-md-6">
                  <div className="mb-0">
                    <label className="form-label">Received From</label>
                    <CommonSelect
                      options={Received_From}
                      className="select"
                      defaultValue={Received_From[0]}
                    />
                  </div>
                </div>
                {/* end col */}
                <div className="col-md-6">
                  <div className="mb-0">
                    <label className="form-label">Payment Method</label>
                    <TagInput
                      initialTags={tags}
                      onTagsChange={handleTagsChange}
                    />
                  </div>
                </div>
                {/* end col */}
                <div className="col-md-6">
                  <div className="mb-0">
                    <label className="form-label">Status</label>
                    <TagInput
                      initialTags={tags2}
                      onTagsChange={handleTagsChange2}
                    />
                  </div>
                </div>
                {/* end col */}
                <div className="col-md-12">
                  <div className="d-flex align-items-center justify-content-end">
                    <Link href="#" className="btn btn-dark">
                      <i className="ti ti-player-play me-1" />
                      Run Report
                    </Link>
                  </div>
                </div>
                {/* end col */}
              </div>
              {/* end row */}
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
          <div className="table-responsive">
            <Datatable
              columns={columns}
              dataSource={data}
              Selection={false}
              searchText={""}
            />
          </div>
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default IncomeReportComponent;
