// nextjs/template/src/components/pages/settings/other-settings/system-update/systemUpdate.tsx
"use client";

import Link from "next/link"
import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar"


const SystemUpdateComponent = () => {
  return (
    <>
  {/* ========================
			Start Page Content
		========================= */}
  <div className="page-wrapper">
    {/* Start Content */}
    <div className="content" id="profilePage">
      {/* Page Header */}
      <div className="mb-3 border-bottom pb-3">
        <h4 className="fw-bold mb-0">Settings</h4>
      </div>
      {/* End Page Header */}
      <div className="card">
        <div className="card-body p-0">
          <div className="settings-wrapper d-flex">
            {/* Start Settings Sidebar */}
            <SettingsSidebar/>
            {/* End Settings Sidebar */}
            <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
              <div className="card-header border-bottom px-0 mx-3">
                <div className="d-flex align-items-center justify-content-between">
                  <h5 className="fw-bold">System Update</h5>
                  <Link
                    href="#"
                    className="btn btn-primary"
                  >
                    Check for Update
                  </Link>
                </div>
              </div>
              <div className="card-body px-0 mx-3">
                <div className="d-flex align-items-center mb-3">
                  <span className="p-2 bg-light rounded-circle d-inline-flex align-items-center justify-content-center text-primary me-1">
                    <i className="ti ti-circle-check-filled fs-20" />
                  </span>
                  <div>
                    <div className="d-flex align-items-center mb-1">
                      <h6 className="fs-14 mb-0 me-2">You are up to date</h6>
                      <span className="badge badge-soft-primary border border-primary fw-medium">
                        Current Version : 8.0
                      </span>
                    </div>
                    <span className="fs-13">Last Checked : Today 10:30 AM</span>
                  </div>
                </div>
                <div className="p-3 bg-light border rounded-2 mb-3">
                  <p className="mb-0">
                    <i className="ti ti-info-circle me-1 text-info" />
                    Before updating, it's best to back up your files and
                    database and review the changelog.
                  </p>
                </div>
                {/* start row */}
                <div className="row">
                  <div className="col-lg-6">
                    <div className="mb-0">
                      <label className="form-label">
                        Purchase Key<span className="text-danger ms-1">*</span>
                      </label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  {/* end col */}
                  <div className="col-lg-6">
                    <div className="mb-0">
                      <label className="form-label">
                        User Name<span className="text-danger ms-1">*</span>
                      </label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  {/* end col */}
                </div>
                {/* end row */}
              </div>
              {/* end card body */}
            </div>
            {/* end card */}
          </div>
        </div>
        {/* end card body */}
      </div>
      {/* end card */}
    </div>
    {/* End Content */}
    {/* Footer Start */}
    <div className="footer text-center bg-white p-2 border-top">
      <p className="text-dark mb-0">
        2025 ©
        <Link href="#" className="link-primary">
          Preclinic
        </Link>
        , All Rights Reserved
      </p>
    </div>
    {/* Footer End */}
  </div>
  {/* ========================
			End Page Content
		========================= */}
</>

  )
}

export default SystemUpdateComponent

// vue/template/src/views/pages/settings/others-settings/system-update.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content" id="profilePage">
      <!-- Page Header -->
      <div class="mb-3 border-bottom pb-3">
        <h4 class="fw-bold mb-0">Settings</h4>
      </div>
      <!-- End Page Header -->

      <div class="card">
        <div class="card-body p-0">
          <div class="settings-wrapper d-flex">
            <!-- Start Settings Sidebar -->
            <settings-sidebar></settings-sidebar>
            <!-- End Settings Sidebar -->

            <div class="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
              <div class="card-header border-bottom px-0 mx-3">
                <div class="d-flex align-items-center justify-content-between">
                  <h5 class="fw-bold">System Update</h5>
                  <a
                    href="javascript:void(0);"
                    class="btn btn-primary"
                    data-bs-toggle="modal"
                    data-bs-target="#generate"
                    >Check for Update</a
                  >
                </div>
              </div>
              <div class="card-body px-0 mx-3">
                <div class="d-flex align-items-center mb-3">
                  <span
                    class="p-2 bg-light rounded-circle d-inline-flex align-items-center justify-content-center text-primary me-1"
                    ><i class="ti ti-circle-check-filled fs-20"></i
                  ></span>
                  <div>
                    <div class="d-flex align-items-center mb-1">
                      <h6 class="fs-14 mb-0 me-2">You are up to date</h6>
                      <span
                        class="badge badge-soft-primary border border-primary fw-medium"
                        >Current Version : 8.0</span
                      >
                    </div>
                    <span class="fs-13">Last Checked : Today 10:30 AM</span>
                  </div>
                </div>

                <div class="p-3 bg-light border rounded-2 mb-3">
                  <p class="mb-0">
                    <i class="ti ti-info-circle me-1 text-info"></i>Before updating, it's
                    best to back up your files and database and review the changelog.
                  </p>
                </div>

                <!-- start row -->
                <div class="row">
                  <div class="col-lg-6">
                    <div class="mb-0">
                      <label class="form-label"
                        >Purchase Key<span class="text-danger ms-1">*</span></label
                      >
                      <input type="text" class="form-control" />
                    </div>
                  </div>
                  <!-- end col -->
                  <div class="col-lg-6">
                    <div class="mb-0">
                      <label class="form-label"
                        >User Name<span class="text-danger ms-1">*</span></label
                      >
                      <input type="text" class="form-control" />
                    </div>
                  </div>
                  <!-- end col -->
                </div>
                <!-- end row -->
              </div>
              <!-- end card body -->
            </div>
            <!-- end card -->
          </div>
        </div>
        <!-- end card body -->
      </div>
      <!-- end card -->
    </div>
    <!-- End Content -->

    <!-- Footer Start -->
    <div class="footer text-center bg-white p-2 border-top">
      <p class="text-dark mb-0">
        2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All
        Rights Reserved
      </p>
    </div>
    <!-- Footer End -->
  </div>
</template>
