// vue/template/src/views/pages/settings/finance-settings/tax-rates-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content" id="profilePage">
      <!-- Page Header -->
      <div class="mb-3 border-bottom pb-3">
        <h4 class="fw-bold mb-0">Settings</h4>
      </div>
      <!-- End Page Header -->

      <div class="card">
        <div class="card-body p-0">
          <div class="settings-wrapper d-flex">
            <!-- Start Settings Sidebar -->
            <settings-sidebar></settings-sidebar>
            <!-- End Settings Sidebar -->

            <!-- start row -->
            <div class="row">
              <div class="col-lg-12">
                <div class="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div class="card-header border-bottom px-0 mx-3">
                    <div class="d-flex align-items-center justify-content-between">
                      <h5 class="fw-bold">Tax Rates</h5>
                      <a
                        href="javascript:void(0);"
                        class="btn btn-primary"
                        data-bs-toggle="modal"
                        data-bs-target="#add_tax_rate"
                        ><i class="ti ti-plus me-1"></i>New Bank Account</a
                      >
                    </div>
                  </div>
                  <div class="card-body px-0 mx-3">
                    <!-- Table List -->
                    <div class="table-responsive border">
                      <table class="table table-nowrap">
                        <thead class="tablehead-light">
                          <tr>
                            <th>Tax Name</th>
                            <th>Tax Rate</th>
                            <th>Created On</th>
                            <th>Status</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>VAT</td>
                            <td>10%</td>
                            <td>30 Apr 2025</td>
                            <td>
                              <span
                                class="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2"
                                >Active</span
                              >
                            </td>
                            <td class="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                class="btn p-1 btn-white border"
                              >
                                <i class="ti ti-dots-vertical"></i>
                              </a>
                              <ul class="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_tax_rate"
                                    >Edit</a
                                  >
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_tax_rate"
                                    >Delete</a
                                  >
                                </li>
                              </ul>
                            </td>
                          </tr>
                          <tr>
                            <td>CGST</td>
                            <td>08%</td>
                            <td>15 Apr 2025</td>
                            <td>
                              <span
                                class="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2"
                                >Active</span
                              >
                            </td>
                            <td class="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                class="btn p-1 btn-white border"
                              >
                                <i class="ti ti-dots-vertical"></i>
                              </a>
                              <ul class="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_tax_rate"
                                    >Edit</a
                                  >
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_tax_rate"
                                    >Delete</a
                                  >
                                </li>
                              </ul>
                            </td>
                          </tr>
                          <tr>
                            <td>SGST</td>
                            <td>10%</td>
                            <td>05 Mar 2025</td>
                            <td>
                              <span
                                class="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2"
                                >Active</span
                              >
                            </td>
                            <td class="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                class="btn p-1 btn-white border"
                              >
                                <i class="ti ti-dots-vertical"></i>
                              </a>
                              <ul class="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_tax_rate"
                                    >Edit</a
                                  >
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_tax_rate"
                                    >Delete</a
                                  >
                                </li>
                              </ul>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <!-- /Table List -->
                  </div>
                  <!-- end card body -->
                </div>
                <!-- end card -->
              </div>
              <!-- end col -->
              <div class="col-lg-12">
                <div class="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div class="card-header border-bottom px-0 mx-3">
                    <div class="d-flex align-items-center justify-content-between">
                      <h5 class="fw-bold">Tax Group</h5>
                      <a
                        href="javascript:void(0);"
                        class="btn btn-primary"
                        data-bs-toggle="modal"
                        data-bs-target="#add_tax_group"
                        ><i class="ti ti-plus me-1"></i>New Tax Group</a
                      >
                    </div>
                  </div>
                  <div class="card-body px-0 mx-3">
                    <!-- Table List -->
                    <div class="table-responsive border">
                      <table class="table table-nowrap">
                        <thead class="tablehead-light">
                          <tr>
                            <th>Tax Name</th>
                            <th>Tax Rate</th>
                            <th>Created On</th>
                            <th>Status</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>GST</td>
                            <td>18%</td>
                            <td>20 Mar 2025</td>
                            <td>
                              <span
                                class="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2"
                                >Active</span
                              >
                            </td>
                            <td class="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                class="btn p-1 btn-white border"
                              >
                                <i class="ti ti-dots-vertical"></i>
                              </a>
                              <ul class="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_tax_group"
                                    >Edit</a
                                  >
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_tax_group"
                                    >Delete</a
                                  >
                                </li>
                              </ul>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <!-- /Table List -->
                  </div>
                  <!-- end card body -->
                </div>
                <!-- end card -->
              </div>
              <!-- end col -->
            </div>
            <!-- end row -->
          </div>
        </div>
        <!-- end card body -->
      </div>
      <!-- end card -->
    </div>
    <!-- End Content -->

    <!-- Footer Start -->
    <div class="footer text-center bg-white p-2 border-top">
      <p class="text-dark mb-0">
        2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All
        Rights Reserved
      </p>
    </div>
    <!-- Footer End -->
  </div>
  <!-- Start Add Categories -->
  <div id="add_tax_rate" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="text-dark modal-title fw-bold">Add Tax Rate</h5>
          <button
            type="button"
            class="btn-close btn-close-modal custom-btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i class="fa-solid fa-x"></i>
          </button>
        </div>
        <form>
          <div class="modal-body">
            <div class="mb-3">
              <label class="form-label"
                >Tax Name<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" />
            </div>
            <div class="mb-0">
              <label class="form-label"
                >Tax Rate (%)<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" />
            </div>
          </div>
          <div class="modal-footer d-flex align-items-center gap-1">
            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
              Add Tax Rate
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- End Add Categories -->

  <!-- Start Edit Categories -->
  <div id="edit_tax_rate" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="text-dark modal-title fw-bold">Edit Tax Rate</h5>
          <button
            type="button"
            class="btn-close btn-close-modal custom-btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i class="fa-solid fa-x"></i>
          </button>
        </div>
        <form>
          <div class="modal-body">
            <div class="mb-3">
              <label class="form-label"
                >Tax Name<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" value="VAT" />
            </div>
            <div class="mb-3">
              <label class="form-label"
                >Tax Rate (%)<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" value="10%" />
            </div>
            <div class="mb-0">
              <div class="d-flex align-items-center justify-content-between">
                <label class="form-label">Status</label>
                <div class="form-check form-switch ps-0">
                  <input class="form-check-input m-0" type="checkbox" checked="" />
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer d-flex align-items-center gap-1">
            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- End Edit Categories -->

  <!-- Start Delete Modal  -->
  <div class="modal fade" id="delete_tax_rate">
    <div class="modal-dialog modal-dialog-centered modal-sm">
      <div class="modal-content">
        <div class="modal-body text-center position-relative">
          <img
            src="@/assets/img/bg/delete-modal-bg-01.png"
            alt=""
            class="img-fluid position-absolute top-0 start-0"
          />
          <img
            src="@/assets/img/bg/delete-modal-bg-02.png"
            alt=""
            class="img-fluid position-absolute bottom-0 end-0"
          />
          <div class="mb-3">
            <span class="avatar avatar-lg bg-danger text-white"
              ><i class="ti ti-trash fs-24"></i
            ></span>
          </div>
          <h5 class="fw-bold mb-1">Delete Confirmation</h5>
          <p class="mb-3">Are you sure want to delete?</p>
          <div class="d-flex justify-content-center">
            <a
              href="javascript:void(0);"
              class="btn btn-light position-relative z-1 me-3"
              data-bs-dismiss="modal"
              >Cancel</a
            >
            <a
              href="javascript:void(0);"
              class="btn btn-danger position-relative z-1"
              data-bs-dismiss="modal"
              >Yes, Delete</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Delete Modal  -->

  <!-- Start Add Categories -->
  <div id="add_tax_group" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="text-dark modal-title fw-bold">Add Tax Group</h5>
          <button
            type="button"
            class="btn-close btn-close-modal custom-btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i class="fa-solid fa-x"></i>
          </button>
        </div>
        <form>
          <div class="modal-body">
            <div class="mb-3">
              <label class="form-label"
                >Tax Name<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" />
            </div>
            <div class="mb-0">
              <label class="form-label"
                >Sub Taxes<span class="text-danger ms-1">*</span></label
              >
              <vue3-tags-input
                class="input-tags form-control"
                type="text"
                id="inputBox2"
                data-role="tagsinput"
                name="specialist"
                value="Tag1"
                :tags="tagsOne"
              />
            </div>
          </div>
          <div class="modal-footer d-flex align-items-center gap-1">
            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
              Add Tax Group
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- End Add Categories -->

  <!-- Start Edit Categories -->
  <div id="edit_tax_group" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="text-dark modal-title fw-bold">Edit Tax Group</h5>
          <button
            type="button"
            class="btn-close btn-close-modal custom-btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i class="fa-solid fa-x"></i>
          </button>
        </div>
        <form>
          <div class="modal-body">
            <div class="mb-3">
              <label class="form-label"
                >Tax Name<span class="text-danger ms-1">*</span></label
              >
              <input type="text" class="form-control" />
            </div>
            <div class="mb-3">
              <label class="form-label"
                >Sub Taxes<span class="text-danger ms-1">*</span></label
              >
              <vue3-tags-input
                class="input-tags form-control"
                type="text"
                id="inputBox2"
                data-role="tagsinput"
                name="specialist"
                value="Tag1"
                :tags="tagsTwo"
              />
            </div>
            <div class="mb-0">
              <div class="d-flex align-items-center justify-content-between">
                <label class="form-label">Status</label>
                <div class="form-check form-switch ps-0">
                  <input class="form-check-input m-0" type="checkbox" checked="" />
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer d-flex align-items-center gap-1">
            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- End Edit Categories -->

  <!-- Start Delete Modal  -->
  <div class="modal fade" id="delete_tax_group">
    <div class="modal-dialog modal-dialog-centered modal-sm">
      <div class="modal-content">
        <div class="modal-body text-center position-relative">
          <img
            src="@/assets/img/bg/delete-modal-bg-01.png"
            alt=""
            class="img-fluid position-absolute top-0 start-0"
          />
          <img
            src="@/assets/img/bg/delete-modal-bg-02.png"
            alt=""
            class="img-fluid position-absolute bottom-0 end-0"
          />
          <div class="mb-3">
            <span class="avatar avatar-lg bg-danger text-white"
              ><i class="ti ti-trash fs-24"></i
            ></span>
          </div>
          <h5 class="fw-bold mb-1">Delete Confirmation</h5>
          <p class="mb-3">Are you sure want to delete?</p>
          <div class="d-flex justify-content-center">
            <a
              href="javascript:void(0);"
              class="btn btn-light position-relative z-1 me-3"
              data-bs-dismiss="modal"
              >Cancel</a
            >
            <a
              href="javascript:void(0);"
              data-bs-dismiss="modal"
              class="btn btn-danger position-relative z-1"
              >Yes, Delete</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Delete Modal  -->
</template>
<script>
import Vue3TagsInput from "vue3-tags-input";
export default {
  components: {
    Vue3TagsInput,
  },
  data() {
    return {
      tagsOne: ["CGST, SGST"],
      tagsTwo: ["CGST, SGST"],
    };
  },
};
</script>

// nextjs/template/src/components/pages/settings/finance-settings/tax-rates-settings/taxRatesSettings.tsx
"use client";

import Link from "next/link";
import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar";
import Modals from "./modals/modals";

const TaxRatesSettingsComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content" id="profilePage">
          {/* Page Header */}
          <div className="mb-3 border-bottom pb-3">
            <h4 className="fw-bold mb-0">Settings</h4>
          </div>
          {/* End Page Header */}
          <div className="card">
            <div className="card-body p-0">
              <div className="settings-wrapper d-flex">
                {/* Start Settings Sidebar */}
                <SettingsSidebar />
                {/* End Settings Sidebar */}
                {/* start row */}
                <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div className="card-header border-bottom px-0 mx-3">
                    <div className="d-flex align-items-center justify-content-between">
                      <h5 className="fw-bold">Bank Account</h5>
                      <a
                        href="javascript:void(0);"
                        className="btn btn-primary"
                        data-bs-toggle="modal"
                        data-bs-target="#add_reason"
                      >
                        <i className="ti ti-plus me-1" />
                        New Bank Account
                      </a>
                    </div>
                  </div>
                  <div className="card-body px-0 mx-3">
                    {/* Table List */}
                    <div className="table-responsive border">
                      <table className="table table-nowrap">
                        <thead className="tablehead-light">
                          <tr>
                            <th>Name</th>
                            <th>Bank</th>
                            <th>Branch</th>
                            <th>Account Number</th>
                            <th>ABA Number</th>
                            <th>Status</th>
                            <th />
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Andrew Simons</td>
                            <td>JPM</td>
                            <td>New York</td>
                            <td>**** **** 1832</td>
                            <td>021000021</td>
                            <td>
                              <span className="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2">
                                Active
                              </span>
                            </td>
                            <td className="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                className="btn p-1 btn-white border"
                              >
                                <i className="ti ti-dots-vertical" />
                              </a>
                              <ul className="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_reason"
                                  >
                                    Edit
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_reason"
                                  >
                                    Delete
                                  </a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          <tr>
                            <td>David Steiger</td>
                            <td>BofA</td>
                            <td>Los Angeles</td>
                            <td>**** **** 1596</td>
                            <td>121000358</td>
                            <td>
                              <span className="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2">
                                Active
                              </span>
                            </td>
                            <td className="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                className="btn p-1 btn-white border"
                              >
                                <i className="ti ti-dots-vertical" />
                              </a>
                              <ul className="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_reason"
                                  >
                                    Edit
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_reason"
                                  >
                                    Delete
                                  </a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          <tr>
                            <td>Darin Mabry</td>
                            <td>WFB</td>
                            <td>Charlotte</td>
                            <td>**** **** 1982</td>
                            <td>121000248</td>
                            <td>
                              <span className="badge bg-soft-success fs-13 fw-medium text-success border border-success py-1 px-2">
                                Active
                              </span>
                            </td>
                            <td className="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                className="btn p-1 btn-white border"
                              >
                                <i className="ti ti-dots-vertical" />
                              </a>
                              <ul className="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_reason"
                                  >
                                    Edit
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_reason"
                                  >
                                    Delete
                                  </a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                          <tr>
                            <td>Mark Neiman</td>
                            <td>USB</td>
                            <td>Chicago</td>
                            <td>**** **** 1645</td>
                            <td>123000220</td>
                            <td>
                              <span className="badge bg-soft-danger fs-13 fw-medium text-danger border border-danger py-1 px-2">
                                Inactive
                              </span>
                            </td>
                            <td className="action-item">
                              <a
                                href="javascript:void(0);"
                                data-bs-toggle="dropdown"
                                className="btn p-1 btn-white border"
                              >
                                <i className="ti ti-dots-vertical" />
                              </a>
                              <ul className="dropdown-menu p-2">
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#edit_reason"
                                  >
                                    Edit
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="javascript:void(0);"
                                    className="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_reason"
                                  >
                                    Delete
                                  </a>
                                </li>
                              </ul>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    {/* /Table List */}
                  </div>
                </div>
                {/* end row */}
              </div>
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
      <Modals />
    </>
  );
};

export default TaxRatesSettingsComponent;
