// vue/template/src/views/pages/authentication/email-verification/email-verification-cover.vue
<template>
  <div class="auth-bg position-relative overflow-hidden">
    <!-- Start Content -->
    <div class="container-fuild position-relative z-1">
      <div
        class="w-100 overflow-hidden position-relative flex-wrap d-block vh-100 bg-white"
      >
        <!-- start row-->
        <div class="row">
          <div class="col-lg-6 p-0">
            <div
              class="login-backgrounds login-covers bg-primary d-lg-flex align-items-center justify-content-center d-none flex-wrap p-4 position-relative h-100 z-0"
            >
              <div class="authentication-card w-100">
                <div class="authen-overlay-item w-100">
                  <div class="authen-head text-center">
                    <h1 class="text-white fs-32 fw-bold mb-2">
                      Seamless healthcare access <br />
                      with smart, modern clinic
                    </h1>
                    <p class="text-light fw-normal text-light">
                      Experience efficient, secure, and user-friendly healthcare
                      management designed for modern clinics and growing practices.
                    </p>
                  </div>
                  <div class="mt-4 mx-auto authen-overlay-img">
                    <img src="@/assets/img/auth/cover-imgs-1.png" alt="Img" />
                  </div>
                </div>
              </div>
              <img
                src="@/assets/img/auth/cover-imgs-2.png"
                alt="cover-imgs-2"
                class="img-fluid cover-img"
              />
            </div>
          </div>
          <!-- end row-->

          <div class="col-lg-6 col-md-12 col-sm-12">
            <div
              class="row justify-content-center align-items-center overflow-auto flex-wrap vh-100"
            >
              <div class="col-md-8 mx-auto">
                <form
                  @submit.prevent="submitForm"
                  class="d-flex justify-content-center align-items-center"
                >
                  <div
                    class="d-flex flex-column justify-content-lg-center p-4 p-lg-0 pb-0 flex-fill"
                  >
                    <div class="mx-auto mb-4 text-center">
                      <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
                    </div>
                    <div class="card border-1 p-lg-3 shadow-md rounded-3 mb-4">
                      <div class="card-body">
                        <div class="mb-3 text-center">
                          <span
                            ><i class="ti ti-circle-check-filled fs-48 text-success"></i
                          ></span>
                        </div>
                        <div class="text-center mb-3">
                          <h5 class="mb-1 fs-20 fw-bold">Email Sent!</h5>
                          <p class="mb-0">Check your email & change your password.</p>
                        </div>
                        <div class="mt-3">
                          <button type="submit" class="btn bg-primary text-white w-100">
                            Reset Password
                          </button>
                        </div>
                      </div>
                      <!-- end card body -->
                    </div>
                    <!-- end card -->
                  </div>
                </form>
                <p class="fs-14 text-dark text-center mt-4">
                  Copyright &copy; 2025 - Preclinic
                </p>
              </div>
              <!-- end row-->
            </div>
          </div>
        </div>
        <!-- end row-->
      </div>
    </div>
    <!-- End Content -->
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {
    submitForm() {
      this.$router.push("/two-step-verification-cover");
    },
  },
};
</script>

// nextjs/template/src/components/auth/email-verification/emailVerificationCover.tsx
"use client";

import ImageWithBasePath from "@/core/imageWithBasePath";
import { all_routes } from "@/routes/all_routes";
import Link from "next/link";

const EmailVerificationCoverComponent = () => {
  return (
    <>
      {/* Start Content */}
      <div className="auth-bg position-relative overflow-hidden">
        <div className="container-fuild position-relative z-1">
          <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100 bg-white">
            {/* start row*/}
            <div className="row">
              <div className="col-lg-6 p-0">
                <div className="login-backgrounds login-covers bg-primary d-lg-flex align-items-center justify-content-center d-none flex-wrap p-4 position-relative h-100 z-0">
                  <div className="authentication-card w-100">
                    <div className="authen-overlay-item w-100">
                      <div className="authen-head text-center">
                        <h1 className="text-white fs-32 fw-bold mb-2">
                          Seamless healthcare access <br /> with smart, modern
                          clinic
                        </h1>
                        <p className="text-light fw-normal text-light">
                          
                          Experience efficient, secure, and user-friendly
                          healthcare management designed for modern clinics and
                          growing practices.
                        </p>
                      </div>
                      <div className="mt-4 mx-auto authen-overlay-img">
                        <ImageWithBasePath
                          src="assets/img/auth/cover-imgs-1.png"
                          alt="Img"
                        />
                      </div>
                    </div>
                  </div>
                  <ImageWithBasePath
                    src="assets/img/auth/cover-imgs-2.png"
                    alt="cover-imgs-2"
                    className="img-fluid cover-img"
                  />
                </div>
              </div>
              {/* end row*/}
              <div className="col-lg-6 col-md-12 col-sm-12">
                <div className="row justify-content-center align-items-center overflow-auto flex-wrap vh-100">
                  <div className="col-md-8 mx-auto">
                    <form
                      className="d-flex justify-content-center align-items-center"
                    >
                      <div className="d-flex flex-column justify-content-lg-center p-4 p-lg-0 pb-0 flex-fill">
                        <div className=" mx-auto mb-4 text-center">
                          <ImageWithBasePath
                            src="assets/img/logo.svg"
                            className="img-fluid"
                            alt="Logo"
                          />
                        </div>
                        <div className="card border-1 p-lg-3 shadow-md rounded-3 mb-4">
                          <div className="card-body">
                            <div className="mb-3 text-center">
                              <span>
                                <i className="ti ti-circle-check-filled fs-48 text-success" />
                              </span>
                            </div>
                            <div className="text-center mb-3">
                              <h5 className="mb-1 fs-20 fw-bold">Email Sent!</h5>
                              <p className="mb-0">
                                
                                Check your email &amp; change your password.
                              </p>
                            </div>
                            <div className="mt-3">
                              <Link
                                href={all_routes.twostepverificationcover}
                                className="btn bg-primary text-white w-100"
                              >
                                Reset Password
                              </Link>
                            </div>
                          </div>
                          {/* end card body */}
                        </div>
                        {/* end card */}
                      </div>
                    </form>
                    <p className="fs-14 text-dark text-center mt-4">
                      
                      Copyright © 2025 - Preclinic
                    </p>
                  </div>
                  {/* end row*/}
                </div>
              </div>
            </div>
            {/* end row*/}
          </div>
        </div>
      </div>
      {/* End Content */}
    </>
  );
};

export default EmailVerificationCoverComponent;
