// angular/template/src/app/features/settings/website-settings/maintenance-mode-settings/maintenance-mode-settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
  
@Component({
  selector: 'app-maintenance-mode-settings',
  templateUrl: './maintenance-mode-settings.component.html',
  styleUrls: ['./maintenance-mode-settings.component.scss'],
  imports: [CommonModule]
})
export class MaintenanceModeSettingsComponent {

}


                                <div class="card-header border-bottom px-0 mx-3">
                                    <h5 class="fw-bold">Maintenance Mode</h5>
                                </div>
                                <div class="card-body px-0 mx-3">
                                    <form>

                                        <!-- start row -->
                                        <div class="row border-bottom mb-3">
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Image </label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <input type="file" class="form-control">
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-2">
                                                        <label class="form-label mb-0">Description  </label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-10">
                                                        <textarea class="form-control" rows="3" placeholder="Description"></textarea>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-2">
                                                    <label class="form-label mb-0">Status</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-10">
                                                    <div class="form-check form-switch ps-0">
                                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                                    </div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->

                                        </div>
                                        <!-- end row -->

                                        <div class="d-flex align-items-center justify-content-end">
                                            <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                                            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                                        </div>
                                        
                                    </form>
                                </div>

// vue/template/src/views/pages/settings/website-settings/maintenance-mode-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content" id="profilePage">
      <!-- Page Header -->
      <div class="mb-3 border-bottom pb-3">
        <h4 class="fw-bold mb-0">Settings</h4>
      </div>
      <!-- End Page Header -->

      <div class="card">
        <div class="card-body p-0">
          <div class="settings-wrapper d-flex">
            <!-- Start Settings Sidebar -->
            <settings-sidebar></settings-sidebar>
            <!-- End Settings Sidebar -->

            <div class="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
              <div class="card-header border-bottom px-0 mx-3">
                <h5 class="fw-bold">Maintenance Mode</h5>
              </div>
              <div class="card-body px-0 mx-3">
                <form>
                  <!-- start row -->
                  <div class="row border-bottom mb-3">
                    <div class="col-lg-12">
                      <!-- start row -->
                      <div class="row align-items-center mb-3">
                        <div class="col-lg-2">
                          <label class="form-label mb-0">Image </label>
                        </div>
                        <!-- end col -->
                        <div class="col-lg-10">
                          <input type="file" class="form-control" />
                        </div>
                        <!-- end col -->
                      </div>
                      <!-- end row -->
                    </div>
                    <!-- end col -->
                    <div class="col-lg-12">
                      <!-- start row -->
                      <div class="row align-items-center mb-3">
                        <div class="col-lg-2">
                          <label class="form-label mb-0">Description </label>
                        </div>
                        <!-- end col -->
                        <div class="col-lg-10">
                          <textarea
                            class="form-control"
                            rows="3"
                            placeholder="Description"
                          ></textarea>
                        </div>
                        <!-- end col -->
                      </div>
                      <!-- end row -->
                    </div>
                    <!-- end col -->
                    <div class="col-lg-12">
                      <!-- start row -->
                      <div class="row align-items-center mb-3">
                        <div class="col-lg-2">
                          <label class="form-label mb-0">Status</label>
                        </div>
                        <!-- end col -->
                        <div class="col-lg-10">
                          <div class="form-check form-switch ps-0">
                            <input
                              class="form-check-input m-0"
                              type="checkbox"
                              checked=""
                            />
                          </div>
                        </div>
                        <!-- end col -->
                      </div>
                      <!-- end row -->
                    </div>
                    <!-- end col -->
                  </div>
                  <!-- end row -->

                  <div class="d-flex align-items-center justify-content-end">
                    <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                    <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- end card body -->
      </div>
      <!-- end card -->
    </div>
    <!-- End Content -->

    <!-- Footer Start -->
    <div class="footer text-center bg-white p-2 border-top">
      <p class="text-dark mb-0">
        2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All
        Rights Reserved
      </p>
    </div>
    <!-- Footer End -->
  </div>
</template>
