// angular/template/src/app/features/settings/clinic-settings/appointment-settings/appointment-settings.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../../../src/app/shared/routes/routes';
import { CommonModule } from '@angular/common';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-appointment-settings',
  templateUrl: './appointment-settings.component.html',
  styleUrls: ['./appointment-settings.component.scss'],
  imports:[CommonModule,MatSelectModule]
})
export class AppointmentSettingsComponent {
routes=routes

trash:boolean=false;
isTrash():void{
  this.trash=true;
}
  formData: any[] = []; 

  addNewRow() {
    this.formData.push({});
  }

  removeRow(index: number) {
      this.formData.splice(index, 1);
  }
  trackByIndex(index: number, item: any) {
    return index;
  }
}


                                <div class="card-header border-bottom px-0 mx-3">
                                    <div class="d-flex align-items-center">
                                        <h5 class="fw-bold">Appointment Reminders</h5>
                                    </div>
                                </div>
                                <div class="card-body px-0 mx-3 break-hours-section" id="break-hours-section">

                                    <!-- start row -->
                                    <div class="row row-gap-2 align-items-center justify-content-between pb-3 mb-3 border-bottom">
                                        <div class="col-lg-11">
                                            <h6 class="fs-14 fw-medium">Automatically notify clients about upcoming appointments.</h6>
                                        </div><!-- end col -->
                                        <div class="col-lg-1">
                                            <div class="form-check form-switch">
                                                <input class="form-check-input text-end me-1" type="checkbox" checked="">
                                            </div>
                                        </div><!-- end col -->
                                        <div class="col-lg-11">
                                            <h6 class="fs-14 fw-medium">Reminders for weekend appointments go out on Friday.</h6>
                                        </div><!-- end col -->
                                        <div class="col-lg-1">
                                            <div class="form-check form-switch">
                                                <input class="form-check-input text-end me-1" type="checkbox">
                                            </div>
                                        </div><!-- end col -->
                                        <div class="col-lg-11">
                                            <h6 class="fs-14 fw-medium">Appointments auto-cancel if clients reply 'No' or 'Cancel' to reminders.</h6>
                                        </div><!-- end col -->
                                        <div class="col-lg-1">
                                            <div class="form-check form-switch">
                                                <input class="form-check-input text-end me-1" type="checkbox" checked="">
                                            </div>
                                        </div><!-- end col -->
                                    </div>
                                    <!-- end row -->

                                    <div>
                                        <h5 class="fw-bold mb-3">Automatic Reminders</h5>

                                        <div class="reminder-list mb-3 border-bottom">

                                        <div class="row d-flex align-items-center mb-3 reminder-list-item">
                                            <div class="col-md-2">
                                                <h6 class="fs-14 fw-medium mb-0">Reminder </h6>
                                            </div>
                                            <div class="col-md-10 flex-grow-1">
                                                <div class="d-flex align-items-center justify-content-end">
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Email</mat-option>
                                                            <mat-option value="1">SMS</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Select</mat-option>
                                                            <mat-option value="1">Welcome Email</mat-option>
                                                            <mat-option value="1">Appointment Reminder</mat-option>
                                                            <mat-option value="1">Appointment Confirmation</mat-option>
                                                            <mat-option value="1">Appointment Rescheduled</mat-option>
                                                            <mat-option value="1">Appointment Cancelled</mat-option>
                                                            <mat-option value="1">Test Result Notification</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">01 </mat-option>
                                                            <mat-option value="1">02</mat-option>
                                                            <mat-option value="1">03</mat-option>
                                                            <mat-option value="1">05</mat-option>
                                                            <mat-option value="1">10</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <span class="me-2">
                                                        Days Before
                                                    </span>
                                                    <div class="d-flex align-items-center">
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 add-reminder" (click)="addNewRow()"><i class="ti ti-plus"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <ng-container  *ngFor="let item of formData; let i = index; trackBy: trackByIndex">
                                            <div class="row d-flex align-items-center mb-3 reminder-list-item">
                                        <div class="col-md-2">
                                            <h6 class="fs-14 fw-medium mb-0">Reminder </h6>
                                        </div>
                                            <div class="col-md-10 flex-grow-1">
                                            <div class="d-flex align-items-center justify-content-end">
                                                <div class="me-2">
                                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                                        <mat-option value="1">Email</mat-option>
                                                        <mat-option value="1">SMS</mat-option>
                                                    </mat-select>
                                                </div>
                                                <div class="me-2">
                                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                                        <mat-option value="1">Select</mat-option>
                                                        <mat-option value="1">Welcome Email</mat-option>
                                                        <mat-option value="1">Appointment Reminder</mat-option>
                                                        <mat-option value="1">Appointment Confirmation</mat-option>
                                                        <mat-option value="1">Appointment Rescheduled</mat-option>
                                                        <mat-option value="1">Appointment Cancelled</mat-option>
                                                        <mat-option value="1">Test Result Notification</mat-option>
                                                    </mat-select>
                                                </div>
                                                <div class="me-2">
                                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                                        <mat-option value="1">01 </mat-option>
                                                        <mat-option value="1">02</mat-option>
                                                        <mat-option value="1">03</mat-option>
                                                        <mat-option value="1">05</mat-option>
                                                        <mat-option value="1">10</mat-option>
                                                    </mat-select>
                                                </div>
                                                <span class="me-2">
                                                    Days Before
                                                </span>
                                                <div class="d-flex align-items-center">
                                                    <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                     <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 remove-reminder" (click)="removeRow(i)"><i class="ti ti-trash"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                            </div>
                                        </ng-container>
                                        <div class="row d-flex align-items-center mb-3 reminder-list-item" [ngClass]="{'d-none':trash}">
                                            <div class="col-md-2">
                                                <h6 class="fs-14 fw-medium mb-0">Reminder </h6>
                                            </div>
                                            <div class="col-md-10 flex-grow-1">
                                                <div class="d-flex align-items-center justify-content-end">
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Email</mat-option>
                                                            <mat-option value="1">SMS</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Select</mat-option>
                                                            <mat-option value="1">Welcome Email</mat-option>
                                                            <mat-option value="1">Appointment Reminder</mat-option>
                                                            <mat-option value="1">Appointment Confirmation</mat-option>
                                                            <mat-option value="1">Appointment Rescheduled</mat-option>
                                                            <mat-option value="1">Appointment Cancelled</mat-option>
                                                            <mat-option value="1">Test Result Notification</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <div class="me-2">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">01 </mat-option>
                                                            <mat-option value="1">02</mat-option>
                                                            <mat-option value="1">03</mat-option>
                                                            <mat-option value="1">05</mat-option>
                                                            <mat-option value="1">10</mat-option>
                                                        </mat-select>
                                                    </div>
                                                    <span class="me-2">
                                                        Days Before
                                                    </span>
                                                    <div class="d-flex align-items-center">
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 remove-reminder" (click)="isTrash()"><i class="ti ti-trash"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        </div>

                                         <div class=" pb-3 mb-3 border-bottom">
                                            <div class="d-flex align-items-center justify-content-between mb-3">
                                                <h5 class="fw-bold mb-0">Manual Reminders</h5>
                                            </div>
    
                                            <!-- start row -->
                                             <div class="row align-items-center row-gap-2 mb-3">
                                                <div class="col-lg-6">
                                                    <p class="text-dark fw-medium mb-0">SMS Reminder Template</p>
                                                </div><!-- end col -->
                                                <div class="col-lg-6">
                                                    <div class="d-flex align-items-center gap-3">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Select</mat-option>
                                                            <mat-option value="1">Appointment Confirmation</mat-option>
                                                            <mat-option value="1">Appointment Reminder</mat-option>
                                                            <mat-option value="1">Appointment Rescheduled</mat-option>
                                                            <mat-option value="1">Appointment Cancellation</mat-option>
                                                            <mat-option value="1">Test Results Notification</mat-option>
                                                            <mat-option value="1">Follow-Up Reminder</mat-option>
                                                        </mat-select>
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                    </div>
                                                </div><!-- end col -->
                                             </div>
                                             <!-- end row -->

                                             <!-- start row -->
                                             <div class="row align-items-center row-gap-2 mb-3">
                                                <div class="col-lg-6">
                                                    <p class="text-dark fw-medium mb-0">Email Reminder Template</p>
                                                </div><!-- end col -->
                                                <div class="col-lg-6">
                                                    <div class="d-flex align-items-center gap-3">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Select</mat-option>
                                                            <mat-option value="1">Welcome Email</mat-option>
                                                            <mat-option value="1">Appointment Confirmation</mat-option>
                                                            <mat-option value="1">Appointment Reminder</mat-option>
                                                            <mat-option value="1">Appointment Rescheduled</mat-option>
                                                            <mat-option value="1">Appointment Cancelled</mat-option>
                                                            <mat-option value="1">Test Result Notification</mat-option>
                                                        </mat-select>
                                                        <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                    </div>
                                                </div><!-- end col -->
                                             </div>
                                             <!-- end row -->

                                             <div class="border-top pt-3">

                                                <!-- start row -->
                                                 <div class="row align-items-center mb-3">
                                                    <div class="col-9">
                                                        <p class="mb-0 text-dark fw-medium">Send reminder automatically upon new appointment booking</p>
                                                    </div>
                                                    <div class="col-3">
                                                       <div class="d-flex align-items-center justify-content-end">
                                                            <div class="form-check form-switch">
                                                                <input class="form-check-input text-end me-1" type="checkbox" checked="">
                                                            </div>
                                                       </div>
                                                    </div>
                                                 </div>
                                                 <!-- start end -->

                                                 <!-- start row -->
                                                <div class="row align-items-center row-gap-2">
                                                    <div class="col-xl-5 col-lg-3">
                                                        <p class="text-dark fw-medium mb-0">Reminder</p>
                                                    </div><!-- end col -->
                                                    <div class="col-xl-7 col-lg-9">
                                                        <div class="d-flex align-items-center gap-3">
                                                             <mat-select class="custom-mat-select select" placeholder="Select">
                                                                <mat-option value="1">Email</mat-option>
                                                                <mat-option value="1">SMS</mat-option>
                                                            </mat-select>
                                                            <mat-select class="custom-mat-select select" placeholder="Select">
                                                                <mat-option value="1">Appointment Remainder</mat-option>
                                                                <mat-option value="1">Welcome Email</mat-option>
                                                                <mat-option value="1">Appointment Confirmation</mat-option>
                                                                <mat-option value="1">Appointment Reminder</mat-option>
                                                                <mat-option value="1">Appointment Rescheduled</mat-option>
                                                                <mat-option value="1">Appointment Cancelled</mat-option>
                                                                <mat-option value="1">Test Result Notification</mat-option>
                                                            </mat-select>
                                                            <a href="javascript:void(0);" class="btn btn-white p-2 border rounded-2 me-2"><i class="ti ti-edit"></i></a>
                                                        </div>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->
                                                </div>

                                         </div>
                                         
                                         <div class="d-flex align-items-center justify-content-end">
                                            <a href="javascript:void(0);" class="btn btn-light me-2">Cancel</a>
                                            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                                         </div>

                                    </div>
                                </div>

// nextjs/template/src/components/pages/settings/clinic-settings/appointment-settings/appointmentSettings.tsx
"use client";


import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar";
import {
  days,
  Email_Reminder,
  Reminder,
  SMS_Reminder,
  Welcome_Email,
} from "@/core/common/selectOption";
import CommonSelect from "@/core/common/common-select/commonSelect";
import Link from "next/link";

const AppointmentSettingsComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content" id="profilePage">
          {/* Page Header */}
          <div className="mb-3 border-bottom pb-3">
            <h4 className="fw-bold mb-0">Settings</h4>
          </div>
          {/* End Page Header */}
          <div className="card mb-0">
            <div className="card-body p-0">
              <div className="settings-wrapper d-flex">
                {/* Start Settings Sidebar */}
                <SettingsSidebar />
                {/* End Settings Sidebar */}
                <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
                  <div className="card-header border-bottom px-0 mx-3">
                    <div className="d-flex align-items-center">
                      <h5 className="fw-bold">Appointment Reminders</h5>
                    </div>
                  </div>
                  <div
                    className="card-body px-0 mx-3 break-hours-section"
                    id="break-hours-section"
                  >
                    {/* start row */}
                    <div className="row row-gap-2 align-items-center justify-content-between pb-3 mb-3 border-bottom">
                      <div className="col-lg-11">
                        <h6 className="fs-14 fw-medium">
                          Automatically notify clients about upcoming
                          appointments.
                        </h6>
                      </div>
                      {/* end col */}
                      <div className="col-lg-1">
                        <div className="form-check form-switch">
                          <input
                            className="form-check-input text-end me-1"
                            type="checkbox"
                            defaultChecked
                          />
                        </div>
                      </div>
                      {/* end col */}
                      <div className="col-lg-11">
                        <h6 className="fs-14 fw-medium">
                          Reminders for weekend appointments go out on Friday.
                        </h6>
                      </div>
                      {/* end col */}
                      <div className="col-lg-1">
                        <div className="form-check form-switch">
                          <input
                            className="form-check-input text-end me-1"
                            type="checkbox"
                          />
                        </div>
                      </div>
                      {/* end col */}
                      <div className="col-lg-11">
                        <h6 className="fs-14 fw-medium">
                          Appointments auto-cancel if clients reply 'No' or
                          'Cancel' to reminders.
                        </h6>
                      </div>
                      {/* end col */}
                      <div className="col-lg-1">
                        <div className="form-check form-switch">
                          <input
                            className="form-check-input text-end me-1"
                            type="checkbox"
                            defaultChecked
                          />
                        </div>
                      </div>
                      {/* end col */}
                    </div>
                    {/* end row */}
                    <div>
                      <h5 className="fw-bold mb-3">Automatic Reminders</h5>
                      <div className="reminder-list mb-3 border-bottom">
                        <div className="row d-flex align-items-center mb-3 reminder-list-item">
                          <div className="col-md-2">
                            <h6 className="fs-14 fw-medium mb-0">Reminder </h6>
                          </div>
                          <div className="col-md-10 flex-grow-1">
                            <div className="d-flex align-items-center justify-content-end">
                              <div className="me-2">
                                <CommonSelect
                                  options={Reminder}
                                  className="select"
                                  defaultValue={Reminder[0]}
                                />
                              </div>
                              <div className="me-2">
                                <CommonSelect
                                  options={Welcome_Email}
                                  className="select"
                                  defaultValue={Welcome_Email[0]}
                                />
                              </div>
                              <div className="me-2">
                                <CommonSelect
                                  options={days}
                                  className="select"
                                  defaultValue={days[0]}
                                />
                              </div>
                              <span className="me-2">Days Before</span>
                              <div className="d-flex align-items-center">
                                <Link
                                  href="#"
                                  className="btn btn-white p-2 border rounded-2 me-2"
                                >
                                  <i className="ti ti-edit" />
                                </Link>
                                <Link
                                  href="#"
                                  className="btn btn-white p-2 border rounded-2 add-reminder"
                                >
                                  <i className="ti ti-plus" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="row d-flex align-items-center mb-3 reminder-list-item">
                          <div className="col-md-2">
                            <h6 className="fs-14 fw-medium mb-0">Reminder </h6>
                          </div>
                          <div className="col-md-10 flex-grow-1">
                            <div className="d-flex align-items-center justify-content-end">
                              <div className="me-2">
                                <CommonSelect
                                  options={Reminder}
                                  className="select"
                                  defaultValue={Reminder[0]}
                                />
                              </div>
                              <div className="me-2">
                                <CommonSelect
                                  options={Welcome_Email}
                                  className="select"
                                  defaultValue={Welcome_Email[0]}
                                />
                              </div>
                              <div className="me-2">
                                <CommonSelect
                                  options={days}
                                  className="select"
                                  defaultValue={days[0]}
                                />
                              </div>
                              <span className="me-2">Days Before</span>
                              <div className="d-flex align-items-center">
                                <Link
                                  href="#"
                                  className="btn btn-white p-2 border rounded-2 me-2"
                                >
                                  <i className="ti ti-edit" />
                                </Link>
                                <Link
                                  href="#"
                                  className="btn btn-white p-2 border rounded-2 remove-reminder"
                                >
                                  <i className="ti ti-trash" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className=" pb-3 mb-3 border-bottom">
                        <div className="d-flex align-items-center justify-content-between mb-3">
                          <h5 className="fw-bold mb-0">Manual Reminders</h5>
                        </div>
                        {/* start row */}
                        <div className="row align-items-center row-gap-2 mb-3">
                          <div className="col-lg-6">
                            <p className="text-dark fw-medium mb-0">
                              SMS Reminder Template
                            </p>
                          </div>
                          {/* end col */}
                          <div className="col-lg-6">
                            <div className="d-flex align-items-center gap-3">
                              <CommonSelect
                                options={SMS_Reminder}
                                className="select"
                                defaultValue={SMS_Reminder[0]}
                              />
                              <Link
                                href="#"
                                className="btn btn-white p-2 border rounded-2 me-2"
                              >
                                <i className="ti ti-edit" />
                              </Link>
                            </div>
                          </div>
                          {/* end col */}
                        </div>
                        {/* end row */}
                        {/* start row */}
                        <div className="row align-items-center row-gap-2 mb-3">
                          <div className="col-lg-6">
                            <p className="text-dark fw-medium mb-0">
                              Email Reminder Template
                            </p>
                          </div>
                          {/* end col */}
                          <div className="col-lg-6">
                            <div className="d-flex align-items-center gap-3">
                              <CommonSelect
                                options={Email_Reminder}
                                className="select"
                                defaultValue={Email_Reminder[0]}
                              />
                              <Link
                                href="#"
                                className="btn btn-white p-2 border rounded-2 me-2"
                              >
                                <i className="ti ti-edit" />
                              </Link>
                            </div>
                          </div>
                          {/* end col */}
                        </div>
                        {/* end row */}
                        <div className="border-top pt-3">
                          {/* start row */}
                          <div className="row align-items-center mb-3">
                            <div className="col-9">
                              <p className="mb-0 text-dark fw-medium">
                                Send reminder automatically upon new appointment
                                booking
                              </p>
                            </div>
                            <div className="col-3">
                              <div className="d-flex align-items-center justify-content-end">
                                <div className="form-check form-switch">
                                  <input
                                    className="form-check-input text-end me-1"
                                    type="checkbox"
                                    defaultChecked
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                          {/* start end */}
                          {/* start row */}
                          <div className="row align-items-center row-gap-2">
                            <div className="col-xl-5 col-lg-3">
                              <p className="text-dark fw-medium mb-0">
                                Reminder
                              </p>
                            </div>
                            {/* end col */}
                            <div className="col-xl-7 col-lg-9">
                              <div className="d-flex align-items-center gap-3">
                                <CommonSelect
                                  options={Reminder}
                                  className="select"
                                  defaultValue={Reminder[0]}
                                />
                                <CommonSelect
                                  options={Welcome_Email}
                                  className="select"
                                  defaultValue={Welcome_Email[0]}
                                />
                                <Link
                                  href="#"
                                  className="btn btn-white p-2 border rounded-2 me-2"
                                >
                                  <i className="ti ti-edit" />
                                </Link>
                              </div>
                            </div>
                            {/* end col */}
                          </div>
                          {/* end row */}
                        </div>
                      </div>
                      <div className="d-flex align-items-center justify-content-end">
                        <Link href="#" className="btn btn-light me-2">
                          Cancel
                        </Link>
                        <Link href="#" className="btn btn-primary">
                          Save Changes
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default AppointmentSettingsComponent;
