// nextjs/template/src/components/pages/pages/profile.tsx
"use client";

import Link from "next/link";
import ImageWithBasePath from "@/core/imageWithBasePath";
import { City, Country, State } from "@/core/common/selectOption";
import CommonSelect from "@/core/common/common-select/commonSelect";

const ProfileComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content" id="profilePage">
          {/* Page Header */}
          <div className="mb-3 border-bottom pb-3">
            <h4 className="fw-bold mb-0">Profile</h4>
          </div>
          {/* End Page Header */}
          <div className="card">
            <div className="card-body">
              {/* start row */}
              <div className="row border-bottom mb-3">
                <div className="col-lg-12">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-2">
                      <label className="form-label mb-0">
                        Profile Image<span className="text-danger ms-1">*</span>
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-10">
                      <div className="profile-container">
                        <ImageWithBasePath
                          src="assets/img/users/user-08.jpg"
                          alt="Profile"
                        />
                        <div className="overlay-btn">
                          <Link
                            href="#"
                            className="text-white"
                            id="uploadTrigger"
                          >
                            <i className="ti ti-photo fs-10" />
                          </Link>
                        </div>
                        <input
                          type="file"
                          id="profileUpload"
                          style={{ display: "none" }}
                        />
                      </div>
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">
                        First Name<span className="text-danger ms-1">*</span>
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">
                        Last Name<span className="text-danger ms-1">*</span>
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">
                        Email<span className="text-danger ms-1">*</span>
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">
                        Phone Number<span className="text-danger ms-1">*</span>
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
              </div>
              {/* end row */}
              {/* start row */}
              <div className="row border-bottom mb-3">
                <div className="mb-3">
                  <h5 className="fw-bold mb-0">Address Information</h5>
                </div>
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">Address Line 1</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">Address Line 2</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">Country</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <CommonSelect
                        options={Country}
                        className="select"
                        defaultValue={Country[0]}
                      />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">State</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <CommonSelect
                        options={State}
                        className="select"
                        defaultValue={State[0]}
                      />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">City</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <CommonSelect
                        options={City}
                        className="select"
                        defaultValue={City[0]}
                      />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-6">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-4">
                      <label className="form-label mb-0">Pincode</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-8">
                      <input type="text" className="form-control" />
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
              </div>
              {/* end row */}
              {/* start row */}
              <div className="row border-bottom mb-3">
                <div className="mb-3">
                  <h5 className="fw-bold mb-0">Change Password</h5>
                </div>
                <div className="col-lg-4">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-6">
                      <label className="form-label mb-0">
                        Current Password
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-6">
                      <div className="pass-group input-group">
                        {/* <span className="isax toggle-password isax-eye-slash" /> */}
                        <input
                          type="password"
                          className="pass-input form-control rounded"
                        />
                      </div>
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-4">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-6">
                      <label className="form-label mb-0">New Password</label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-6">
                      <div className="pass-group input-group">
                        {/* <span className="isax toggle-passwords isax-eye-slash" /> */}
                        <input
                          type="password"
                          className="pass-inputs form-control rounded"
                        />
                      </div>
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
                <div className="col-lg-4">
                  {/* start row */}
                  <div className="row align-items-center mb-3">
                    <div className="col-lg-6">
                      <label className="form-label mb-0">
                        Confirm Password
                      </label>
                    </div>
                    {/* end col */}
                    <div className="col-lg-6">
                      <div className="pass-group input-group">
                        {/* <span className="isax toggle-passworda isax-eye-slash" /> */}
                        <input
                          type="password"
                          className="pass-inputa form-control rounded"
                        />
                      </div>
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                </div>
                {/* end col */}
              </div>
              {/* end row */}
              <div className="d-flex align-items-center justify-content-end">
                <Link href="#" className="btn btn-light me-3">
                  Cancel
                </Link>
                <Link href="#" className="btn btn-primary">
                  Save Changes
                </Link>
              </div>
            </div>
            {/* end card body */}
          </div>
          {/* end card */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default ProfileComponent;

// vue/template/src/views/pages/pages/profile.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content" id="profilePage">
      <!-- Page Header -->
      <div class="mb-3 border-bottom pb-3">
        <h4 class="fw-bold mb-0">Profile</h4>
      </div>
      <!-- End Page Header -->

      <div class="card">
        <div class="card-body">
          <!-- start row -->
          <div class="row border-bottom mb-3">
            <div class="col-lg-12">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-2">
                  <label class="form-label mb-0"
                    >Profile Image<span class="text-danger ms-1">*</span></label
                  >
                </div>
                <!-- end col -->
                <div class="col-lg-10">
                  <div class="profile-container">
                    <img src="@/assets/img/users/user-08.jpg" alt="Profile" />
                    <div class="overlay-btn">
                      <a href="javascript:void(0);" class="text-white" id="uploadTrigger">
                        <i class="ti ti-photo fs-10"></i>
                      </a>
                    </div>
                    <input type="file" id="profileUpload" style="display: none" />
                  </div>
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0"
                    >First Name<span class="text-danger ms-1">*</span></label
                  >
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0"
                    >Last Name<span class="text-danger ms-1">*</span></label
                  >
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0"
                    >Email<span class="text-danger ms-1">*</span></label
                  >
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0"
                    >Phone Number<span class="text-danger ms-1">*</span></label
                  >
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
          </div>
          <!-- end row -->

          <!-- start row -->
          <div class="row border-bottom mb-3">
            <div class="mb-3">
              <h5 class="fw-bold mb-0">Address Information</h5>
            </div>
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">Address Line 1</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">Address Line 2</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">Country</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <vue3-select
                    v-model="selected"
                    :options="CountPro"
                    placeholder="Select"
                  />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">State</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <vue3-select
                    v-model="selectedOne"
                    :options="StatPro"
                    placeholder="Select"
                  />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">City</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <vue3-select
                    v-model="selectedTwo"
                    :options="CityPro"
                    placeholder="Select"
                  />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-6">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-4">
                  <label class="form-label mb-0">Pincode</label>
                </div>
                <!-- end col -->
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
          </div>
          <!-- end row -->

          <!-- start row -->
          <div class="row border-bottom mb-3">
            <div class="mb-3">
              <h5 class="fw-bold mb-0">Change Password</h5>
            </div>
            <div class="col-lg-4">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-6">
                  <label class="form-label mb-0">Current Password</label>
                </div>
                <!-- end col -->
                <div class="col-lg-6">
                  <div class="pass-group input-group">
                    <span class="isax toggle-password isax-eye-slash"></span>
                    <input type="password" class="pass-input form-control rounded" />
                  </div>
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-6">
                  <label class="form-label mb-0">New Password</label>
                </div>
                <!-- end col -->
                <div class="col-lg-6">
                  <div class="pass-group input-group">
                    <span class="isax toggle-passwords isax-eye-slash"></span>
                    <input type="password" class="pass-inputs form-control rounded" />
                  </div>
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <!-- start row -->
              <div class="row align-items-center mb-3">
                <div class="col-lg-6">
                  <label class="form-label mb-0">Confirm Password</label>
                </div>
                <!-- end col -->
                <div class="col-lg-6">
                  <div class="pass-group input-group">
                    <span class="isax toggle-passworda isax-eye-slash"></span>
                    <input type="password" class="pass-inputa form-control rounded" />
                  </div>
                </div>
                <!-- end col -->
              </div>
              <!-- end row -->
            </div>
            <!-- end col -->
          </div>
          <!-- end row -->

          <div class="d-flex align-items-center justify-content-end">
            <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
          </div>
        </div>
        <!-- end card body -->
      </div>
      <!-- end card -->
    </div>
    <!-- End Content -->

    <!-- Footer Start -->
    <div class="footer text-center bg-white p-2 border-top">
      <p class="text-dark mb-0">
        2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All
        Rights Reserved
      </p>
    </div>
    <!-- Footer End -->
  </div>
</template>
<script>
export default {
  data() {
    return {
      selected: null,
      selectedOne: null,
      selectedTwo: null,
      CityPro: [
        { label: "Select", value: "Select" },
        { label: "Los Angeles", value: "Los Angeles" },
        { label: "Toronto", value: "Toronto" },
        { label: "London", value: "London" },
        { label: "Munich", value: "Munich" },
      ],
      StatPro: [
        { label: "Select", value: "Select" },
        { label: "California", value: "California" },
        { label: "Onatario", value: "Onatario" },
        { label: "England", value: "England" },
        { label: "Bavaria", value: "Bavaria" },
      ],
      CountPro: [
        { label: "Select", value: "Select" },
        { label: "USA", value: "USA" },
        { label: "Canada", value: "Canada" },
        { label: "UK", value: "UK" },
        { label: "Germany", value: "Germany" },
      ],
    };
  },
};
</script>
