// nextjs/template/src/components/pages/support/contactMessages.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import ImageWithBasePath from "@/core/imageWithBasePath";
import { ContactMessagesData } from "@/core/json/contactMessagesData";
import Datatable from "@/core/common/dataTable";
import FilterIndex from "@/core/common/filter/filterIndex";
import SearchInput from "@/core/common/dataTable/dataTableSearch";

const ContactMessagesComponent = () => {
  const data = ContactMessagesData;
  const columns = [
    {
      title: "Name",
      dataIndex: "Name",
      render: (text: any, record: any) => (
        <div className="d-flex align-items-center">
          <Link href="#" className="avatar avatar-sm me-2">
            <ImageWithBasePath
              src={`assets/img/users/${record.Image}`}
              alt="product"
              className="rounded-circle"
            />
          </Link>
          <Link href="#" className="fw-medium">
            {text}
          </Link>
        </div>
      ),
      sorter: (a: any, b: any) => a.Name.length - b.Name.length,
    },
    {
      title: "Phone",
      dataIndex: "Phone",
      sorter: (a: any, b: any) => a.Phone.length - b.Phone.length,
    },
    {
      title: "Message",
      dataIndex: "Message",
      sorter: (a: any, b: any) => a.Message.length - b.Message.length,
    },
    {
      title: "Created On",
      dataIndex: "CreatedOn",
      sorter: (a: any, b: any) => a.CreatedOn.length - b.CreatedOn.length,
    },
    {
      title: "",
      render: () => (
        <div className="action-item">
          <Link
            href="#"
            data-bs-toggle="dropdown"
            className="btn p-1 btn-white border"
          >
            <i className="ti ti-dots-vertical" />
          </Link>
          <ul className="dropdown-menu p-2">
            <li>
              <Link
                href="#"
                className="dropdown-item d-flex align-items-center"
                data-bs-toggle="modal"
                data-bs-target="#edit_contact"
              >
                Edit
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="dropdown-item d-flex align-items-center"
                data-bs-toggle="modal"
                data-bs-target="#delete_contact"
              >
                Delete
              </Link>
            </li>
          </ul>
        </div>
      ),
    },
  ];
  const [searchText, setSearchText] = useState<string>("");

  const handleSearch = (value: string) => {
    setSearchText(value);
  };
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Page Header */}
          <div className="d-flex align-items-center pb-3 mb-3 border-bottom">
            <div className="d-flex align-items-center">
              <h4 className="fw-bold mb-0 me-2">Contact Message</h4>
              <span className="badge badge-soft-primary border pt-1 px-2 border-primary fw-medium">
                Total Contact Message : 565
              </span>
            </div>
          </div>
          {/* End Page Header */}
          <div className=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
            <div className="search-set mb-3">
              <div className="d-flex align-items-center flex-wrap gap-2">
                <div className="table-search d-flex align-items-center mb-0">
                  <div className="search-input">
                    <SearchInput value={searchText} onChange={handleSearch} />
                  </div>
                </div>
              </div>
            </div>
            <div className="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
              <div className="dropdown me-2">
                <Link
                  href="#"
                  className="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                >
                  <i className="ti ti-filter me-2 fs-14" />
                  Filter
                </Link>
                <div
                  className="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown"
                  id="filter-dropdown"
                >
                  <div className="d-flex align-items-center justify-content-between border-bottom filter-header">
                    <h4 className="fs-18 fw-bold">Filter</h4>
                    <div className="d-flex align-items-center">
                      <Link
                        href="#"
                        className="link-danger text-decoration-underline me-3"
                      >
                        Clear All
                      </Link>
                    </div>
                  </div>
                  <FilterIndex />
                </div>
              </div>
              <div className="dropdown">
                <Link
                  href="#"
                  className="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                  data-bs-toggle="dropdown"
                >
                  <span className="me-1"> Sort By : </span> Recent
                </Link>
                <ul className="dropdown-menu dropdown-menu-end p-2">
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Recent
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Oldest
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className="table-responsive">
            <Datatable
              columns={columns}
              dataSource={data}
              Selection={false}
              searchText={searchText}
            />
          </div>
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}

<>
  {/* Start Edit Contact */}
  <div id="edit_contact" className="modal fade">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="text-dark modal-title">Edit New Country</h5>
          <button
            type="button"
            className="btn-close btn-close-modal custom-btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <form>
          <div className="modal-body">
            {/* start row */}
            <div className="row">
              <div className="col-lg-12">
                <div className="mb-2">
                  <label className="form-label">
                    Name<span className="text-danger ms-1">*</span>
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    defaultValue="John Carter"
                  />
                </div>
              </div>
              {/* end col */}
              <div className="col-lg-6">
                <div className="mb-2">
                  <label className="form-label">
                    Email Address<span className="text-danger ms-1">*</span>
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    defaultValue="john@example.com"
                  />
                </div>
              </div>
              {/* end col */}
              <div className="col-lg-6">
                <div className="mb-2">
                  <label className="form-label">
                    Phone Number<span className="text-danger ms-1">*</span>
                  </label>
                  <input type="text" className="form-control" id="phone" />
                </div>
              </div>
              {/* end col */}
              <div className="col-lg-12">
                <div className="mb-2">
                  <label className="form-label">Message</label>
                  <textarea
                    className="form-control"
                    rows={3}
                    defaultValue={
                      "Unable to log into my account. Can you assist?"
                    }
                  />
                </div>
              </div>
              {/* end col */}
            </div>
            {/* end row */}
          </div>
          <div className="modal-footer d-flex align-items-center gap-1">
            <button
              type="button"
              className="btn btn-white border"
              data-bs-dismiss="modal"
            >
              Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* End Edit Contact */}
  {/* Start Delete Modal  */}
  <div className="modal fade" id="delete_contact">
    <div className="modal-dialog modal-dialog-centered modal-sm">
      <div className="modal-content">
        <div className="modal-body text-center position-relative">
          <img
            src="assets/img/bg/delete-modal-bg-01.png"
            alt=""
            className="img-fluid position-absolute top-0 start-0"
          />
          <img
            src="assets/img/bg/delete-modal-bg-02.png"
            alt=""
            className="img-fluid position-absolute bottom-0 end-0"
          />
          <div className="mb-3">
            <span className="avatar avatar-lg bg-danger text-white">
              <i className="ti ti-trash fs-24" />
            </span>
          </div>
          <h5 className="fw-bold mb-1">Delete Confirmation</h5>
          <p className="mb-3">Are you sure want to delete?</p>
          <div className="d-flex justify-content-center">
            <a
              href="javascript:void(0);"
              className="btn btn-light position-relative z-1 me-3"
              data-bs-dismiss="modal"
            >
              Cancel
            </a>
            <a
              href="javascript:void(0);"
              className="btn btn-danger position-relative z-1"
              data-bs-dismiss="modal"
            >
              Yes, Delete
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* End Delete Modal  */}
</>

    </>
  );
};

export default ContactMessagesComponent;

// angular/template/src/app/features/support/contact-messages/contact-messages.component.ts
  import { CommonModule } from '@angular/common';
  import { Component } from '@angular/core';
import { MatSortModule, Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { PaginationService, tablePageSize } from '../../../../../src/app/shared/custom-pagination/pagination.service';
import { DataService } from '../../../../../src/app/shared/data/data.service';
import { apiResultFormat, pageSelection, contactmessages } from '../../../../../src/app/shared/models/models';
import { routes } from '../../../../../src/app/shared/routes/routes';
import { MatSelectModule } from '@angular/material/select';
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
import { FormsModule } from '@angular/forms';
import { MultiSelectModule } from 'primeng/multiselect';
import { TagInputModule } from 'ngx-chips';
import { NgxEditorModule } from 'ngx-editor';
import { CustomPaginationComponent } from '../../../shared/custom-pagination/custom-pagination.component';

@Component({
  selector: 'app-contact-messages',
  templateUrl: './contact-messages.component.html',
  styleUrls: ['./contact-messages.component.scss'],
  imports:[CommonModule,MatSelectModule,BsDatepickerModule,MatSortModule,FormsModule,MultiSelectModule,TagInputModule,NgxEditorModule,CustomPaginationComponent]
})
export class ContactMessagesComponent {
routes=routes
  tags=['Received', 'Pending'];
  tags1=['PayPal', 'Cheque'];
    bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();
public pageSize = 10;
public tableData: contactmessages[] = [];
public tableDataCopy: contactmessages[] = [];
public actualData: contactmessages[] = [];
public currentPage = 1;
public skip = 0;
public limit: number = this.pageSize;
public serialNumberArray: number[] = [];
public totalData = 0;
public pageSelection: pageSelection[] = [];
dataSource!: MatTableDataSource<contactmessages>;
public searchDataValue = '';
public row=true;
constructor(
  private data: DataService,
  private router: Router,
  private pagination: PaginationService
) {
      this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];

  this.data.getContactmessages().subscribe((apiRes: apiResultFormat) => {
    this.actualData = apiRes.data;
    this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
      if (this.router.url == this.routes.contactMessages) {
        this.getTableData({ skip: res.skip, limit: res.limit });
        this.pageSize = res.pageSize;
      }
    });
  });
}
private getTableData(pageOption: pageSelection): void {
  this.data.getContactmessages().subscribe((apiRes: apiResultFormat) => {
    this.tableData = [];
    this.tableDataCopy = [];
    this.serialNumberArray = [];
    this.totalData = apiRes.totalData;
    apiRes.data.map((res: contactmessages, index: number) => {
      const serialNumber = index + 1;
      if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
        res.sNo = serialNumber;
        this.tableData.push(res);
        this.tableDataCopy.push(res);
        this.serialNumberArray.push(serialNumber);
      }
    });
    this.dataSource = new MatTableDataSource<contactmessages>(this.actualData);
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  });
}

public searchData(value: string): void {
  this.searchDataValue = value.trim().toLowerCase();
  this.dataSource.filter = this.searchDataValue;
  this.tableData = this.dataSource.filteredData;
  this.row = this.tableData.length > 0;

  if (this.searchDataValue !== '') {
    // Handle filtered data
    this.pagination.calculatePageSize.next({
      totalData: this.tableData.length,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.tableData.map((_, i) => i + 1), // Generates serials like [1, 2, 3...]
    });
  } else {
    // Handle reset to full data
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  }
}

public sortData(sort: Sort) {
  const data = this.tableData.slice();

  if (!sort.active || sort.direction === '') {
    this.tableData = data;
  } else {
    this.tableData = data.sort((a, b) => {
      const aValue = (a as never)[sort.active];

      const bValue = (b as never)[sort.active];
      return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
    });
  }
}
public changePageSize(pageSize: number): void {
  this.pageSelection = [];
  this.limit = pageSize;
  this.skip = 0;
  this.currentPage = 1;
  this.pagination.tablePageSize.next({
    skip: this.skip,
    limit: this.limit,
    pageSize: this.pageSize,
  });
}
}

<!-- Start Content -->
<div class="content">

    <!-- Page Header -->
    <div class="d-flex align-items-center pb-3 mb-3 border-bottom">
        <div class="d-flex align-items-center">
            <h4 class="fw-bold mb-0 me-2">Contact Message</h4>
            <span class="badge badge-soft-primary border pt-1 px-2 border-primary fw-medium">Total Contact Message :
                565</span>
        </div>
    </div>
    <!-- End Page Header -->


    <div class=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
        <div class="search-set mb-3">
            <div class="d-flex align-items-center">
                <div class="table-search d-flex align-items-center mb-0 me-2">
                    <div class="search-input">
                        <a href="javascript:void(0);" class="btn-searchset"><i
                                class="isax isax-search-normal fs-12"></i></a>
                        <div id="DataTables_Table_0_filter" class="dataTables_filter">
                            <label>
                                <input type="search" [(ngModel)]="searchDataValue"
                                    [ngModelOptions]="{ standalone: true }" type="search"
                                    (ngModelChange)="searchData(searchDataValue)" class="form-control form-control-sm"
                                    placeholder="Search" aria-controls="DataTables_Table_0">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
            <div class="dropdown me-2">
                <a href="javascript:void(0);"
                    class="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                    data-bs-toggle="dropdown" data-bs-auto-close="outside">
                    <i class="ti ti-filter me-2 fs-14"></i>Filter
                </a>
                <div class="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown" id="filter-dropdown">
                    <div class="d-flex align-items-center justify-content-between border-bottom filter-header">
                        <h4 class="fs-18 fw-bold">Filter</h4>
                        <div class="d-flex align-items-center">
                            <a href="javascript:void(0);" class="link-danger text-decoration-underline me-3">Clear
                                All</a>
                        </div>
                    </div>
                    <form >
                        <div class="filter-body pb-1">
                            <div class="mb-3">
                                <label class="form-label">Name</label>
                                <div class="dropdown">
                                    <a href="javascript:void(0);"
                                        class="dropdown-toggle btn bg-white  d-flex align-items-center justify-content-start fs-13 p-2 fw-normal border"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="true">
                                        Select
                                    </a>
                                    <div class="dropdown-menu shadow-lg w-100 dropdown-info p-3">
                                        <div class="mb-3">
                                            <div class="input-icon-start position-relative">
                                                <span class="input-icon-addon fs-12">
                                                    <i class="isax isax-search-normal"></i>
                                                </span>
                                                <input type="text" class="form-control form-control-sm"
                                                    placeholder="Search">
                                            </div>
                                        </div>
                                        <ul class="mb-3">
                                            <li class="d-flex align-items-center justify-content-between mb-3">
                                                <label class="d-inline-flex align-items-center text-gray-9">
                                                    <input class="form-check-input select-all m-0 me-2" type="checkbox">
                                                    Select All
                                                </label>
                                                <a href="javascript:void(0);"
                                                    class="link-danger fw-medium text-decoration-underline">Reset</a>
                                            </li>
                                            <li>
                                                <label class="dropdown-item px-2 d-flex align-items-center text-dark">
                                                    <input class="form-check-input m-0 me-2" type="checkbox">
                                                    <span class="avatar avatar-sm rounded-circle me-2"><img
                                                            src="assets/img/users/user-33.jpg"
                                                            class="flex-shrink-0 rounded-circle"
                                                            alt="img"></span>Alberto Ripley
                                                </label>
                                            </li>
                                            <li>
                                                <label class="dropdown-item px-2 d-flex align-items-center text-dark">
                                                    <input class="form-check-input m-0 me-2" type="checkbox">
                                                    <span class="avatar avatar-sm rounded-circle me-2"><img
                                                            src="assets/img/users/user-12.jpg"
                                                            class="flex-shrink-0 rounded-circle"
                                                            alt="img"></span>Bernard Griffith
                                                </label>
                                            </li>
                                            <li>
                                                <label class="dropdown-item px-2 d-flex align-items-center text-dark">
                                                    <input class="form-check-input m-0 me-2" type="checkbox">
                                                    <span class="avatar avatar-sm rounded-circle me-2"><img
                                                            src="assets/img/users/user-02.jpg"
                                                            class="flex-shrink-0 rounded-circle" alt="img"></span>Carol
                                                    Lam
                                                </label>
                                            </li>
                                            <li>
                                                <label class="dropdown-item px-2 d-flex align-items-center text-dark">
                                                    <input class="form-check-input m-0 me-2" type="checkbox">
                                                    <span class="avatar avatar-sm rounded-circle me-2"><img
                                                            src="assets/img/users/user-08.jpg"
                                                            class="flex-shrink-0 rounded-circle" alt="img"></span>Ezra
                                                    Belcher
                                                </label>
                                            </li>
                                        </ul>
                                        <div class="row g-2">
                                            <div class="col-6">
                                                <a href="javascript:void(0);"
                                                    class="btn btn-outline-white w-100 close-filter">Cancel</a>
                                            </div>
                                            <div class="col-6">
                                                <a href="javascript:void(0);" class="btn btn-primary w-100">Select</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center justify-content-between">
                                    <label class="form-label">Date</label>
                                </div>
                                <div class="input-group position-relative">
                                    <input type="text"
                                        class="form-control date-range bookingrange rounded-end h-auto py-2 bg-white" bsDatepicker>
                                    <span class="input-icon-addon fs-16 text-gray-9">
                                        <i class="ti ti-calendar"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="filter-footer d-flex align-items-center justify-content-end border-top">
                            <a href="javascript:void(0);" class="btn btn-light btn-md me-2" id="close-filter">Close</a>
                            <button type="submit" class="btn btn-primary btn-md">Filter</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="dropdown">
                <a href="javascript:void(0);"
                    class="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                    data-bs-toggle="dropdown">
                    <span class="me-1"> Sort By : </span> Recent
                </a>
                <ul class="dropdown-menu dropdown-menu-end p-2">
                    <li>
                        <a href="javascript:void(0);" class="dropdown-item rounded-1">Recent</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="dropdown-item rounded-1">Oldest</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table matSort (matSortChange)="sortData($event)" class="table table-nowrap dataTable datatable">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Created On</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (data of tableData;track data){
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <a href="javascript:void(0);" class="avatar avatar-sm me-2">
                                <img src="assets/img/users/{{data.Image}}" alt="product" class="rounded-circle">
                            </a>
                            <a href="javascript:void(0);" class="fw-medium">{{data.Name}}</a>
                        </div>
                    </td>
                    <td>{{data.Phone}}</td>
                    <td>{{data.Email}}</td>
                    <td>
                        <p class="truncate-text">{{data.Message}}</p>
                    </td>
                    <td>{{data.CreatedOn}}</td>
                    <td class="action-item">
                        <a href="javascript:void(0);" data-bs-toggle="dropdown" class="btn p-1 btn-white border">
                            <i class="ti ti-dots-vertical"></i>
                        </a>
                        <ul class="dropdown-menu p-2">
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal" data-bs-target="#edit_contact">Edit</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center"
                                    data-bs-toggle="modal" data-bs-target="#delete_contact">Delete</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            }@if(tableData.length==0){
                <tr>
                    <td colspan="5" class="text-center">No data found</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <app-custom-pagination *ngIf="row"></app-custom-pagination>
</div>
<!-- End Content -->

<!-- Start Edit Contact -->
    <div id="edit_contact" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="text-dark modal-title">Edit New Country</h5>
                    <button type="button" class="btn-close btn-close-modal custom-btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-x"></i></button>
                </div>
                <form >
                    <div class="modal-body">
                        <!-- start row -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="mb-2">
                                    <label class="form-label">Name<span class="text-danger ms-1">*</span></label>
                                    <input type="text" class="form-control" value="John Carter">
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-6">
                                <div class="mb-2">
                                    <label class="form-label">Email Address<span class="text-danger ms-1">*</span></label>
                                    <input type="text" class="form-control" value="john@example.com">
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-6">
                                <div class="mb-2">
                                    <label class="form-label">Phone Number<span class="text-danger ms-1">*</span></label>
                                    <input type="text" class="form-control" id="phone">
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-12">
                                <div class="mb-2">
                                    <label class="form-label">Message</label>
                                    <textarea class="form-control" rows="3">Unable to log into my account. Can you assist?</textarea>
                                </div>
                            </div><!-- end col -->
                        </div>
                        <!-- end row -->
                    </div>
                    <div class="modal-footer d-flex align-items-center gap-1">
                        <button type="button" class="btn btn-white border" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- End Edit Contact -->

    <!-- Start Delete Modal  -->
    <div class="modal fade" id="delete_contact">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-body text-center position-relative">
                    <img src="assets/img/bg/delete-modal-bg-01.png" alt="" class="img-fluid position-absolute top-0 start-0">
                    <img src="assets/img/bg/delete-modal-bg-02.png" alt="" class="img-fluid position-absolute bottom-0 end-0">
                    <div class="mb-3">
                        <span class="avatar avatar-lg bg-danger text-white"><i class="ti ti-trash fs-24"></i></span>
                    </div>
                    <h5 class="fw-bold mb-1">Delete Confirmation</h5>
                    <p class="mb-3">Are you sure want to delete?</p>
                    <div class="d-flex justify-content-center">
                        <a href="javascript:void(0);" class="btn btn-light position-relative z-1 me-3" data-bs-dismiss="modal">Cancel</a>
                        <a href="javascript:void(0);" class="btn btn-danger position-relative z-1">Yes, Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Delete Modal  -->
