// angular/template/src/app/features/administration/reports/appointment-report/appointment-report.component.ts
import { Component, ViewChild } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { PaginationService, tablePageSize } from '../../../../../../src/app/shared/custom-pagination/pagination.service';
import { DataService } from '../../../../../../src/app/shared/data/data.service';
import { apiResultFormat, pageSelection, reports } from '../../../../../../src/app/shared/models/models';
import { routes } from '../../../../../../src/app/shared/routes/routes';
import {
  ApexAxisChartSeries,
  ApexChart,
  ChartComponent,
  ApexDataLabels,
  ApexPlotOptions,
  ApexYAxis,
  ApexLegend,
  ApexStroke,
  ApexXAxis,
  ApexFill,
  ApexTooltip,
  ApexTitleSubtitle,
  ApexGrid,
  ApexResponsive,
  NgApexchartsModule,
} from 'ng-apexcharts';
import { CommonModule } from '@angular/common';
import { MatSelectModule } from '@angular/material/select';
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
import { MatSortModule } from '@angular/material/sort';
import { FormsModule } from '@angular/forms';
import { MultiSelectModule } from 'primeng/multiselect';
import { TagInputModule } from 'ngx-chips';

export type ChartOptions = {
  series: ApexAxisChartSeries | any;
  chart: ApexChart | any;
  dataLabels: ApexDataLabels | any;
  plotOptions: ApexPlotOptions | any;
  yaxis: ApexYAxis | any;
  xaxis: ApexXAxis | any;
  fill: ApexFill | any;
  tooltip: ApexTooltip | any;
  stroke: ApexStroke | any;
  legend: ApexLegend | any;
  title: ApexTitleSubtitle | any;
  colors: string[] | any;
  subtitle: ApexTitleSubtitle | any;
  grid: ApexGrid | any;
  responsive:ApexResponsive | any;
  labels:ApexDataLabels | any;

};
@Component({
  selector: 'app-appointment-report',
  templateUrl: './appointment-report.component.html',
  styleUrls: ['./appointment-report.component.scss'],
  imports:[CommonModule,MatSelectModule,BsDatepickerModule,MatSortModule,FormsModule,MultiSelectModule,TagInputModule,NgApexchartsModule]
})
export class AppointmentReportComponent {
routes=routes
  tags=['Received', 'Pending'];
    bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();
  @ViewChild('chart') chart!: ChartComponent;
public barChart: Partial<ChartOptions>;
public barChart1: Partial<ChartOptions>;
public barChart2: Partial<ChartOptions>;
public barChart3: Partial<ChartOptions>;

public pageSize = 10;
public tableData: reports[] = [];
public tableDataCopy: reports[] = [];
public actualData: reports[] = [];
public currentPage = 1;
public skip = 0;
public limit: number = this.pageSize;
public serialNumberArray: number[] = [];
public totalData = 0;
public pageSelection: pageSelection[] = [];
dataSource!: MatTableDataSource<reports>;
public searchDataValue = '';
public row=true;
constructor(
  private data: DataService,
  private router: Router,
  private pagination: PaginationService
) {
     this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];
  this.data.getAppointmentReport().subscribe((apiRes: apiResultFormat) => {
    this.actualData = apiRes.data;
    this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
      if (this.router.url == this.routes.appointmentReport) {
        this.getTableData({ skip: res.skip, limit: res.limit });
        this.pageSize = res.pageSize;
      }
    });
  });
  this.barChart={
    chart: {
      width: 56,
      height: 40,
      type: 'bar',
      toolbar: { show: false },
      sparkline: { enabled: true }
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '70%',
        borderRadius: 0,
        endingShape: 'rounded'
      }
    },
    dataLabels: { enabled: false },
    stroke: { show: false },
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'light',
        type: "vertical",
        colorStops: [
          {
            offset: 0,
            color: "#ffffff",
            opacity: 1
          },
          {
            offset: 100,
            color: "#2E37A4",
            opacity: 1
          }
        ]
      }
    },
    series: [{
      name: 'Data',
      data: [40, 50, 100, 100, 70]
    }],
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false }
    },
    yaxis: { show: false },
    grid: { show: false },
    tooltip: { enabled: false }
  };
  this.barChart1= {
    chart: {
      width: 56,
      height: 40,
      type: 'bar',
      toolbar: { show: false },
      sparkline: { enabled: true }
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '70%',
        borderRadius: 0,
        endingShape: 'rounded'
      }
    },
    dataLabels: { enabled: false },
    stroke: { show: false },
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'light',
        type: "vertical",
        colorStops: [
          {
            offset: 0,
            color: "#ffffff",
            opacity: 1
          },
          {
            offset: 100,
            color: "#27AE60",
            opacity: 1
          }
        ]
      }
    },
    series: [{
      name: 'Data',
      data: [40, 50, 100, 100, 70]
    }],
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false }
    },
    yaxis: { show: false },
    grid: { show: false },
    tooltip: { enabled: false }
  };
  this.barChart2={
    chart: {
      width: 56,
      height: 40,
      type: 'bar',
      toolbar: { show: false },
      sparkline: { enabled: true }
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '70%',
        borderRadius: 0,
        endingShape: 'rounded'
      }
    },
    dataLabels: { enabled: false },
    stroke: { show: false },
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'light',
        type: "vertical",
        colorStops: [
          {
            offset: 0,
            color: "#ffffff",
            opacity: 1
          },
          {
            offset: 100,
            color: "#E2B93B",
            opacity: 1
          }
        ]
      }
    },
    series: [{
      name: 'Data',
      data: [40, 50, 100, 100, 70]
    }],
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false }
    },
    yaxis: { show: false },
    grid: { show: false },
    tooltip: { enabled: false }
  };
  this.barChart3= {
    chart: {
      width: 56,
      height: 40,
      type: 'bar',
      toolbar: { show: false },
      sparkline: { enabled: true }
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '70%',
        borderRadius: 0,
        endingShape: 'rounded'
      }
    },
    dataLabels: { enabled: false },
    stroke: { show: false },
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'light',
        type: "vertical",
        colorStops: [
          {
            offset: 0,
            color: "#ffffff",
            opacity: 1
          },
          {
            offset: 100,
            color: "#EF1E1E",
            opacity: 1
          }
        ]
      }
    },
    series: [{
      name: 'Data',
      data: [40, 50, 100, 100, 70]
    }],
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false }
    },
    yaxis: { show: false },
    grid: { show: false },
    tooltip: { enabled: false }
  };
}
private getTableData(pageOption: pageSelection): void {
  this.data.getAppointmentReport().subscribe((apiRes: apiResultFormat) => {
    this.tableData = [];
    this.tableDataCopy = [];
    this.serialNumberArray = [];
    this.totalData = apiRes.totalData;
    apiRes.data.map((res: reports, index: number) => {
      const serialNumber = index + 1;
      if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
        res.sNo = serialNumber;
        this.tableData.push(res);
        this.tableDataCopy.push(res);
        this.serialNumberArray.push(serialNumber);
      }
    });
    this.dataSource = new MatTableDataSource<reports>(this.actualData);
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  });
}

public searchData(value: string): void {
  this.searchDataValue = value.trim().toLowerCase();
  this.dataSource.filter = this.searchDataValue;
  this.tableData = this.dataSource.filteredData;
  this.row = this.tableData.length > 0;

  if (this.searchDataValue !== '') {
    // Handle filtered data
    this.pagination.calculatePageSize.next({
      totalData: this.tableData.length,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.tableData.map((_, i) => i + 1), // Generates serials like [1, 2, 3...]
    });
  } else {
    // Handle reset to full data
    this.pagination.calculatePageSize.next({
      totalData: this.totalData,
      pageSize: this.pageSize,
      tableData: this.tableData,
      serialNumberArray: this.serialNumberArray,
    });
  }
}

public sortData(sort: Sort) {
  const data = this.tableData.slice();

  if (!sort.active || sort.direction === '') {
    this.tableData = data;
  } else {
    this.tableData = data.sort((a, b) => {
      const aValue = (a as never)[sort.active];

      const bValue = (b as never)[sort.active];
      return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
    });
  }
}
public changePageSize(pageSize: number): void {
  this.pageSelection = [];
  this.limit = pageSize;
  this.skip = 0;
  this.currentPage = 1;
  this.pagination.tablePageSize.next({
    skip: this.skip,
    limit: this.limit,
    pageSize: this.pageSize,
  });
}
}

            <!-- Start Content -->
            <div class="content">

                <!-- Start Page Header -->
                <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 mb-3 pb-3 border-bottom">
                    <div class="flex-grow-1">
                        <h4 class="fw-bold mb-0">Appointment Report</h4>
                    </div>
                    <div class="text-end d-flex">
                        <!-- dropdown-->
                        <div class="dropdown me-1">
							<a href="javascript:void(0);" class="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"  data-bs-toggle="dropdown">
								Export<i class="ti ti-chevron-down ms-2"></i>
							</a>
							<ul class="dropdown-menu p-2">
								<li>
									<a class="dropdown-item" href="javascript:void(0);">Download as PDF</a>
								</li>
								<li>
									<a class="dropdown-item" href="javascript:void(0);">Download as Excel</a>
								</li>
							</ul>
						</div>
                    </div>
				</div>
				<!-- End Page Header -->

                <!-- row start -->
                <div class="row">

                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">                       
                        <div class="card shadow-sm flex-fill w-100 z-0">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="avatar avatar-sm bg-soft-primary border border-primary text-primary rounded-2 flex-shrink-0"><i class="ti ti-calendar-time fs-14"></i></span>
                                    <span class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2">+10%<i class="ti ti-arrow-up-right ms-1"></i></span>
                                </div>  
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <p class="mb-1 text-truncate">Total Appointments</p>
                                        <h6 class="mb-0 fw-bold">850</h6>
                                    </div>
                                    <div id="s-col-11" class="chart-set no-tooltips">
                                        <apx-chart [series]="barChart.series" 
                       [chart]="barChart.chart"
                       [dataLabels]="barChart.dataLabels"
                       [plotOptions]="barChart.plotOptions"
                       [yaxis]="barChart.yaxis" 
                       [legend]="barChart.legend" 
                       [fill]="barChart.fill"
                       [stroke]="barChart.stroke" 
                       [xaxis]="barChart.xaxis"
                       [colors]="barChart.colors"
                       [fill]="barChart.fill"
                       [tooltip]="barChart.tooltip"></apx-chart>
                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                    <!-- col end -->

                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">                       
                        <div class="card shadow-sm flex-fill w-100 z-0">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="avatar avatar-sm bg-soft-success border border-success text-success rounded-2 flex-shrink-0"><i class="ti ti-calendar-up fs-14"></i></span>
                                    <span class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2">+11.5%<i class="ti ti-arrow-up-right ms-1"></i></span>
                                </div>  
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <p class="mb-1 text-truncate">Completed</p>
                                        <h6 class="mb-0 fw-bold">720</h6>
                                    </div>
                                    <div id="s-col-12" class="chart-set no-tooltips">
                                        <apx-chart [series]="barChart1.series" 
                       [chart]="barChart1.chart"
                       [dataLabels]="barChart1.dataLabels"
                       [plotOptions]="barChart1.plotOptions"
                       [yaxis]="barChart1.yaxis" 
                       [legend]="barChart1.legend" 
                       [fill]="barChart1.fill"
                       [stroke]="barChart1.stroke" 
                       [xaxis]="barChart1.xaxis"
                       [colors]="barChart1.colors"
                       [fill]="barChart1.fill"
                       [tooltip]="barChart1.tooltip"></apx-chart>

                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                    <!-- col end -->

                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">                       
                        <div class="card shadow-sm flex-fill w-100 z-0">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="avatar avatar-sm bg-soft-warning border border-warning text-warning rounded-2 flex-shrink-0"><i class="ti ti-calendar-down fs-14"></i></span>
                                    <span class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2">+8.43%<i class="ti ti-arrow-up-right ms-1"></i></span>
                                </div>  
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <p class="mb-1 text-truncate">Cancelled</p>
                                        <h6 class="mb-0 fw-bold">65</h6>
                                    </div>
                                    <div id="s-col-13" class="chart-set no-tooltips">
                                        <apx-chart [series]="barChart2.series" 
                       [chart]="barChart2.chart"
                       [dataLabels]="barChart2.dataLabels"
                       [plotOptions]="barChart2.plotOptions"
                       [yaxis]="barChart2.yaxis" 
                       [legend]="barChart2.legend" 
                       [fill]="barChart2.fill"
                       [stroke]="barChart2.stroke" 
                       [xaxis]="barChart2.xaxis"
                       [colors]="barChart2.colors"
                       [fill]="barChart2.fill"
                       [tooltip]="barChart2.tooltip"></apx-chart>

                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                    <!-- col end -->

                    <!-- col start -->
                    <div class="col-xl-3 col-md-6 d-flex">                       
                        <div class="card shadow-sm flex-fill w-100 z-0">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="avatar avatar-sm bg-soft-danger border border-danger text-danger rounded-2 flex-shrink-0"><i class="ti ti-calendar-repeat fs-14"></i></span>
                                    <span class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2">+6.58%<i class="ti ti-arrow-up-right ms-1"></i></span>
                                </div>  
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <p class="mb-1 text-truncate">Rescheduled</p>
                                        <h6 class="mb-0 fw-bold">40</h6>
                                    </div>
                                    <div id="s-col-14" class="chart-set no-tooltips">
                                        <apx-chart [series]="barChart3.series" 
                       [chart]="barChart3.chart"
                       [dataLabels]="barChart3.dataLabels"
                       [plotOptions]="barChart3.plotOptions"
                       [yaxis]="barChart3.yaxis" 
                       [legend]="barChart3.legend" 
                       [fill]="barChart3.fill"
                       [stroke]="barChart3.stroke" 
                       [xaxis]="barChart3.xaxis"
                       [colors]="barChart3.colors"
                       [fill]="barChart3.fill"
                       [tooltip]="barChart3.tooltip"></apx-chart>

                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                    <!-- col end -->

                </div>
                <!-- row end -->

                 <div class="card">
                    <div class="card-body">

                        <!-- start row -->
                         <div class="row row-gap-2">
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Date</label>
                                    <div class="input-group position-relative">
                                        <input type="text" class="form-control date-range bookingrange rounded-end bg-white" bsDaterangepicker [(ngModel)]="bsRangeValue" name="time" [bsConfig]="{ adaptivePosition: true }" placeholder="20 Apr 25 - 20 Apr 25">
                                        <span class="input-icon-addon fs-14 text-dark">
                                            <i class="ti ti-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Patient</label>
                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="1">Alberto Ripley</mat-option>
                                        <mat-option value="1">Susan Babin</mat-option>
                                        <mat-option value="1">Martin Lisa</mat-option>
                                        <mat-option value="1">Stella Mary</mat-option>
                                        <mat-option value="1">Carol Lam</mat-option>
                                        <mat-option value="1">Jesus Adams</mat-option>
                                        <mat-option value="1">Ezra Belcher</mat-option>
                                    </mat-select>
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Location</label>
                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="1">California</mat-option>
                                        <mat-option value="1">Options Enhanced</mat-option>
                                        <mat-option value="1">New York</mat-option>
                                        <mat-option value="1">Florida</mat-option>
                                        <mat-option value="1">Illinois</mat-option>
                                        <mat-option value="1">Georgia</mat-option>
                                        <mat-option value="1">Washington</mat-option>
                                        <mat-option value="1">Arizona</mat-option>
                                    </mat-select>
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Practioner</label>
                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="1">Dr. Mick Thompson</mat-option>
                                        <mat-option value="1">Dr. Sarah Johnson</mat-option>
                                        <mat-option value="1">Dr. Emily Carter</mat-option>
                                        <mat-option value="1">Dr. David Lee</mat-option>
                                        <mat-option value="1">Dr. Anna Kim</mat-option>
                                        <mat-option value="1">Dr. John Smith</mat-option>
                                        <mat-option value="1">Dr. Lisa White</mat-option>
                                        <mat-option value="1">Dr. Patrica Brown</mat-option>
                                    </mat-select>
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Designation</label>
                                    <mat-select class="custom-mat-select select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="1">Cardiologist</mat-option>
                                        <mat-option value="1">Orthopedic Surgeon</mat-option>
                                        <mat-option value="1">Pediatrician</mat-option>
                                        <mat-option value="1">Gynecologist</mat-option>
                                        <mat-option value="1">Psychiatrist</mat-option>
                                        <mat-option value="1">Neurosurgeon</mat-option>
                                        <mat-option value="1">Oncologist</mat-option>
                                    </mat-select>
                                </div>
                            </div><!-- end col -->
                            <div class="col-lg-4">
                                <div class="mb-0">
                                    <label class="form-label">Status</label>
                                    <tag-input [ngModelOptions]="{standalone: true}" [(ngModel)]="tags" [placeholder]="'Add new'"></tag-input>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-12">
                                <div class="d-flex align-items-center justify-content-end">
                                    <a href="javascript:void(0);" class="btn btn-dark"><i class="ti ti-player-play me-1"></i>Run Report</a>
                                </div>
                            </div><!-- end col -->
                         </div>
                        <!-- end row -->

                    </div><!-- end card body -->
                 </div><!-- end card -->

                <div class="table-responsive">
                    <table matSort (matSortChange)="sortData($event)" class="table table-nowrap dataTable datatable">
                        <thead class="thead-light">
                            <tr>
                                <th>Patient</th>
                                <th>Date & Time</th>
                                <th>Invoice ID</th>
                                <th>Practioner</th>
                                <th>Location</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (data of tableData;track data){
                            <tr>
                                <td>{{data.patient}}</td>
                                <td>{{data.dateTime}}</td>
                                <td>{{data.invoiceID}}</td>
                                <td><p class="text-dark fw-medium">{{data.practioner}}</p></td>
                                <td>{{data.location}}</td>
                                <td>
                                    <span class="badge px-2 py-1 fs-13 fw-medium"
                                    [ngClass]="data.status==='Checked In'?'badge-soft-warning border border-warning ':data.status==='Cancelled'?'badge-soft-danger border border-danger ': data.status==='Checked Out'?'badge-soft-primary border border-primary ':data.status==='Schedule'?'badge-soft-info border border-info ':'badge-soft-success border border-success'">
                                    {{data.status}}
                                    </span>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                                
            </div>
            <!-- End Content -->

// vue/template/src/views/pages/reports/appointment-report.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content">
      <!-- Start Page Header -->
      <div
        class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 mb-3 pb-3 border-bottom"
      >
        <div class="flex-grow-1">
          <h4 class="fw-bold mb-0">Appointment Report</h4>
        </div>
        <div class="text-end d-flex">
          <!-- dropdown-->
          <div class="dropdown me-1">
            <a
              href="javascript:void(0);"
              class="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"
              data-bs-toggle="dropdown"
            >
              Export<i class="ti ti-chevron-down ms-2"></i>
            </a>
            <ul class="dropdown-menu p-2">
              <li>
                <a class="dropdown-item" href="#">Download as PDF</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Download as Excel</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- End Page Header -->

      <!-- row start -->
      <div class="row">
        <!-- col start -->
        <div class="col-xl-3 col-md-6 d-flex">
          <div class="card shadow-sm flex-fill w-100 z-0">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <span
                  class="avatar avatar-sm bg-soft-primary border border-primary text-primary rounded-2 flex-shrink-0"
                  ><i class="ti ti-calendar-time fs-14"></i
                ></span>
                <span
                  class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2"
                  >+10%<i class="ti ti-arrow-up-right ms-1"></i
                ></span>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="mb-1 text-truncate">Total Appointments</p>
                  <h6 class="mb-0 fw-bold">850</h6>
                </div>
                <div id="s-col-11" class="chart-set"></div>
              </div>
            </div>
          </div>
        </div>
        <!-- col end -->

        <!-- col start -->
        <div class="col-xl-3 col-md-6 d-flex">
          <div class="card shadow-sm flex-fill w-100 z-0">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <span
                  class="avatar avatar-sm bg-soft-success border border-success text-success rounded-2 flex-shrink-0"
                  ><i class="ti ti-calendar-up fs-14"></i
                ></span>
                <span
                  class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2"
                  >+11.5%<i class="ti ti-arrow-up-right ms-1"></i
                ></span>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="mb-1 text-truncate">Completed</p>
                  <h6 class="mb-0 fw-bold">720</h6>
                </div>
                <div id="s-col-12" class="chart-set"></div>
              </div>
            </div>
          </div>
        </div>
        <!-- col end -->

        <!-- col start -->
        <div class="col-xl-3 col-md-6 d-flex">
          <div class="card shadow-sm flex-fill w-100 z-0">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <span
                  class="avatar avatar-sm bg-soft-warning border border-warning text-warning rounded-2 flex-shrink-0"
                  ><i class="ti ti-calendar-down fs-14"></i
                ></span>
                <span
                  class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2"
                  >+8.43%<i class="ti ti-arrow-up-right ms-1"></i
                ></span>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="mb-1 text-truncate">Cancelled</p>
                  <h6 class="mb-0 fw-bold">65</h6>
                </div>
                <div id="s-col-13" class="chart-set"></div>
              </div>
            </div>
          </div>
        </div>
        <!-- col end -->

        <!-- col start -->
        <div class="col-xl-3 col-md-6 d-flex">
          <div class="card shadow-sm flex-fill w-100 z-0">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <span
                  class="avatar avatar-sm bg-soft-danger border border-danger text-danger rounded-2 flex-shrink-0"
                  ><i class="ti ti-calendar-repeat fs-14"></i
                ></span>
                <span
                  class="badge fw-medium bg-soft-success text-success flex-shrink-0 ms-2"
                  >+6.58%<i class="ti ti-arrow-up-right ms-1"></i
                ></span>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="mb-1 text-truncate">Rescheduled</p>
                  <h6 class="mb-0 fw-bold">40</h6>
                </div>
                <div id="s-col-14" class="chart-set"></div>
              </div>
            </div>
          </div>
        </div>
        <!-- col end -->
      </div>
      <!-- row end -->

      <div class="card">
        <div class="card-body">
          <!-- start row -->
          <div class="row row-gap-2">
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Date</label>
                <div class="input-group position-relative">
                  <input
                    type="text"
                    class="form-control date-range bookingrange rounded-end bg-white"
                    ref="dateRangeInput"
                  />
                  <span class="input-icon-addon fs-14 text-dark">
                    <i class="ti ti-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Patient</label>
                <vue3-select v-model="selected" :options="PatiApp" placeholder="Select" />
              </div>
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Location</label>
                <vue3-select
                  v-model="selectedOne"
                  :options="LocaApp"
                  placeholder="Select"
                />
              </div>
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Practioner</label>
                <vue3-select
                  v-model="selectedTwo"
                  :options="PracApp"
                  placeholder="Select"
                />
              </div>
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Designation</label>
                <vue3-select
                  v-model="selectedThree"
                  :options="DesiApp"
                  placeholder="Select"
                />
              </div>
            </div>
            <!-- end col -->
            <div class="col-lg-4">
              <div class="mb-0">
                <label class="form-label">Status</label>
                <vue3-tags-input
                  class="input-tags form-control"
                  type="text"
                  data-role="tagsinput"
                  name="specialist"
                  value="Tag1"
                  :tags="tagsOne"
                />
              </div>
            </div>
            <!-- end col -->
            <div class="col-md-12">
              <div class="d-flex align-items-center justify-content-end">
                <a href="javascript:void(0);" class="btn btn-dark"
                  ><i class="ti ti-player-play me-1"></i>Run Report</a
                >
              </div>
            </div>
            <!-- end col -->
          </div>
          <!-- end row -->
        </div>
        <!-- end card body -->
      </div>
      <!-- end card -->

      <div class="table-responsive">
        <a-table
          class="table table-nowrap datatable"
          :columns="columns"
          :data-source="filteredPages"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'Practioner'">
              <div>
                <p class="text-dark fw-medium">{{ record.Practioner }}</p>
              </div>
            </template>
            <template v-if="column.key === 'Status'">
              <span
                class="fw-medium fs-13"
                :class="[
                  'badge',
                  {
                    'badge-soft-success rounded text-success border border-success':
                      record.Status === 'Confirmed',
                    'badge-soft-primary rounded text-primary border border-primary':
                      record.Status === 'Checked Out',
                    'badge-soft-warning rounded text-warning border border-warning':
                      record.Status === 'Checked in',
                    'badge-soft-danger rounded text-danger border border-danger':
                      record.Status === 'Cancelled',
                    'badge-soft-info rounded text-info border border-info':
                      record.Status === 'Schedule',
                  },
                ]"
                >{{ record.Status }}
              </span>
            </template>
          </template>
        </a-table>
      </div>
    </div>
    <!-- End Content -->

    <!-- Footer Start -->
    <div class="footer text-center bg-white p-2 border-top">
      <p class="text-dark mb-0">
        2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All
        Rights Reserved
      </p>
    </div>
    <!-- Footer End -->
  </div>
</template>
<script>
const columns = [
  {
    title: "Patient",
    dataIndex: "Patient",
    key: "Patient",
    sorter: {
      compare: (a, b) => (a.Patient.toLowerCase() > b.Patient.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Date & Time",
    dataIndex: "DateTime",
    key: "DateTime",
    sorter: {
      compare: (a, b) => (a.DateTime.toLowerCase() > b.DateTime.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Invoice ID",
    dataIndex: "InvoiceID",
    key: "InvoiceID",
    sorter: {
      compare: (a, b) => (a.InvoiceID.toLowerCase() > b.InvoiceID.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Practioner",
    dataIndex: "Practioner",
    key: "Practioner",
    sorter: {
      compare: (a, b) =>
        a.Practioner.toLowerCase() > b.Practioner.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "Location",
    dataIndex: "Location",
    key: "Location",
    sorter: {
      compare: (a, b) => (a.Location.toLowerCase() > b.Location.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => (a.Status.toLowerCase() > b.Status.toLowerCase() ? -1 : 1),
    },
  },
];
const data = [
  {
    Patient: "Alberto Ripley",
    DateTime: "May 27 2025 - 09:30 AM",
    InvoiceID: "#INV0020",
    Practioner: "Dr. Mick Thompson",
    Location: "California",
    Status: "Checked Out",
  },
  {
    Patient: "Susan Babin",
    DateTime: "May 27 2025 - 10:00 AM",
    InvoiceID: "#INV0019",
    Practioner: "Dr. Sarah Johnson",
    Location: "Texas",
    Status: "Checked in",
  },
  {
    Patient: "Carol Lam",
    DateTime: "May 28 2025 - 10:00 AM",
    InvoiceID: "#INV0018",
    Practioner: "Dr. Emily Carter",
    Location: "New York",
    Status: "Cancelled",
  },
  {
    Patient: "Marsha Noland",
    DateTime: "May 28 2025 - 10:30 AM",
    InvoiceID: "#INV0017",
    Practioner: "Dr. David Lee",
    Location: "Florida",
    Status: "Schedule",
  },
  {
    Patient: "Irma Armstrong",
    DateTime: "May 28 2025 - 11: 15 AM",
    InvoiceID: "#INV0016",
    Practioner: "Dr. Anna Kim",
    Location: "Illinois",
    Status: "Confirmed",
  },
  {
    Patient: "Jesus Adams",
    DateTime: "May 29 2025 - 11:30 AM",
    InvoiceID: "#INV0015",
    Practioner: "Dr. John Smith",
    Location: "Pennsylvania",
    Status: "Confirmed",
  },
  {
    Patient: "Ezra Belcher",
    DateTime: "May 30 2025 - 09:30 AM",
    InvoiceID: "#INV0014",
    Practioner: "Dr. Lisa White",
    Location: "Ohio",
    Status: "Cancelled",
  },
  {
    Patient: "Glen Lentz",
    DateTime: "May 30 2025 - 10:00 AM",
    InvoiceID: "#INV0013",
    Practioner: "Dr. Patricia Brown",
    Location: "Georgia",
    Status: "Confirmed",
  },
  {
    Patient: "Bernard Griffith",
    DateTime: "May 30 2025 - 11:00 AM",
    InvoiceID: "#INV0012",
    Practioner: "Dr. Rachel Green",
    Location: "North Carolina",
    Status: "Checked Out",
  },
  {
    Patient: "John Elsass",
    DateTime: "May 30 2025 - 11:00 AM",
    InvoiceID: "#INV0011",
    Practioner: "Dr. Michael Smith",
    Location: "Michigan",
    Status: "Schedule",
  },
];
import { ref } from "vue";
import "daterangepicker/daterangepicker.css";
import "daterangepicker/daterangepicker.js";
import { onMounted } from "vue";
import moment from "moment";
import DateRangePicker from "daterangepicker";
import Vue3TagsInput from "vue3-tags-input";
export default {
  components: {
    Vue3TagsInput,
  },
  data() {
    return {
      selected: null,
      selectedOne: null,
      selectedTwo: null,
      selectedThree: null,
      PatiApp: [
        { label: "Select", value: "Select" },
        { label: "Alberto Ripley", value: "Alberto Ripley" },
        { label: "Susan Babin", value: "Susan Babin" },
        { label: "Martin Lisa", value: "Martin Lisa" },
        { label: "Stella Mary", value: "Stella Mary" },
        { label: "Carol Lam", value: "Carol Lam" },
        { label: "Jesus Adams", value: "Jesus Adams" },
        { label: "Ezra Belcher", value: "Ezra Belcher" },
      ],
      LocaApp: [
        { label: "Select", value: "Select" },
        { label: "California", value: "California" },
        { label: "Options Enhanced", value: "Options Enhanced" },
        { label: "New York", value: "New York" },
        { label: "Florida", value: "Florida" },
        { label: "Illinois", value: "Illinois" },
        { label: "Georgia", value: "Georgia" },
        { label: "Washington", value: "Washington" },
        { label: "Arizona", value: "Arizona" },
      ],
      PracApp: [
        { label: "Select", value: "Select" },
        { label: "Dr. Mick Thompson", value: "Dr. Mick Thompson" },
        { label: "Dr. Sarah Johnson", value: "Dr. Sarah Johnson" },
        { label: "Dr. Emily Carter", value: "Dr. Emily Carter" },
        { label: "Dr. David Lee", value: "Dr. David Lee" },
        { label: "Dr. Anna Kim", value: "Dr. Anna Kim" },
        { label: "Dr. John Smith", value: "Dr. John Smith" },
        { label: "Dr. Lisa White", value: "Dr. Lisa White" },
        { label: "Dr. Patrica Brown", value: "Dr. Patrica Brown" },
      ],
      DesiApp: [
        { label: "Select", value: "Select" },
        { label: "Cardiologist", value: "Cardiologist" },
        { label: "Orthopedic Surgeon", value: "Orthopedic Surgeon" },
        { label: "Pediatrician", value: "Pediatrician" },
        { label: "Gynecologist", value: "Gynecologist" },
        { label: "Psychiatrist", value: "Psychiatrist" },
        { label: "Neurosurgeon", value: "Neurosurgeon" },
        { label: "Oncologist", value: "Oncologist" },
        { label: "Dr. Patrica Brown", value: "Dr. Patrica Brown" },
      ],
      tagsOne: ["Pending"],
      searchQuery: "",
      data,
      columns,
    };
  },
  computed: {
    filteredPages() {
      const query = this.searchQuery.toLowerCase();
      return this.data.filter((record) => {
        return (
          record.Patient.toLowerCase().includes(query) ||
          record.DateTime.toLowerCase().includes(query) ||
          record.InvoiceID.toLowerCase().includes(query) ||
          record.Practioner.toLowerCase().includes(query) ||
          record.Location.toLowerCase().includes(query) ||
          record.Status.toLowerCase().includes(query)
        );
      });
    },
  },
  setup() {
    const dateRangeInput = ref(null);

    // Move the function declaration outside of the onMounted callback
    function booking_range(start, end) {
      return start.format("M/D/YYYY") + " - " + end.format("M/D/YYYY");
    }

    onMounted(() => {
      if (dateRangeInput.value) {
        const start = moment().subtract(6, "days");
        const end = moment();

        new DateRangePicker(
          dateRangeInput.value,
          {
            startDate: start,
            endDate: end,
            ranges: {
              Today: [moment(), moment()],
              Yesterday: [moment().subtract(1, "days"), moment().subtract(1, "days")],
              "Last 7 Days": [moment().subtract(6, "days"), moment()],
              "Last 30 Days": [moment().subtract(29, "days"), moment()],
              "This Month": [moment().startOf("month"), moment().endOf("month")],
              "Last Month": [
                moment().subtract(1, "month").startOf("month"),
                moment().subtract(1, "month").endOf("month"),
              ],
            },
          },
          booking_range
        );

        booking_range(start, end);
      }
    });

    return {
      dateRangeInput,
    };
  },
};
</script>
