// nextjs/template/src/components/pages/doctor/doctors-leaves/doctorsLeaves.tsx
"use client";


import { DatePicker } from "antd";
import {
  Amount,
  Department,
  Designation,
  Doctor,
  Status,
} from "@/core/common/selectOption";
import { useState } from "react";
import SearchInput from "@/core/common/dataTable/dataTableSearch";
import { DoctorLeavesData } from "@/core/json/doctorLeavesData";
import Datatable from "@/core/common/dataTable";
import Modals from "./modals/modals";
import Link from "next/link";
import CommonSelect from "@/core/common/common-select/commonSelect";

const DoctorsLeavesComponent = () => {
  const data = DoctorLeavesData;
  const columns = [
    {
      title: "Date",
      dataIndex: "Date",
      sorter: (a: any, b: any) => a.Date.length - b.Date.length,
    },
    {
      title: "Leave Type",
      dataIndex: "Leave_Type",
      sorter: (a: any, b: any) => a.Leave_Type.length - b.Leave_Type.length,
    },
    {
      title: "Day",
      dataIndex: "Day",
      sorter: (a: any, b: any) => a.Day.length - b.Day.length,
    },
    {
      title: "Applied On",
      dataIndex: "Applied_On",
      sorter: (a: any, b: any) => a.Applied_On.length - b.Applied_On.length,
    },
    {
      title: "Status",
      dataIndex: "Status",
      render: (text: any) => (
        <span
          className={`badge badge-sm border rounded
    ${
      text === "Applied"
        ? "badge-info text-info border-info"
        : text === "Approved"
        ? "badge-success text-success border-success"
        : "badge-danger text-danger border-danger"
    }`}
        >
          {text}
        </span>
      ),
      sorter: (a: any, b: any) => a.Status.length - b.Status.length,
    },
    {
      title: "",
      render: () => (
        <div className="action-item">
          <>
            <Link href="#" data-bs-toggle="dropdown">
              <i className="ti ti-dots-vertical" />
            </Link>
            <ul className="dropdown-menu p-2">
              <li>
                <Link
                  href="#"
                  className="dropdown-item d-flex align-items-center"
                  data-bs-toggle="modal"
                  data-bs-target="#edit-leave"
                >
                  Edit
                </Link>
              </li>
              <li>
                <Link
                  href="#"
                  className="dropdown-item d-flex align-items-center"
                  data-bs-toggle="modal"
                  data-bs-target="#delete_modal"
                >
                  Delete
                </Link>
              </li>
            </ul>
          </>
        </div>
      ),
    },
  ];
  const [searchText, setSearchText] = useState<string>("");

  const handleSearch = (value: string) => {
    setSearchText(value);
  };

  const getModalContainer = () => {
    const modalElement = document.getElementById("modal-datepicker");
    return modalElement ? modalElement : document.body; // Fallback to document.body if modalElement is null
  };
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Start Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3 mb-3 border-1 border-bottom">
            <div className="flex-grow-1">
              <h4 className="fw-bold mb-0"> Leaves </h4>
            </div>
            <div className="text-end d-flex">
              {/* dropdown*/}
              <div className="dropdown me-1">
                <Link
                  href="#"
                  className="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"
                  data-bs-toggle="dropdown"
                >
                  Export
                  <i className="ti ti-chevron-down ms-2" />
                </Link>
                <ul className="dropdown-menu p-2">
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as PDF
                    </Link>
                  </li>
                  <li>
                    <Link className="dropdown-item" href="#">
                      Download as Excel
                    </Link>
                  </li>
                </ul>
              </div>
              <Link
                href="#"
                className="btn btn-primary ms-2 fs-13 btn-md"
                data-bs-toggle="modal"
                data-bs-target="#add-leave"
              >
                <i className="ti ti-plus me-1" />
                Add New Leave
              </Link>
            </div>
          </div>
          {/* End Page Header */}
          {/* Start Filter */}
          <div className=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
            <div className="search-set mb-3">
              <div className="d-flex align-items-center flex-wrap gap-2">
                <div className="table-search d-flex align-items-center mb-0">
                  <div className="search-input">
                    <SearchInput value={searchText} onChange={handleSearch} />
                  </div>
                </div>
              </div>
            </div>
            <div className="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
              <div className="dropdown me-2">
                <Link
                  href="#"
                  className="bg-white border rounded btn btn-md text-dark fs-14 py-1 align-items-center d-flex fw-normal"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                >
                  <i className="ti ti-filter text-gray-5 me-1" />
                  Filters
                </Link>
                <div
                  className="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown p-0"
                  id="filter-dropdown"
                >
                  <div className="d-flex align-items-center justify-content-between border-bottom filter-header">
                    <h4 className="mb-0 fw-bold">Filter</h4>
                    <div className="d-flex align-items-center">
                      <Link
                        href="#"
                        className="link-danger text-decoration-underline"
                      >
                        Clear All
                      </Link>
                    </div>
                  </div>
                  <form action="#">
                    <div className="filter-body pb-0">
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label mb-1">Doctor</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                          options={Doctor}
                          className="select"
                          defaultValue={Doctor[0]}
                        />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Designation</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                          options={Designation}
                          className="select"
                          defaultValue={Designation[0]}
                        />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Department</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                          options={Department}
                          className="select"
                          defaultValue={Department[0]}
                        />
                      </div>
                      <div className="mb-3">
                        <label className="form-label mb-1 text-dark fs-14 fw-medium">
                          Date<span className="text-danger">*</span>
                        </label>
                        <div className="input-icon-end position-relative">
                          <DatePicker
                            className="form-control datetimepicker"
                            format={{
                              format: "DD-MM-YYYY",
                              type: "mask",
                            }}
                            getPopupContainer={getModalContainer}
                            placeholder="DD-MM-YYYY"
                            suffixIcon={null}
                          />
                          <span className="input-icon-addon">
                            <i className="ti ti-calendar" />
                          </span>
                        </div>
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Amount</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                          options={Amount}
                          className="select"
                          defaultValue={Amount[0]}
                        />
                      </div>
                      <div className="mb-3">
                        <div className="d-flex align-items-center justify-content-between">
                          <label className="form-label">Status</label>
                          <Link href="#" className="link-primary mb-1">
                            Reset
                          </Link>
                        </div>
                        <CommonSelect
                          options={Status}
                          className="select"
                          defaultValue={Status[0]}
                        />
                      </div>
                    </div>
                    <div className="filter-footer d-flex align-items-center justify-content-end border-top">
                      <Link
                        href="#"
                        className="btn btn-light btn-md me-2 fw-medium"
                        id="close-filter"
                      >
                        Close
                      </Link>
                      <button
                        type="submit"
                        className="btn btn-primary btn-md fw-medium"
                      >
                        Filter
                      </button>
                    </div>
                  </form>
                </div>
              </div>
              <div className="dropdown">
                <Link
                  href="#"
                  className="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14"
                  data-bs-toggle="dropdown"
                >
                  <span className="me-1"> Sort By : </span> Recent
                </Link>
                <ul className="dropdown-menu  dropdown-menu-end p-2">
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Recent
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="dropdown-item rounded-1">
                      Oldest
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          {/* End Filter */}
          {/* Start Table */}
          <div className="table-responsive">
            <Datatable
              columns={columns}
              dataSource={data}
              Selection={false}
              searchText={searchText}
            />
          </div>
          {/* End Table */}
        </div>
        {/* End Content */}
        {/* Footer Start */}
        <div className="footer text-center bg-white p-2 border-top">
          <p className="text-dark mb-0">
            2025 ©
            <Link href="#" className="link-primary">
              Preclinic
            </Link>
            , All Rights Reserved
          </p>
        </div>
        {/* Footer End */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
      <Modals />
    </>
  );
};

export default DoctorsLeavesComponent;

// vue/template/src/views/pages/doctor/doctors-leaves.vue
<template>
    <doctor-header></doctor-header>
    <doctor-sidebar></doctor-sidebar>

    <!-- ========================
        Start Page Content
    ========================= -->
        
    <div class="page-wrapper">

        <!-- Start Content -->
        <div class="content">

            <!-- Start Page Header -->
            <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3 mb-3 border-1 border-bottom">
                <div class="flex-grow-1">
                    <h4 class="fw-bold mb-0"> Leaves </h4>
                </div>
                <div class="text-end d-flex">
                    <!-- dropdown-->
                    <div class="dropdown me-1">
                        <a href="javascript:void(0);" class="btn btn-md fs-14 fw-normal border bg-white rounded text-dark d-inline-flex align-items-center"  data-bs-toggle="dropdown">
                            Export<i class="ti ti-chevron-down ms-2"></i>
                        </a>
                        <ul class="dropdown-menu p-2">
                            <li>
                                <a class="dropdown-item" href="#">Download as PDF</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Download as Excel</a>
                            </li>
                        </ul>
                    </div>
                    <a href="javascript:void(0);" class="btn btn-primary ms-2 fs-13 btn-md" data-bs-toggle="modal" data-bs-target="#add-leave"><i class="ti ti-plus me-1"></i>Add New Leave</a>
                </div>
            </div>
            <!-- End Page Header -->

            <!-- Start Filter -->
            <div class=" d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                <div class="search-set mb-3">
                    <div class="d-flex align-items-center flex-wrap gap-2">
                        <div class="table-search d-flex align-items-center mb-0">
                            <div class="search-input">
                                <a href="javascript:void(0);" class="btn-searchset"></a>
                                <input
                                    type="text"
                                    class="form-control"
                                    placeholder="Search"
                                    v-model="searchQuery"
                                />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex table-dropdown mb-3 pb-1 right-content align-items-center flex-wrap row-gap-3">
                    <div class="dropdown me-2">
                        <a href="javascript:void(0);" class="bg-white border rounded btn btn-md text-dark fs-14 py-1 align-items-center d-flex fw-normal" data-bs-toggle="dropdown" data-bs-auto-close="outside">
                            <i class="ti ti-filter text-gray-5 me-1"></i>Filters
                        </a>
                        <div class="dropdown-menu dropdown-lg dropdown-menu-end filter-dropdown p-0" id="filter-dropdown">
                            <div class="d-flex align-items-center justify-content-between border-bottom filter-header">
                                <h4 class="mb-0 fw-bold">Filter</h4>
                                <div class="d-flex align-items-center">
                                    <a href="javascript:void(0);" class="link-danger text-decoration-underline">Clear All</a>
                                </div>
                            </div>
                            <filter-index></filter-index>
                        </div>
                    </div>
                    <div class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle btn bg-white btn-md d-inline-flex align-items-center fw-normal rounded border text-dark px-2 py-1 fs-14" data-bs-toggle="dropdown">
                            <span  class="me-1"> Sort By : </span>  Recent
                        </a>
                        <ul class="dropdown-menu  dropdown-menu-end p-2">
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Recent</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Oldest</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- End Filter -->

            <!-- Start Table -->
            <div class="table-responsive">
                <a-table class="table table-nowrap datatable" :columns="columns" :data-source="filteredPages">
                    <template #bodyCell="{ column, record }">
                        <template v-if="column.key === 'Status'">
                            <span :class="[
                                    'badge badge-sm border rounded',
                                    {
                                        'badge-info text-info border-info': record.Status === 'Applied',
                                        'badge-success text-success border-success': record.Status === 'Approved',
                                        'badge-danger text-danger border-danger': record.Status === 'Rejected',
                                    },
                                ]"
                            > {{record.Status}} </span>
                        </template>
                        <template v-if="column.key === 'action'">
                            <div class="action-item"> 
                                <template v-if="record.Status === 'Applied'">
                                    <a href="#" class="" data-bs-toggle="modal" data-bs-target="#cancel-leave">
                                        <i class="ti ti-x"></i> 
                                    </a> 
                                </template>
                                <template v-else>
                                    <a href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <i class="ti ti-dots-vertical"></i>
                                    </a>
                                    <ul class="dropdown-menu p-2">
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#edit-leave">Edit</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#delete_modal">Delete</a>
                                        </li>
                                    </ul>
                                </template>
                            </div>                            
                        </template>
                    </template>
                </a-table>
            </div>
            <!-- End Table -->
            
        </div>
        <!-- End Content -->

        <!-- Footer Start -->
        <div class="footer text-center bg-white p-2 border-top">
            <p class="text-dark mb-0">2025 &copy; <a href="javascript:void(0);" class="link-primary">Preclinic</a>, All Rights Reserved</p>
        </div>
        <!-- Footer End -->

    </div>


    <!-- ========================
        End Page Content
    ========================= -->

    <doctors-leave-modal></doctors-leave-modal>
</template>

<script>
const columns = [
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) =>
        a.Date.toLowerCase() > b.Date.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "Leave Type",
    dataIndex: "Leave_Type",
    sorter: {
      compare: (a, b) =>
        a.Leave_Type.toLowerCase() > b.Leave_Type.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "Day",
    dataIndex: "Day",
    sorter: {
      compare: (a, b) => (a.Day.toLowerCase() > b.Day.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Applied On",
    dataIndex: "Applied_On",
    sorter: {
      compare: (a, b) => (a.Applied_On.toLowerCase() > b.Applied_On.toLowerCase() ? -1 : 1),
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) =>
        a.Status.toLowerCase() > b.Status.toLowerCase() ? -1 : 1,
    },
  },
  {
    title: "",
    key: "action",
    sorter: false,
  },
];

const data = [
 {
   "Date": "15 Apr 2025 - 15 Apr 2025",
   "Leave_Type": "Sick Leave",
   "Day": "01 Day",
   "Applied_On": "22 Apr 2025",
   "Status": "Applied",
 },
 {
   "Date": "30 Apr 2025 - 30 Apr 2025",
   "Leave_Type": "Sick Leave",
   "Day": "01 Day",
   "Applied_On": "22 Apr 2025",
   "Status": "Applied",
 },
 {
   "Date": "15 Apr 2025 - 15 Apr 2025",
   "Leave_Type": "Casual Leave",
   "Day": "01 Day",
   "Applied_On": "12 Apr 2025",
   "Status": "Approved",
 },
 {
   "Date": "02 Apr 2025 - 03 Apr 2025",
   "Leave_Type": "Emergency",
   "Day": "02 Days",
   "Applied_On": "01 Apr 2025",
   "Status": "Rejected",
 },
 {
   "Date": "12 Mar 2025 - 13 Mar 2025",
   "Leave_Type": "Vacation",
   "Day": "02 Days",
   "Applied_On": "05 Mar 2025",
   "Status": "Approved",
 },
 {
   "Date": "27 Mar 2025 - 29 Mar 2025",
   "Leave_Type": "Maternity",
   "Day": "03 Days",
   "Applied_On": "20 Mar 2025",
   "Status": "Rejected",
 },
 {
   "Date": "05 Mar 2025 - 05 Mar 2025",
   "Leave_Type": "Paternity",
   "Day": "01 Day",
   "Applied_On": "01 Mar 2025",
   "Status": "Approved",
 },
 {
   "Date": "24 Feb 2025 - 25 Feb 2025",
   "Leave_Type": "Sick Leave",
   "Day": "02 Days",
   "Applied_On": "15 Feb 2025",
   "Status": "Approved",
 },
 {
   "Date": "16 Feb 2025 - 17 Feb 2025",
   "Leave_Type": "Casual Leave",
   "Day": "01 Day",
   "Applied_On": "09 Feb 2025",
   "Status": "Rejected",
 },
 {
   "Date": "01 Feb 2025 - 01 Feb 2025",
   "Leave_Type": "Emergency",
   "Day": "01 Day",
   "Applied_On": "01 Feb 2025",
   "Status": "Applied",
 },
 {
   "Date": "25 Jan 2025 - 29 Jan 2025",
   "Leave_Type": "Vacation",
   "Day": "05 Days",
   "Applied_On": "12 Jan 2025",
   "Status": "Approved",
 }
]

export default {
    data(){
        return{
            searchQuery: "",
            data,
            columns,
        }
    },
    computed: {
        filteredPages() {
            const query = this.searchQuery.toLowerCase();
            return this.data.filter((record) => {
                return (
                    record.Date.toLowerCase().includes(query) ||
                    record.Leave_Type.toLowerCase().includes(query) ||
                    record.Day.toLowerCase().includes(query) ||
                    record.Applied_On.toLowerCase().includes(query) ||
                    record.Status.toLowerCase().includes(query)
                );
            });
        },
    },
}
</script>
