// vue/template/src/views/pages/pages/starter.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content">
      <!-- Page Header -->
      <div class="pb-3 mb-3 border-bottom">
        <h4 class="fw-bold mb-0">Starter</h4>
      </div>
      <!-- End Page Header -->
    </div>
    <!-- End Content -->
  </div>
</template>

// nextjs/template/src/components/pages/pages/starter.tsx
"use client";

const StarterComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Page Header */}
          <div className="pb-3 mb-3 border-bottom">
            <h4 className="fw-bold mb-0">Starter</h4>
          </div>
          {/* End Page Header */}
        </div>
        {/* End Content */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default StarterComponent;
