// nextjs/template/src/components/pages/ui-modules/ui-interface/base-ui/uiCollapse.tsx
"use client";
import Footer from "@/core/common/footer/footer";
import Link from "next/link";

const UiCollapseComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
            <div className="flex-grow-1">
              <h4 className="fs-18 fw-semibold mb-0">Collapse</h4>
            </div>
            <div className="text-end">
              <ol className="breadcrumb m-0 py-0">
                <li className="breadcrumb-item">
                  <Link href="#">Home</Link>
                </li>
                <li className="breadcrumb-item">
                  <Link href="#">Base UI</Link>
                </li>
                <li className="breadcrumb-item active">Collapse</li>
              </ol>
            </div>
          </div>
          {/* End Page Header */}
          <div className="row">
            <div className="col-xl-6">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Collapse</h5>
                </div>
                {/* end card header */}
                <div className="card-body">
                  <p className="text-muted mb-3">
                    Bootstrap's collapse provides the way to toggle the
                    visibility of any content or element. Please read the
                    official
                    <Link
                      href="https://getbootstrap.com/docs/5.2/components/collapse/"
                      target="_blank"
                    >
                      Bootstrap
                    </Link>
                    documentation for a full list of options.
                  </p>
                  <p>
                    <Link
                      className="btn btn-primary"
                      data-bs-toggle="collapse"
                      href="#collapseExample"
                      aria-expanded="false"
                      aria-controls="collapseExample"
                    >
                      Link with to
                    </Link>
                    <button
                      className="btn btn-primary ms-1"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseExample"
                      aria-expanded="false"
                      aria-controls="collapseExample"
                    >
                      Button with data-bs-target
                    </button>
                  </p>
                  <div className="collapse show" id="collapseExample">
                    <div className="card card-body mb-0">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life
                      accusamus terry richardson ad squid. Nihil anim keffiyeh
                      helvetica, craft beer labore wes anderson cred nesciunt
                      sapiente ea proident.
                    </div>
                  </div>
                </div>
                {/* end card-body*/}
              </div>
              {/* end card*/}
            </div>
            {/* end col*/}
            <div className="col-xl-6">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Collapse Horizontal</h5>
                </div>
                {/* end card header */}
                <div className="card-body">
                  <p className="text-muted mb-3">
                    The collapse plugin also supports horizontal collapsing. Add
                    the <code>.collapse-horizontal</code> modifier class to
                    transition the <code>width</code> instead of
                    <code>height</code> and set a <code>width</code> on the
                    immediate child element.
                  </p>
                  <p>
                    <button
                      className="btn btn-primary"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseWidthExample"
                      aria-expanded="false"
                      aria-controls="collapseWidthExample"
                    >
                      Toggle width collapse
                    </button>
                  </p>
                  <div style={{ minHeight: 105 }}>
                    <div
                      className="collapse collapse-horizontal"
                      id="collapseWidthExample"
                    >
                      <div
                        className="card card-body mb-0"
                        style={{ width: 300 }}
                      >
                        This is some placeholder content for a horizontal
                        collapse. It's hidden by default and shown when
                        triggered.
                      </div>
                    </div>
                  </div>
                </div>
                {/* end card-body*/}
              </div>
              {/* end card*/}
            </div>
            {/* end col*/}
          </div>
          {/* end row*/}
          <div className="row">
            <div className="col-xl-12">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Multiple Targets</h5>
                </div>
                {/* end card header */}
                <div className="card-body">
                  <p className="text-muted mb-3">
                    
                    Multiple <code>&lt;button&gt;</code> or
                    <code>&lt;a&gt;</code> can show and hide an element if they
                    each reference it with their <code>to</code> or
                    <code>data-bs-target</code> attribute
                  </p>
                  <p className="mb-0">
                    <Link
                      className="btn btn-primary me-2"
                      data-bs-toggle="collapse"
                      href="#multiCollapseExample1"
                      role="button"
                      aria-expanded="false"
                      aria-controls="multiCollapseExample1"
                    >
                      Toggle first element
                    </Link>
                    <button
                      className="btn btn-primary me-2"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#multiCollapseExample2"
                      aria-expanded="false"
                      aria-controls="multiCollapseExample2"
                    >
                      Toggle second element
                    </button>
                    <button
                      className="btn btn-primary"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target=".multi-collapse"
                      aria-expanded="false"
                      aria-controls="multiCollapseExample1 multiCollapseExample2"
                    >
                      Toggle both elements
                    </button>
                  </p>
                  <div className="row">
                    <div className="col">
                      <div
                        className="collapse multi-collapsee mt-2"
                        id="multiCollapseExample1"
                      >
                        <div className="card card-body mb-0">
                          Anim pariatur cliche reprehenderit, enim eiusmod high
                          life accusamus terry richardson ad squid. Nihil anim
                          keffiyeh helvetica, craft beer labore wes anderson
                          cred nesciunt sapiente ea proident.
                        </div>
                      </div>
                    </div>
                    <div className="col">
                      <div
                        className="collapse multi-collapse mt-2"
                        id="multiCollapseExample2"
                      >
                        <div className="card card-body mb-0">
                          Anim pariatur cliche reprehenderit, enim eiusmod high
                          life accusamus terry richardson ad squid. Nihil anim
                          keffiyeh helvetica, craft beer labore wes anderson
                          cred nesciunt sapiente ea proident.
                        </div>
                      </div>
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row*/}
                </div>
                {/* end card-body*/}
              </div>
              {/* end card*/}
            </div>
            {/* end col*/}
          </div>
          {/* end row*/}
        </div>
        {/*End container */}
        {/* Start Footer */}
        <Footer/>
        {/* End Footer */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default UiCollapseComponent;

// vue/template/src/views/pages/uiinterface/baseui/ui-collapse.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content">
      <!-- Page Header -->
      <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
        <div class="flex-grow-1">
          <h4 class="fs-18 fw-semibold mb-0">Collapse</h4>
        </div>
        <div class="text-end">
          <ol class="breadcrumb m-0 py-0">
            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>

            <li class="breadcrumb-item"><a href="javascript: void(0);">Base UI</a></li>

            <li class="breadcrumb-item active">Collapse</li>
          </ol>
        </div>
      </div>
      <!-- End Page Header -->

      <div class="row">
        <div class="col-xl-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Collapse</h5>
            </div>
            <!-- end card header -->
            <div class="card-body">
              <p class="text-muted mb-3">
                Bootstrap's collapse provides the way to toggle the visibility of any
                content or element. Please read the official
                <a
                  href="https://getbootstrap.com/docs/5.2/components/collapse/"
                  target="_blank"
                  >Bootstrap</a
                >
                documentation for a full list of options.
              </p>

              <p>
                <a
                  class="btn btn-primary"
                  data-bs-toggle="collapse"
                  href="#collapseExample"
                  aria-expanded="false"
                  aria-controls="collapseExample"
                >
                  Link with href
                </a>
                <button
                  class="btn btn-primary ms-1"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseExample"
                  aria-expanded="false"
                  aria-controls="collapseExample"
                >
                  Button with data-bs-target
                </button>
              </p>
              <div class="collapse show" id="collapseExample">
                <div class="card card-body mb-0">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                  terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                  labore wes anderson cred nesciunt sapiente ea proident.
                </div>
              </div>
            </div>
            <!-- end card-body-->
          </div>
          <!-- end card-->
        </div>
        <!-- end col-->

        <div class="col-xl-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Collapse Horizontal</h5>
            </div>
            <!-- end card header -->

            <div class="card-body">
              <p class="text-muted mb-3">
                The collapse plugin also supports horizontal collapsing. Add the
                <code>.collapse-horizontal</code> modifier class to transition the
                <code>width</code> instead of <code>height</code> and set a
                <code>width</code> on the immediate child element.
              </p>
              <p>
                <button
                  class="btn btn-primary"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseWidthExample"
                  aria-expanded="false"
                  aria-controls="collapseWidthExample"
                >
                  Toggle width collapse
                </button>
              </p>
              <div style="min-height: 105px">
                <div class="collapse collapse-horizontal" id="collapseWidthExample">
                  <div class="card card-body mb-0" style="width: 300px">
                    This is some placeholder content for a horizontal collapse. It's
                    hidden by default and shown when triggered.
                  </div>
                </div>
              </div>
            </div>
            <!-- end card-body-->
          </div>
          <!-- end card-->
        </div>
        <!-- end col-->
      </div>
      <!-- end row-->

      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Multiple Targets</h5>
            </div>
            <!-- end card header -->

            <div class="card-body">
              <p class="text-muted mb-3">
                Multiple <code>&lt;button&gt;</code> or <code>&lt;a&gt;</code> can show
                and hide an element if they each reference it with their
                <code>href</code> or <code>data-bs-target</code> attribute
              </p>

              <p class="mb-0">
                <a
                  class="btn btn-primary"
                  data-bs-toggle="collapse"
                  href="#multiCollapseExample1"
                  role="button"
                  aria-expanded="false"
                  aria-controls="multiCollapseExample1"
                  >Toggle first element</a
                >
                <button
                  class="btn btn-primary"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#multiCollapseExample2"
                  aria-expanded="false"
                  aria-controls="multiCollapseExample2"
                >
                  Toggle second element
                </button>
                <button
                  class="btn btn-primary"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target=".multi-collapse"
                  aria-expanded="false"
                  aria-controls="multiCollapseExample1 multiCollapseExample2"
                >
                  Toggle both elements
                </button>
              </p>

              <div class="row">
                <div class="col">
                  <div class="collapse multi-collapsee mt-2" id="multiCollapseExample1">
                    <div class="card card-body mb-0">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                      terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                      labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                  </div>
                </div>
                <div class="col">
                  <div class="collapse multi-collapse mt-2" id="multiCollapseExample2">
                    <div class="card card-body mb-0">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
                      terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer
                      labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                  </div>
                </div>
                <!-- end col -->
              </div>
              <!-- end row-->
            </div>
            <!-- end card-body-->
          </div>
          <!-- end card-->
        </div>
        <!-- end col-->
      </div>
      <!-- end row-->
    </div>
    <!--End container -->

    <!-- Start Footer -->
    <div
      class="footer d-sm-flex align-items-center justify-content-between bg-white py-2 px-4 border-top"
    >
      <p class="text-dark mb-0">
        &copy; 2025 <a href="javascript:void(0);" class="link-primary">Kanakku</a>, All
        Rights Reserved
      </p>
      <p class="text-dark">Version : 1.3.8</p>
    </div>
    <!-- End Footer -->
  </div>
</template>
<script>
export default {
  data() {
    return {
      title: "Home",
      text: "Collapse",
    };
  },
};
</script>
