// nextjs/template/src/components/pages/ui-modules/ui-interface/base-ui/uiListGroup.tsx

"use client";
import Footer from "@/core/common/footer/footer";
import Link from "next/link";

const UiListGroupComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content">
          {/* Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
            <div className="flex-grow-1">
              <h4 className="fs-18 fw-semibold mb-0">List Group</h4>
            </div>
            <div className="text-end">
              <ol className="breadcrumb m-0 py-0">
                <li className="breadcrumb-item">
                  <Link href="#">Home</Link>
                </li>
                <li className="breadcrumb-item">
                  <Link href="#">Base UI</Link>
                </li>
                <li className="breadcrumb-item active">List Group</li>
              </ol>
            </div>
          </div>
          {/* End Page Header */}
          {/* start row */}
          <div className="row">
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Basic example</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    The most basic list group is an unordered list with list
                    items and the proper classes. Build upon it with the options
                    that follow, or with your own CSS as needed.
                  </p>
                  <ul className="list-group">
                    <li className="list-group-item">
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack Collaboration
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-nextcloud me-1 align-middle fs-18" />
                      Nextcloud File Sharing
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom Video Meetings
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe Billing System
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Active Items</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Add <code>.active</code> to a <code>.list-group-item</code>
                    to indicate the current active selection.
                  </p>
                  <ul className="list-group">
                    <li className="list-group-item active">
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack Collaboration
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-nextcloud me-1 align-middle fs-18" />
                      Nextcloud File Sharing
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom Video Meetings
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-notion me-1 align-middle fs-18" />
                      Notion Workspace
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe Billing System
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Disabled Items</h5>
                </div>
                <div className="card-body">
                  <p>
                    Add <code>.disabled</code> to a
                    <code>.list-group-item</code> to make it
                    <em>appear</em> disabled.
                  </p>
                  <ul className="list-group">
                    <li
                      className="list-group-item disabled"
                      aria-disabled="true"
                    >
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack Collaboration
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-nextcloud me-1 align-middle fs-18" />
                      Nextcloud File Sharing
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom Video Meetings
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-notion me-1 align-middle fs-18" />
                      Notion Workspace
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe Billing System
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
          </div>
          {/* end row */}
          <div className="row">
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Links and Buttons</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Use <code>&lt;a&gt;</code>s or
                    <code>&lt;button&gt;</code>s to create <em>actionable</em>
                    list group items with hover, disabled, and active states by
                    adding
                    <code>.list-group-item-action</code>.
                  </p>
                  <div className="list-group">
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action active"
                    >
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack Collaboration
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action"
                    >
                      <i className="ti ti-brand-nextcloud me-1 align-middle fs-18" />
                      Nextcloud File Sharing
                    </Link>
                    <button
                      type="button"
                      className="list-group-item list-group-item-action"
                    >
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom Video Meetings
                    </button>
                    <button
                      type="button"
                      className="list-group-item list-group-item-action"
                    >
                      <i className="ti ti-brand-notion me-1 align-middle fs-18" />
                      Notion Workspace
                    </button>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action disabled"
                      tabIndex={-1}
                      aria-disabled="true"
                    >
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe Billing System
                    </Link>
                  </div>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Flush</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Add <code>.list-group-flush</code> to remove some borders
                    and rounded corners to render list group items edge-to-edge
                    in a parent container (e.g., cards).
                  </p>
                  <ul className="list-group list-group-flush">
                    <li className="list-group-item">
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack Collaboration
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-nextcloud me-1 align-middle fs-18" />
                      Nextcloud File Sharing
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom Video Meetings
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-notion me-1 align-middle fs-18" />
                      Notion Workspace
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe Billing System
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Numbered</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Numbers are generated by <code>counter-reset</code> on the
                    <code>&lt;ol&gt;</code>, and then styled and placed with a
                    <code>::before</code> psuedo-element on the
                    <code>&lt;li&gt;</code> with
                    <code>counter-increment</code> and <code>content</code>.
                  </p>
                  <ol className="list-group list-group-numbered">
                    <li className="list-group-item d-flex justify-content-between align-items-start">
                      <div className="ms-2 me-auto">
                        <div className="fw-bold">SmartOne Admin</div>
                        SmartOne Admin
                      </div>
                      <span className="badge bg-primary rounded-pill">865</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-start">
                      <div className="ms-2 me-auto">
                        <div className="fw-bold">SmartOne React Admin</div>
                        SmartOne React Admin
                      </div>
                      <span className="badge bg-primary rounded-pill">140</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-start">
                      <div className="ms-2 me-auto">
                        <div className="fw-bold">Angular Version</div>
                        Angular Version
                      </div>
                      <span className="badge bg-primary rounded-pill">85</span>
                    </li>
                  </ol>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
          </div>
          {/* end row */}
          <div className="row">
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Contextual Classes</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Use contextual classes to style list items with a stateful
                    background and color.
                  </p>
                  <ul className="list-group">
                    <li className="list-group-item">Dapibus ac facilisis in</li>
                    <li className="list-group-item list-group-item-primary">
                      A simple primary list group item
                    </li>
                    <li className="list-group-item list-group-item-secondary">
                      A simple secondary list group item
                    </li>
                    <li className="list-group-item list-group-item-success">
                      A simple success list group item
                    </li>
                    <li className="list-group-item list-group-item-danger">
                      A simple danger list group item
                    </li>
                    <li className="list-group-item list-group-item-warning">
                      A simple warning list group item
                    </li>
                    <li className="list-group-item list-group-item-info">
                      A simple info list group item
                    </li>
                    <li className="list-group-item list-group-item-light">
                      A simple light list group item
                    </li>
                    <li className="list-group-item list-group-item-dark">
                      A simple dark list group item
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Contextual Classes with Link</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Use contextual classes to style list items with a stateful
                    background and color.
                  </p>
                  <div className="list-group">
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action"
                    >
                      Darius ac facilities in
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-primary"
                    >
                      A simple primary list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-secondary"
                    >
                      A simple secondary list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-success"
                    >
                      A simple success list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-danger"
                    >
                      A simple danger list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-warning"
                    >
                      A simple warning list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-info"
                    >
                      A simple info list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-light"
                    >
                      A simple light list group item
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action list-group-item-dark"
                    >
                      A simple dark list group item
                    </Link>
                  </div>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Custom content</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Add nearly any HTML within, even for linked list groups like
                    the one below, with the help of flexbox utilities.
                  </p>
                  <div className="list-group">
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action active"
                    >
                      <div className="d-flex w-100 justify-content-between">
                        <h5 className="fs-16 mb-1">List group item heading</h5>
                        <small>3 days ago</small>
                      </div>
                      <p className="mb-1">
                        Donec id elit non mi porta gravida at eget metus.
                        Maecenas sed diam eget risus varius blandit.
                      </p>
                      <small>Donec id elit non mi porta.</small>
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action"
                    >
                      <div className="d-flex w-100 justify-content-between">
                        <h5 className="fs-16 mb-1">List group item heading</h5>
                        <small className="text-muted">3 days ago</small>
                      </div>
                      <p className="mb-1">
                        Donec id elit non mi porta gravida at eget metus.
                        Maecenas sed diam eget risus varius blandit.
                      </p>
                      <small className="text-muted">
                        Donec id elit non mi porta.
                      </small>
                    </Link>
                    <Link
                      href="#"
                      className="list-group-item list-group-item-action"
                    >
                      <div className="d-flex w-100 justify-content-between">
                        <h5 className="fs-16 mb-1">List group item heading</h5>
                        <small className="text-muted">3 days ago</small>
                      </div>
                      <p className="mb-1">
                        Donec id elit non mi porta gravida at eget metus.
                        Maecenas sed diam eget risus varius blandit.
                      </p>
                      <small className="text-muted">
                        Donec id elit non mi porta.
                      </small>
                    </Link>
                  </div>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
          </div>
          {/* end row */}
          <div className="row">
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Horizontal</h5>
                </div>
                <div className="card-body">
                  <p>
                    Add <code>.list-group-horizontal</code> to change the layout
                    of list group items from vertical to horizontal across all
                    breakpoints. Alternatively, choose a responsive variant
                    <code>
                      .list-group-horizontal-{"{"}sm|md|lg|xl|xxl{"}"}
                    </code>
                    to make a list group horizontal starting at that
                    breakpoint’s <code>min-width</code>.
                  </p>
                  <ul className="list-group list-group-horizontal mb-3">
                    <li className="list-group-item">
                      <i className="ti ti-brand-slack me-1 align-middle fs-18" />
                      Slack
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-zoom me-1 align-middle fs-18" />
                      Zoom
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-trello me-1 align-middle fs-18" />
                      Trello
                    </li>
                  </ul>
                  <ul className="list-group list-group-horizontal-sm mb-3">
                    <li className="list-group-item">
                      <i className="ti ti-brand-notion me-1 align-middle fs-18" />
                      Notion
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-stripe me-1 align-middle fs-18" />
                      Stripe
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-dropbox me-1 align-middle fs-18" />
                      Dropbox
                    </li>
                  </ul>
                  <ul className="list-group list-group-horizontal-md">
                    <li className="list-group-item">
                      <i className="ti ti-brand-github me-1 align-middle fs-18" />
                      GitHub
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-discord me-1 align-middle fs-18" />
                      Discord
                    </li>
                    <li className="list-group-item">
                      <i className="ti ti-brand-asana me-1 align-middle fs-18" />
                      Asana
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">With Badges</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Add badges to any list group item to show unread counts,
                    activity, and more with the help of some utilities.
                  </p>
                  <ul className="list-group">
                    <li className="list-group-item d-flex justify-content-between align-items-center">
                      New Task Assignments
                      <span className="badge bg-primary rounded-pill">5</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-center">
                      Upcoming Meetings
                      <span className="badge bg-success rounded-pill">3</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-center">
                      System Notifications
                      <span className="badge bg-danger rounded-pill">15+</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-center">
                      Completed Projects
                      <span className="badge bg-success rounded-pill">8</span>
                    </li>
                    <li className="list-group-item d-flex justify-content-between align-items-center">
                      Overdue Tasks
                      <span className="badge bg-warning rounded-pill">2</span>
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
            <div className="col-xl-4">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Checkboxes and Radios</h5>
                </div>
                <div className="card-body">
                  <p className="text-muted">
                    Place Bootstrap’s checkboxes and radios within list group
                    items and customize as needed. You can use them without
                    <code>&lt;label&gt;</code>s, but please remember to include
                    an
                    <code>aria-label</code> attribute and value for
                    accessibility.
                  </p>
                  <ul className="list-group">
                    <li className="list-group-item">
                      <input
                        className="form-check-input me-1"
                        type="checkbox"
                        id="firstCheckbox"
                      />
                      <label
                        className="form-check-label"
                        htmlFor="firstCheckbox"
                      >
                        First checkbox
                      </label>
                    </li>
                    <li className="list-group-item">
                      <input
                        className="form-check-input me-1"
                        type="checkbox"
                        id="secondCheckbox"
                      />
                      <label
                        className="form-check-label"
                        htmlFor="secondCheckbox"
                      >
                        Second checkbox
                      </label>
                    </li>
                  </ul>
                  <ul className="list-group mt-2">
                    <li className="list-group-item">
                      <input
                        className="form-check-input me-1"
                        type="radio"
                        name="listGroupRadio"
                        id="firstRadio"
                        defaultChecked
                      />
                      <label className="form-check-label" htmlFor="firstRadio">
                        First radio
                      </label>
                    </li>
                    <li className="list-group-item">
                      <input
                        className="form-check-input me-1"
                        type="radio"
                        name="listGroupRadio"
                        id="secondRadio"
                      />
                      <label className="form-check-label" htmlFor="secondRadio">
                        Second radio
                      </label>
                    </li>
                  </ul>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
          </div>
          {/* end row */}
        </div>
        {/* End Content */}
        {/* Start Footer */}
        <Footer/>
        {/* End Footer */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default UiListGroupComponent;

// vue/template/src/views/pages/uiinterface/baseui/ui-list-group.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <!-- ========================
			Start Page Content
		========================= -->

  <div class="page-wrapper">
    <!-- Start Content -->
    <div class="content">
      <!-- Page Header -->
      <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
        <div class="flex-grow-1">
          <h4 class="fs-18 fw-semibold mb-0">List Group</h4>
        </div>

        <div class="text-end">
          <ol class="breadcrumb m-0 py-0">
            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript: void(0);">Base UI</a></li>
            <li class="breadcrumb-item active">List Group</li>
          </ol>
        </div>
      </div>
      <!-- End Page Header -->

      <!-- start row -->
      <div class="row">
        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Basic example</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                The most basic list group is an unordered list with list items and the
                proper classes. Build upon it with the options that follow, or with your
                own CSS as needed.
              </p>

              <ul class="list-group">
                <li class="list-group-item">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                  Collaboration
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-nextcloud me-1 align-middle fs-18"></i> Nextcloud
                  File Sharing
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom Video
                  Meetings
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                  Billing System
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Active Items</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Add <code>.active</code> to a <code>.list-group-item</code> to indicate
                the current active selection.
              </p>

              <ul class="list-group">
                <li class="list-group-item active">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                  Collaboration
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-nextcloud me-1 align-middle fs-18"></i> Nextcloud
                  File Sharing
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom Video
                  Meetings
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-notion me-1 align-middle fs-18"></i> Notion
                  Workspace
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                  Billing System
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Disabled Items</h5>
            </div>

            <div class="card-body">
              <p>
                Add <code>.disabled</code> to a <code>.list-group-item</code> to make it
                <em>appear</em> disabled.
              </p>

              <ul class="list-group">
                <li class="list-group-item disabled" aria-disabled="true">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                  Collaboration
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-nextcloud me-1 align-middle fs-18"></i> Nextcloud
                  File Sharing
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom Video
                  Meetings
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-notion me-1 align-middle fs-18"></i> Notion
                  Workspace
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                  Billing System
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->
      </div>
      <!-- end row -->

      <div class="row">
        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Links and Buttons</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Use <code>&lt;a&gt;</code>s or <code>&lt;button&gt;</code>s to create
                <em>actionable</em> list group items with hover, disabled, and active
                states by adding <code>.list-group-item-action</code>.
              </p>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action active">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                  Collaboration
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                  <i class="ti ti-brand-nextcloud me-1 align-middle fs-18"></i> Nextcloud
                  File Sharing
                </a>
                <button type="button" class="list-group-item list-group-item-action">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom Video
                  Meetings
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                  <i class="ti ti-brand-notion me-1 align-middle fs-18"></i> Notion
                  Workspace
                </button>
                <a
                  href="#"
                  class="list-group-item list-group-item-action disabled"
                  tabindex="-1"
                  aria-disabled="true"
                >
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                  Billing System
                </a>
              </div>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Flush</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Add <code>.list-group-flush</code> to remove some borders and rounded
                corners to render list group items edge-to-edge in a parent container
                (e.g., cards).
              </p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                  Collaboration
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-nextcloud me-1 align-middle fs-18"></i> Nextcloud
                  File Sharing
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom Video
                  Meetings
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-notion me-1 align-middle fs-18"></i> Notion
                  Workspace
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                  Billing System
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Numbered</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Numbers are generated by <code>counter-reset</code> on the
                <code>&lt;ol&gt;</code>, and then styled and placed with a
                <code>::before</code> psuedo-element on the <code>&lt;li&gt;</code> with
                <code>counter-increment</code> and <code>content</code>.
              </p>

              <ol class="list-group list-group-numbered">
                <li
                  class="list-group-item d-flex justify-content-between align-items-start"
                >
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">SmartOne Admin</div>
                    SmartOne Admin
                  </div>
                  <span class="badge bg-primary rounded-pill">865</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-start"
                >
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">SmartOne React Admin</div>
                    SmartOne React Admin
                  </div>
                  <span class="badge bg-primary rounded-pill">140</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-start"
                >
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">Angular Version</div>
                    Angular Version
                  </div>
                  <span class="badge bg-primary rounded-pill">85</span>
                </li>
              </ol>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->
      </div>
      <!-- end row -->

      <div class="row">
        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Contextual Classes</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Use contextual classes to style list items with a stateful background and
                color.
              </p>

              <ul class="list-group">
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item list-group-item-primary">
                  A simple primary list group item
                </li>
                <li class="list-group-item list-group-item-secondary">
                  A simple secondary list group item
                </li>
                <li class="list-group-item list-group-item-success">
                  A simple success list group item
                </li>
                <li class="list-group-item list-group-item-danger">
                  A simple danger list group item
                </li>
                <li class="list-group-item list-group-item-warning">
                  A simple warning list group item
                </li>
                <li class="list-group-item list-group-item-info">
                  A simple info list group item
                </li>
                <li class="list-group-item list-group-item-light">
                  A simple light list group item
                </li>
                <li class="list-group-item list-group-item-dark">
                  A simple dark list group item
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Contextual Classes with Link</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Use contextual classes to style list items with a stateful background and
                color.
              </p>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action"
                  >Darius ac facilities in</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-primary"
                  >A simple primary list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-secondary"
                  >A simple secondary list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-success"
                  >A simple success list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-danger"
                  >A simple danger list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-warning"
                  >A simple warning list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-info"
                  >A simple info list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-light"
                  >A simple light list group item</a
                >
                <a
                  href="#"
                  class="list-group-item list-group-item-action list-group-item-dark"
                  >A simple dark list group item</a
                >
              </div>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Custom content</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Add nearly any HTML within, even for linked list groups like the one
                below, with the help of flexbox utilities.
              </p>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action active">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="fs-16 mb-1">List group item heading</h5>
                    <small>3 days ago</small>
                  </div>
                  <p class="mb-1">
                    Donec id elit non mi porta gravida at eget metus. Maecenas sed diam
                    eget risus varius blandit.
                  </p>
                  <small>Donec id elit non mi porta.</small>
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="fs-16 mb-1">List group item heading</h5>
                    <small class="text-muted">3 days ago</small>
                  </div>
                  <p class="mb-1">
                    Donec id elit non mi porta gravida at eget metus. Maecenas sed diam
                    eget risus varius blandit.
                  </p>
                  <small class="text-muted">Donec id elit non mi porta.</small>
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="fs-16 mb-1">List group item heading</h5>
                    <small class="text-muted">3 days ago</small>
                  </div>
                  <p class="mb-1">
                    Donec id elit non mi porta gravida at eget metus. Maecenas sed diam
                    eget risus varius blandit.
                  </p>
                  <small class="text-muted">Donec id elit non mi porta.</small>
                </a>
              </div>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->
      </div>
      <!-- end row -->

      <div class="row">
        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Horizontal</h5>
            </div>

            <div class="card-body">
              <p>
                Add <code>.list-group-horizontal</code> to change the layout of list group
                items from vertical to horizontal across all breakpoints. Alternatively,
                choose a responsive variant
                <code>.list-group-horizontal-{sm|md|lg|xl|xxl}</code> to make a list group
                horizontal starting at that breakpoint’s <code>min-width</code>.
              </p>

              <ul class="list-group list-group-horizontal mb-3">
                <li class="list-group-item">
                  <i class="ti ti-brand-slack me-1 align-middle fs-18"></i> Slack
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-zoom me-1 align-middle fs-18"></i> Zoom
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-trello me-1 align-middle fs-18"></i> Trello
                </li>
              </ul>

              <ul class="list-group list-group-horizontal-sm mb-3">
                <li class="list-group-item">
                  <i class="ti ti-brand-notion me-1 align-middle fs-18"></i> Notion
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-stripe me-1 align-middle fs-18"></i> Stripe
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-dropbox me-1 align-middle fs-18"></i> Dropbox
                </li>
              </ul>

              <ul class="list-group list-group-horizontal-md">
                <li class="list-group-item">
                  <i class="ti ti-brand-github me-1 align-middle fs-18"></i> GitHub
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-discord me-1 align-middle fs-18"></i> Discord
                </li>
                <li class="list-group-item">
                  <i class="ti ti-brand-asana me-1 align-middle fs-18"></i> Asana
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">With Badges</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Add badges to any list group item to show unread counts, activity, and
                more with the help of some utilities.
              </p>

              <ul class="list-group">
                <li
                  class="list-group-item d-flex justify-content-between align-items-center"
                >
                  New Task Assignments
                  <span class="badge bg-primary rounded-pill">5</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center"
                >
                  Upcoming Meetings
                  <span class="badge bg-success rounded-pill">3</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center"
                >
                  System Notifications
                  <span class="badge bg-danger rounded-pill">15+</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center"
                >
                  Completed Projects
                  <span class="badge bg-success rounded-pill">8</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center"
                >
                  Overdue Tasks
                  <span class="badge bg-warning rounded-pill">2</span>
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->

        <div class="col-xl-4">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Checkboxes and Radios</h5>
            </div>

            <div class="card-body">
              <p class="text-muted">
                Place Bootstrap’s checkboxes and radios within list group items and
                customize as needed. You can use them without <code>&lt;label&gt;</code>s,
                but please remember to include an <code>aria-label</code> attribute and
                value for accessibility.
              </p>

              <ul class="list-group">
                <li class="list-group-item">
                  <input
                    class="form-check-input me-1"
                    type="checkbox"
                    value=""
                    id="firstCheckbox"
                  />
                  <label class="form-check-label" for="firstCheckbox"
                    >First checkbox</label
                  >
                </li>
                <li class="list-group-item">
                  <input
                    class="form-check-input me-1"
                    type="checkbox"
                    value=""
                    id="secondCheckbox"
                  />
                  <label class="form-check-label" for="secondCheckbox"
                    >Second checkbox</label
                  >
                </li>
              </ul>

              <ul class="list-group mt-2">
                <li class="list-group-item">
                  <input
                    class="form-check-input me-1"
                    type="radio"
                    name="listGroupRadio"
                    value=""
                    id="firstRadio"
                    checked
                  />
                  <label class="form-check-label" for="firstRadio">First radio</label>
                </li>
                <li class="list-group-item">
                  <input
                    class="form-check-input me-1"
                    type="radio"
                    name="listGroupRadio"
                    value=""
                    id="secondRadio"
                  />
                  <label class="form-check-label" for="secondRadio">Second radio</label>
                </li>
              </ul>
            </div>
            <!-- end card body -->
          </div>
          <!-- end card -->
        </div>
        <!-- end col -->
      </div>
      <!-- end row -->
    </div>
    <!-- End Content -->

    <!-- Start Footer -->
    <div
      class="footer d-sm-flex align-items-center justify-content-between bg-white py-2 px-4 border-top"
    >
      <p class="text-dark mb-0">
        &copy; 2025 <a href="javascript:void(0);" class="link-primary">Kanakku</a>, All
        Rights Reserved
      </p>
      <p class="text-title">Version : 1.3.8</p>
    </div>
    <!-- End Footer -->
  </div>

  <!-- ========================
End Page Content
========================= -->
</template>
<script>
export default {
  data() {
    return {
      title: "Home",
      text: "List Group",
    };
  },
};
</script>
