// angular/template/src/app/auth/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component} from '@angular/core';
  import { Router, RouterLink } from '@angular/router';
import { routes } from '../../../../src/app/shared/routes/routes';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss'],
    imports: [CommonModule,FormsModule,RouterLink],
})
export class LoginComponent {
  public routes = routes;
  public passwordClass = false;
  togglePassword() {
    this.passwordClass = !this.passwordClass;
  }
  constructor(private router:Router){
    
  }
  pageRedirect(){
    this.router.navigate([routes.index])
  }
}

    <!-- Begin Wrapper -->
    <div class="auth-bg auth-bg-custom position-relative overflow-hidden">

        <!-- Start Content -->
		<div class="container-fuild position-relative z-1">
			<div class="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">

				<!-- start row -->
				<div class="row justify-content-center align-items-center vh-100 overflow-auto flex-wrap py-3">
					<div class="col-lg-4 mx-auto">
						<form (ngSubmit)="pageRedirect()" class="d-flex justify-content-center align-items-center">
							<div class="d-flex flex-column justify-content-lg-center p-4 p-lg-0 pb-0 flex-fill">
								<div class=" mx-auto mb-4 text-center">
									<img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
								</div>
								<div class="card border-1 p-lg-3 shadow-md rounded-3 mb-4">
									<div class="card-body">
										<div class="text-center mb-3">
											<h5 class="mb-1 fs-20 fw-bold">Sign In</h5>
											<p class="mb-0">Please enter below details to access the dashboard</p>
										</div>
										<div class="mb-3">
											<label class="form-label">Email Address</label>
											<div class="input-group">
												<span class="input-group-text border-end-0 bg-white">
													<i class="ti ti-mail fs-14 text-dark"></i>
												</span>
												<input type="text" value="" class="form-control border-start-0 ps-0" placeholder="Enter Email Address">
											</div>
										</div>
										<div class="mb-3">
											<label class="form-label">Password</label>
											<div class="position-relative">
                                                <div class="pass-group input-group position-relative border rounded">
                                                    <span class="input-group-text bg-white border-0">
                                                        <i class="ti ti-lock text-dark fs-14"></i>
                                                    </span>
                                                    <input type="password" [type]="passwordClass?'text':'password'" class="pass-input form-control ps-0 border-0" placeholder="****************">
                                                    <span class="input-group-text bg-white border-0">
                                                        <i class="ti toggle-password  text-dark fs-14" [ngClass]="passwordClass?'ti-eye':'ti-eye-off'" (click)="togglePassword()"></i>
                                                    </span>
                                                </div>
                                            </div>
										</div>
										<div class="d-flex align-items-center justify-content-between mb-3">
											<div class="d-flex align-items-center">
												<div class="form-check form-check-md mb-0">
													<input class="form-check-input" id="remember_me" type="checkbox">
													<label for="remember_me" class="form-check-label mt-0 text-dark">Remember Me</label>
												</div>
											</div>
											<div class="text-end">
												<a [routerLink]="routes.forgotPasswordBasic" class="text-danger">Forgot Password?</a>
											</div>
										</div>
										<div class="mb-2">
											<button type="submit" class="btn bg-primary text-white w-100">Login</button>
										</div>
										<div class="login-or position-relative mb-3">
											<span class="span-or">OR</span>
										</div>
										<div class="mb-3">
											<div class="d-flex align-items-center justify-content-center flex-wrap">
												<div class="text-center me-2 flex-fill">
													<a href="javascript:void(0);"
														class="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center">
														<img class="img-fluid m-1" src="assets/img/icons/facebook-logo.svg" alt="Facebook">
													</a>
												</div>
												<div class="text-center me-2 flex-fill">
													<a href="javascript:void(0);"
														class="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center">
														<img class="img-fluid m-1" src="assets/img/icons/google-logo.svg" alt="Google">
													</a>
												</div>
                                                <div class="text-center me-2 flex-fill">
													<a href="javascript:void(0);"
														class="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center">
														<img class="img-fluid m-1" src="assets/img/icons/apple-logo.svg" alt="apple">
													</a>
												</div>
											</div>
										</div>
										<div class="text-center">
											<h6 class="fw-normal fs-14 text-dark mb-0">Don’t have an account yet?
												<a [routerLink]="routes.registerBasic" class="hover-a"> Register</a>
											</h6>
										</div>
									</div><!-- end card body -->
								</div><!-- end card -->
							</div>
						</form>
						<p class="text-dark text-center"> Copyright &copy; 2025 - Preclinic </p>
					</div><!-- end col -->
				</div>
				<!-- end row -->
			</div>
		</div>
		<!-- End Content -->
    </div>
    <!-- End Wrapper -->

// nextjs/template/src/components/auth/login/login.tsx
"use client"

import ImageWithBasePath from "@/core/imageWithBasePath";
import { all_routes } from "@/routes/all_routes";
import Link from "next/link";
import { useState } from "react";
type PasswordField = "password" | "confirmPassword";

const LoginComponent = () => {
  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prevState) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };
  return (
    <>
      {/* Start Content */}
      <div className="auth-bg position-relative overflow-hidden">
        <div className="container-fuild position-relative z-1">
          <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">
            {/* start row */}
            <div className="row justify-content-center align-items-center vh-100 overflow-auto flex-wrap py-3">
              <div className="col-lg-4 mx-auto">
                <form
                  className="d-flex justify-content-center align-items-center"
                >
                  <div className="d-flex flex-column justify-content-lg-center p-4 p-lg-0 pb-0 flex-fill">
                    <div className=" mx-auto mb-4 text-center">
                      <ImageWithBasePath
                        src="assets/img/logo.svg"
                        className="img-fluid"
                        alt="Logo"
                      />
                    </div>
                    <div className="card border-1 p-lg-3 shadow-md rounded-3 mb-4">
                      <div className="card-body">
                        <div className="text-center mb-3">
                          <h5 className="mb-1 fs-20 fw-bold">Sign In</h5>
                          <p className="mb-0">
                            Please enter below details to access the dashboard
                          </p>
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Email Address</label>
                          <div className="input-group">
                            <span className="input-group-text border-end-0 bg-white">
                              <i className="ti ti-mail fs-14 text-dark" />
                            </span>
                            <input
                              type="text"
                              
                              className="form-control border-start-0 ps-0"
                              placeholder="Enter Email Address"
                            />
                          </div>
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Password</label>
                          <div className="position-relative">
                          <div className="pass-group input-group position-relative border rounded">
                                  <span className="input-group-text bg-white border-0">
                                    <i className="ti ti-lock text-dark fs-14" />
                                  </span>
                                  <input
                                    type={
                                      passwordVisibility.password
                                        ? "text"
                                        : "password"
                                    }
                                    className="pass-input form-control border-start-0 ps-0"
                                    placeholder="****************"
                                  />
                                  <span
                                    className={`ti toggle-password text-dark fs-14 ${
                                      passwordVisibility.password
                                        ? "ti-eye"
                                        : "ti-eye-off"
                                    }`}
                                    onClick={() =>
                                      togglePasswordVisibility("password")
                                    }
                                  ></span>
                                </div>
                          </div>
                        </div>
                        <div className="d-flex align-items-center justify-content-between mb-3">
                          <div className="d-flex align-items-center">
                            <div className="form-check form-check-md mb-0">
                              <input
                                className="form-check-input"
                                id="remember_me"
                                type="checkbox"
                              />
                              <label
                                htmlFor="remember_me"
                                className="form-check-label mt-0 text-dark"
                              >
                                Remember Me
                              </label>
                            </div>
                          </div>
                          <div className="text-end">
                            <Link
                              href={all_routes.forgotpasswordbasic}
                              className="text-danger"
                            >
                              Forgot Password?
                            </Link>
                          </div>
                        </div>
                        <div className="mb-2">
                          <Link
                            href={all_routes.dashboard}
                            className="btn bg-primary text-white w-100"
                          >
                            Login
                          </Link>
                        </div>
                        <div className="login-or position-relative mb-3">
                          <span className="span-or">OR</span>
                        </div>
                        <div className="mb-3">
                          <div className="d-flex align-items-center justify-content-center flex-wrap">
                            <div className="text-center me-2 flex-fill">
                              <Link
                                href="#"
                                className="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center"
                              >
                                <ImageWithBasePath
                                  className="img-fluid m-1"
                                  src="assets/img/icons/facebook-logo.svg"
                                  alt="Facebook"
                                />
                              </Link>
                            </div>
                            <div className="text-center me-2 flex-fill">
                              <Link
                                href="#"
                                className="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center"
                              >
                                <ImageWithBasePath
                                  className="img-fluid m-1"
                                  src="assets/img/icons/google-logo.svg"
                                  alt="Google"
                                />
                              </Link>
                            </div>
                            <div className="text-center me-2 flex-fill">
                              <Link
                                href="#"
                                className="br-10 p-1 btn btn-outline-light border d-flex align-items-center justify-content-center"
                              >
                                <ImageWithBasePath
                                  className="img-fluid m-1"
                                  src="assets/img/icons/apple-logo.svg"
                                  alt="apple"
                                />
                              </Link>
                            </div>
                          </div>
                        </div>
                        <div className="text-center">
                          <h6 className="fw-normal fs-14 text-dark mb-0">
                            Don’t have an account yet? 
                            <Link href={all_routes.registerbasic} className="hover-a ms-1">
                              Register
                            </Link>
                          </h6>
                        </div>
                      </div>
                      {/* end card body */}
                    </div>
                    {/* end card */}
                  </div>
                </form>
                <p className="text-dark text-center">
                  
                  Copyright © 2025 - Preclinic
                </p>
              </div>
              {/* end col */}
            </div>
            {/* end row */}
          </div>
        </div>
      </div>
      {/* End Content */}
    </>
  );
};

export default LoginComponent;
