// nextjs/template/src/components/pages/settings/clinic-settings/custom-fields-settings/customFieldsSettings.tsx
"use client";

import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar"
import Modals from "./modals/modals"
import Link from "next/link";


const CustomFieldsSettingsComponent = () => {
  return (
   <>
  {/* ========================
			Start Page Content
		========================= */}
  <div className="page-wrapper">
    {/* Start Content */}
    <div className="content">
      {/* Page Header */}
      <div className="mb-3 border-bottom pb-3">
        <h4 className="fw-bold mb-0">Settings</h4>
      </div>
      {/* End Page Header */}
      <div className="card">
        <div className="card-body p-0">
          <div className="settings-wrapper d-flex">
            {/* Start Settings Sidebar */}
           <SettingsSidebar/>
            {/* End Settings Sidebar */}
            <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
              <div className="card-header border-bottom px-0 mx-3">
                <div className="d-flex align-items-center justify-content-between">
                  <h5 className="fw-bold">Custom Field</h5>
                  <Link
                    href="#"
                    className="btn btn-primary"
                    data-bs-toggle="modal"
                    data-bs-target="#add_reason"
                  >
                    <i className="ti ti-plus me-1" />
                    New Custom Field
                  </Link>
                </div>
              </div>
              <div className="card-body px-0 mx-3">
                {/* Table List */}
                <div className="table-responsive border">
                  <table className="table table-nowrap">
                    <thead className="tablehead-light">
                      <tr>
                        <th>Module</th>
                        <th>Label</th>
                        <th>Type</th>
                        <th>Default Value</th>
                        <th>Required</th>
                        <th>Status</th>
                        <th />
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Patient</td>
                        <td>Preferred Language</td>
                        <td>Select</td>
                        <td>English</td>
                        <td>
                          <div className="form-check form-switch ps-0">
                            <input
                              className="form-check-input m-0"
                              type="checkbox"
                              defaultChecked
                            />
                          </div>
                        </td>
                        <td>
                          <span className="badge bg-soft-success fs-13 fw-medium text-success d-inline-flex align-items-center">
                            <i className="ti ti-point-filled" />
                            Active
                          </span>
                        </td>
                        <td className="action-item">
                          <Link
                            href="#"
                            data-bs-toggle="dropdown"
                            className="btn p-1 btn-white border"
                          >
                            <i className="ti ti-dots-vertical" />
                          </Link>
                          <ul className="dropdown-menu p-2">
                            <li>
                              <Link
                                href="#"
                                className="dropdown-item d-flex align-items-center"
                                data-bs-toggle="modal"
                                data-bs-target="#edit_reason"
                              >
                                Edit
                              </Link>
                            </li>
                            <li>
                              <Link
                                href="#"
                                className="dropdown-item d-flex align-items-center"
                                data-bs-toggle="modal"
                                data-bs-target="#delete_reason"
                              >
                                Delete
                              </Link>
                            </li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>Staff</td>
                        <td>Job Type</td>
                        <td>Text</td>
                        <td>Full Time</td>
                        <td>
                          <div className="form-check form-switch ps-0">
                            <input
                              className="form-check-input m-0"
                              type="checkbox"
                              defaultChecked
                            />
                          </div>
                        </td>
                        <td>
                          <span className="badge bg-soft-success fs-13 fw-medium text-success d-inline-flex align-items-center">
                            <i className="ti ti-point-filled" />
                            Active
                          </span>
                        </td>
                        <td className="action-item">
                          <Link
                            href="#"
                            data-bs-toggle="dropdown"
                            className="btn p-1 btn-white border"
                          >
                            <i className="ti ti-dots-vertical" />
                          </Link>
                          <ul className="dropdown-menu p-2">
                            <li>
                              <Link
                                href="#"
                                className="dropdown-item d-flex align-items-center"
                                data-bs-toggle="modal"
                                data-bs-target="#edit_reason"
                              >
                                Edit
                              </Link>
                            </li>
                            <li>
                              <Link
                                href="#"
                                className="dropdown-item d-flex align-items-center"
                                data-bs-toggle="modal"
                                data-bs-target="#delete_reason"
                              >
                                Delete
                              </Link>
                            </li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                {/* /Table List */}
              </div>
            </div>
          </div>
        </div>
        {/* end card body */}
      </div>
      {/* end card */}
    </div>
    {/* End Content */}
    {/* Footer Start */}
    <div className="footer text-center bg-white p-2 border-top">
      <p className="text-dark mb-0">
        2025 ©
        <Link href="#" className="link-primary">
          Preclinic
        </Link>
        , All Rights Reserved
      </p>
    </div>
    {/* Footer End */}
  </div>
  {/* ========================
			End Page Content
		========================= */}
    <Modals/>
</>

  )
}

export default CustomFieldsSettingsComponent;

// angular/template/src/app/features/settings/app-settings/custom-fields-settings/custom-fields-settings.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-custom-fields-settings',
  templateUrl: './custom-fields-settings.component.html',
  styleUrls: ['./custom-fields-settings.component.scss'],
  imports:[CommonModule,MatSelectModule]
})
export class CustomFieldsSettingsComponent {

}


                                <div class="card-header border-bottom px-0 mx-3">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <h5 class="fw-bold">Custom Field</h5>
                                        <a href="javascript:void(0);" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_reason"><i class="ti ti-plus me-1"></i>New Custom Field</a>
                                    </div>
                                </div>
                                <div class="card-body px-0 mx-3">
                                    <!-- Table List -->
                                    <div class="table-responsive border">
                                        <table class="table table-nowrap">
                                            <thead class="tablehead-light">
                                                <tr>
                                                    <th>Module</th>
                                                    <th>Label</th>
                                                    <th>Type</th>
                                                    <th>Default Value</th>
                                                    <th>Required</th>
                                                    <th>Status</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>Patient</td>
                                                    <td>Preferred Language</td>
                                                    <td>Select</td>
                                                    <td>English</td>
                                                    <td>
                                                        <div class="form-check form-switch ps-0">
                                                            <input class="form-check-input m-0" type="checkbox" checked="">
                                                        </div>
                                                    </td>
                                                    <td><span class="badge bg-soft-success fs-13 fw-medium text-success d-inline-flex align-items-center"><i class="ti ti-point-filled"></i>Active</span></td>
                                                    <td class="action-item">
                                                        <a href="javascript:void(0);" data-bs-toggle="dropdown" class="btn p-1 btn-white border">
                                                            <i class="ti ti-dots-vertical"></i>
                                                        </a>
                                                        <ul class="dropdown-menu p-2">
                                                            <li>
                                                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#edit_reason">Edit</a>
                                                            </li>
                                                            <li>
                                                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#delete_reason">Delete</a>
                                                            </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Staff</td>
                                                    <td>Job Type</td>
                                                    <td>Text</td>
                                                    <td>Full Time</td>
                                                    <td>
                                                        <div class="form-check form-switch ps-0">
                                                            <input class="form-check-input m-0" type="checkbox" checked="">
                                                        </div>
                                                    </td>
                                                    <td><span class="badge bg-soft-success fs-13 fw-medium text-success d-inline-flex align-items-center"><i class="ti ti-point-filled"></i>Active</span></td>
                                                    <td class="action-item">
                                                        <a href="javascript:void(0);" data-bs-toggle="dropdown" class="btn p-1 btn-white border">
                                                            <i class="ti ti-dots-vertical"></i>
                                                        </a>
                                                        <ul class="dropdown-menu p-2">
                                                            <li>
                                                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#edit_reason">Edit</a>
                                                            </li>
                                                            <li>
                                                                <a href="javascript:void(0);" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#delete_reason">Delete</a>
                                                            </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /Table List -->
                                </div>


                                        <!-- Start Add Categories -->
        <div id="add_reason" class="modal fade">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="text-dark modal-title fw-bold">Add Custom Field</h5>
                        <button type="button" class="btn-close btn-close-modal custom-btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-x"></i></button>
                    </div>
                    <form>
                        <div class="modal-body">
                            <div class="mb-3">
                                <label class="form-label">Module<span class="text-danger ms-1">*</span></label>
                                <mat-select class="custom-mat-select select" placeholder="Select">
                                    <mat-option value="1">Select</mat-option>
                                    <mat-option value="1">Patient</mat-option>
                                    <mat-option value="1">Staff</mat-option>
                                </mat-select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Input Type<span class="text-danger ms-1">*</span></label>
                                <mat-select class="custom-mat-select select" placeholder="Select">
                                    <mat-option value="1">Select</mat-option>
                                    <mat-option value="1">Text</mat-option>
                                    <mat-option value="1">Number</mat-option>
                                    <mat-option value="1">Password</mat-option>
                                    <mat-option value="1">File</mat-option>
                                </mat-select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Label<span class="text-danger ms-1">*</span></label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Default Value<span class="text-danger ms-1">*</span></label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="mb-0">
                                <div class="d-flex align-items-center justify-content-between">
                                    <label class="form-label">Required</label>
                                    <div class="form-check form-switch ps-0">
                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer d-flex align-items-center gap-1">
                            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Add Custom Field</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- End Add Categories -->

        <!-- Start Edit Categories -->
        <div id="edit_reason" class="modal fade">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="text-dark modal-title fw-bold">Edit Custom Field</h5>
                        <button type="button" class="btn-close btn-close-modal custom-btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-x"></i></button>
                    </div>
                    <form>
                        <div class="modal-body">
                            <div class="mb-3">
                                <label class="form-label">Module<span class="text-danger ms-1">*</span></label>
                                <mat-select class="custom-mat-select select" placeholder="Patient">
                                    <mat-option value="1">Select</mat-option>
                                    <mat-option value="1">Patient</mat-option>
                                    <mat-option value="1">Staff</mat-option>
                                </mat-select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Input Type<span class="text-danger ms-1">*</span></label>
                                <mat-select class="custom-mat-select select" placeholder="Select">
                                    <mat-option value="1">Select</mat-option>
                                    <mat-option value="1">Text</mat-option>
                                    <mat-option value="1">Number</mat-option>
                                    <mat-option value="1">Password</mat-option>
                                    <mat-option value="1">File</mat-option>
                                </mat-select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Label<span class="text-danger ms-1">*</span></label>
                                <input type="text" class="form-control" value="Preferred Language">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Default Value<span class="text-danger ms-1">*</span></label>
                                <input type="text" class="form-control" value="English">
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center justify-content-between">
                                    <label class="form-label">Required</label>
                                    <div class="form-check form-switch ps-0">
                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                    </div>
                                </div>
                            </div>
                            <div class="mb-0">
                                <div class="d-flex align-items-center justify-content-between">
                                    <label class="form-label">Status</label>
                                    <div class="form-check form-switch ps-0">
                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer d-flex align-items-center gap-1">
                            <button type="button" class="btn btn-white border" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- End Edit Categories -->
