// nextjs/template/src/components/pages/settings/system-settings/gdpr-cookies-settings/gdprCookiesSettings.tsx
"use client";

import Link from "next/link"
import { Cookies_Position } from "@/core/common/selectOption"
import SettingsSidebar from "@/core/common/settings-sidebar/settingsSidebar"
import CommonSelect from "@/core/common/common-select/commonSelect"


const GdprCookiesSettingsComponent = () => {
  return (
   <>
  {/* ========================
			Start Page Content
		========================= */}
  <div className="page-wrapper">
    {/* Start Content */}
    <div className="content" id="profilePage">
      {/* Page Header */}
      <div className="mb-3 border-bottom pb-3">
        <h4 className="fw-bold mb-0">Settings</h4>
      </div>
      {/* End Page Header */}
      <div className="card">
        <div className="card-body p-0">
          <div className="settings-wrapper d-flex">
            {/* Start Settings Sidebar */}
           <SettingsSidebar/>
            {/* End Settings Sidebar */}
            <div className="card flex-fill mb-0 border-0 bg-light-500 shadow-none">
              <div className="card-header border-bottom px-0 mx-3">
                <h5 className="fw-bold">GDPR Cookies</h5>
              </div>
              <div className="card-body px-0 mx-3">
                <form>
                  {/* start row */}
                  <div className="row border-bottom mb-3">
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Cookies Position
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-5">
                       <CommonSelect
                        options={Cookies_Position}
                        className="select"
                        defaultValue={Cookies_Position[0]}
                      />
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Agree Button Text
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-5">
                          <input type="text" className="form-control" />
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Decline Button Text
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-5">
                          <input type="text" className="form-control" />
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Show Decline Button
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-8">
                          <div className="form-check form-switch ps-0">
                            <input
                              className="form-check-input m-0"
                              type="checkbox"
                              defaultChecked
                            />
                          </div>
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Links for Cookies Page
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-8">
                          <input type="text" className="form-control" />
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                    <div className="col-lg-12">
                      {/* start row */}
                      <div className="row align-items-center mb-3">
                        <div className="col-lg-4">
                          <label className="form-label mb-0">
                            Cookies Content Text
                          </label>
                        </div>
                        {/* end col */}
                        <div className="col-lg-8">
                          <div className="editor three-line" />
                        </div>
                        {/* end col */}
                      </div>
                      {/* end row */}
                    </div>
                    {/* end col */}
                  </div>
                  {/* end row */}
                  <div className="d-flex align-items-center justify-content-end">
                    <Link
                      href="#"
                      className="btn btn-light me-3"
                    >
                      Cancel
                    </Link>
                    <Link href="#" className="btn btn-primary">
                      Save Changes
                    </Link>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        {/* end card body */}
      </div>
      {/* end card */}
    </div>
    {/* End Content */}
    {/* Footer Start */}
    <div className="footer text-center bg-white p-2 border-top">
      <p className="text-dark mb-0">
        2025 ©
        <Link href="#" className="link-primary">
          Preclinic
        </Link>
        , All Rights Reserved
      </p>
    </div>
    {/* Footer End */}
  </div>
  {/* ========================
			End Page Content
		========================= */}
</>

  )
}

export default GdprCookiesSettingsComponent

// angular/template/src/app/features/settings/system-settings/gdpr-cookies-settings/gdpr-cookies-settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-gdpr-cookies-settings',
  templateUrl: './gdpr-cookies-settings.component.html',
  styleUrls: ['./gdpr-cookies-settings.component.scss'],
  imports: [CommonModule,MatSelectModule]
})
export class GdprCookiesSettingsComponent {

}


                                <div class="card-header border-bottom px-0 mx-3">
                                    <h5 class="fw-bold">GDPR Cookies</h5>
                                </div>
                                <div class="card-body px-0 mx-3">
                                    <form>

                                        <!-- start row -->
                                        <div class="row border-bottom mb-3">
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                    <div class="col-lg-4">
                                                        <label class="form-label mb-0">Cookies Position</label>
                                                    </div><!-- end col -->
                                                    <div class="col-lg-5">
                                                        <mat-select class="custom-mat-select select" placeholder="Select">
                                                            <mat-option value="1">Select</mat-option>
                                                            <mat-option value="1">Select</mat-option>
                                                        </mat-select>
                                                    </div><!-- end col -->
                                                </div>
                                                <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-4">
                                                    <label class="form-label mb-0">Agree Button Text</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-5">
                                                    <input type="text" class="form-control">
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-4">
                                                    <label class="form-label mb-0">Decline Button Text</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-5">
                                                    <input type="text" class="form-control">
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-4">
                                                    <label class="form-label mb-0">Show Decline Button</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-8">
                                                    <div class="form-check form-switch ps-0">
                                                        <input class="form-check-input m-0" type="checkbox" checked="">
                                                    </div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-4">
                                                    <label class="form-label mb-0">Links for Cookies Page</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-8">
                                                    <input type="text" class="form-control">
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                            <div class="col-lg-12">

                                                <!-- start row -->
                                                <div class="row align-items-center mb-3">
                                                <div class="col-lg-4">
                                                    <label class="form-label mb-0">Cookies Content Text</label>
                                                </div><!-- end col -->
                                                <div class="col-lg-8">
                                                    <div class="editor three-line"></div>
                                                </div><!-- end col -->
                                            </div>
                                            <!-- end row -->

                                            </div><!-- end col -->
                                        </div>
                                        <!-- end row -->

                                        <div class="d-flex align-items-center justify-content-end">
                                            <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                                            <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
                                        </div>
                                    </form>
                                </div>
