// nextjs/template/src/components/auth/error-modules/error500.tsx
"use client";

import ImageWithBasePath from "@/core/imageWithBasePath"
import { all_routes } from "@/routes/all_routes"
import Link from "next/link";

const Error500Component = () => {
  return (
   <>
  {/* Start Content */}
  <div className="auth-bg position-relative overflow-hidden">
    <div className="container-fuild">
      <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100 z-1">
        <div className="row justify-content-center align-items-center vh-100 overflow-auto flex-wrap ">
          <div className="col-lg-6">
            <div className="d-flex flex-column align-items-center justify-content-center">
              <div className=" mx-auto mb-5 text-center">
                <ImageWithBasePath src="assets/img/logo.svg" className="img-fluid" alt="Logo" />
              </div>
              <div className="error-images mb-3">
                <ImageWithBasePath
                  src="assets/img/error-500.svg"
                  alt="image"
                  className="img-fluid"
                />
              </div>
              <div className="text-center">
                <h4 className="mb-2 fw-bold">Oops, something went wrong</h4>
                <p className="fs-14 text-center">
                  Server Error 500. We apologise and are fixing the problem.
                  Please try again at a later stage
                </p>
                <div className="d-flex justify-content-center pb-3">
                  <Link
                    href={all_routes.dashboard}
                    className="btn btn-primary d-flex align-items-center "
                  >
                    <i className="ti ti-chevron-left me-2" />
                    Back to Dashboard
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {/* End Content */}
  {/* Start Bg Content */}
  <ImageWithBasePath
    src="assets/img/auth/auth-bg-top.png"
    alt=""
    className="img-fluid element-01"
  />
  <ImageWithBasePath
    src="assets/img/auth/auth-bg-bot.png"
    alt=""
    className="img-fluid element-02"
  />
  </div>
  {/* End Bg Content */}
</>


  )
}

export default Error500Component

// vue/template/src/views/pages/authentication/error/error-500.vue
<template>
  <div class="auth-bg position-relative overflow-hidden">
    <!-- Start Content -->
    <div class="container-fuild">
      <div class="w-100 overflow-hidden position-relative flex-wrap d-block vh-100 z-1">
        <div
          class="row justify-content-center align-items-center vh-100 overflow-auto flex-wrap"
        >
          <div class="col-lg-6">
            <div class="d-flex flex-column align-items-center justify-content-center">
              <div class="mx-auto mb-5 text-center">
                <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
              </div>
              <div class="error-images mb-3">
                <img src="@/assets/img/error-500.svg" alt="image" class="img-fluid" />
              </div>
              <div class="text-center">
                <h4 class="mb-2 fw-bold">Oops, something went wrong</h4>
                <p class="fs-14 text-center">
                  Server Error 500. We apologise and are fixing the problem. Please try
                  again at a later stage
                </p>
                <div class="d-flex justify-content-center pb-3">
                  <router-link
                    to="/dashboard/"
                    class="btn btn-primary d-flex align-items-center"
                    ><i class="ti ti-chevron-left me-2"></i>Back to Dashboard</router-link
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Content -->

    <!-- Start Bg Content -->

    <img src="@/assets/img/auth/auth-bg-top.png" alt="" class="img-fluid element-01" />
    <img src="@/assets/img/auth/auth-bg-bot.png" alt="" class="img-fluid element-02" />
    <!-- End Bg Content -->
  </div>
</template>
