// nextjs/template/src/components/pages/application-modules/application/calls/outGoingCall.tsx
"use client";


import ImageWithBasePath from "@/core/imageWithBasePath";
import { all_routes } from "../../../../../routes/all_routes";
import Link from "next/link";

const OutGoingCallComponent = () => {
  return (
    <>
      {/* ========================
			Start Page Content
		========================= */}
      <div className="page-wrapper">
        {/* Start Content */}
        <div className="content content-two">
          {/* Page Header */}
          <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
            <div className="flex-grow-1">
              <h4 className="fs-18 fw-semibold mb-0">OutgoingCall</h4>
            </div>
            <div className="text-end">
              <ol className="breadcrumb m-0 py-0">
                <li className="breadcrumb-item">
                  <Link href={all_routes.dashboard}>Home</Link>
                </li>
                <li className="breadcrumb-item">
                  <Link href={all_routes.dashboard}>Applications</Link>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  Outgoing Call
                </li>
              </ol>
            </div>
          </div>
          {/* End Page Header */}

          {/* start row  */}
          <div className="row">
            <div className="col-xxl-12">
              <div className="card car-max-height mb-0 shadow-none">
                <div className="card-body text-center d-flex flex-column justify-content-center">
                  <div className="caller-profile mb-3">
                    <ImageWithBasePath
                      src="assets/img/users/user-01.jpg"
                      className="img-fluid rounded-circle"
                      alt="img"
                    />
                  </div>
                  <h5>Anthony Lewis</h5>
                  <p>Calling...</p>
                  <div className="d-flex align-items-center justify-content-center">
                    <Link
                      href="#"
                      className="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"
                    >
                      <i className="ti ti-video fs-20" />
                    </Link>
                    <Link
                      href="#"
                      className="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"
                    >
                      <i className="ti ti-microphone fs-20" />
                    </Link>
                    <Link
                      href="#"
                      className="btn btn-danger btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"
                    >
                      <i className="ti ti-phone-off fs-20" />
                    </Link>
                    <Link
                      href="#"
                      className="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"
                    >
                      <i className="ti ti-user-plus fs-20" />
                    </Link>
                    <Link
                      href="#"
                      className="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center"
                    >
                      <i className="ti ti-volume fs-20" />
                    </Link>
                  </div>
                </div>
                {/* end card body */}
              </div>
              {/* end card */}
            </div>
            {/* end col */}
          </div>
          {/* end row  */}
        </div>
        {/* End Content */}
      </div>
      {/* ========================
			End Page Content
		========================= */}
    </>
  );
};

export default OutGoingCallComponent;

// angular/template/src/app/features/application/calls/outgoing-call/outgoing-call.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-outgoing-call',
  templateUrl: './outgoing-call.component.html',
  styleUrls: ['./outgoing-call.component.scss'],
  imports: [CommonModule,RouterLink]
})
export class OutgoingCallComponent {
routes=routes
}

<div class="content">              

                <!-- Page Header -->
                <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-2 pb-3">
                    <div class="flex-grow-1">
                        <h4 class="fs-18 fw-semibold mb-0">OutgoingCall</h4>
                    </div>
                    <div class="text-end">
                        <ol class="breadcrumb m-0 py-0">
                            <li class="breadcrumb-item"><a [routerLink]="routes.index">Home</a></li>                              
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Applications</a></li>                              
                            <li class="breadcrumb-item active" aria-current="page">Outgoing Call</li>
                        </ol>
                    </div>
				</div>
				<!-- End Page Header -->

                <!-- start row  -->
                <div class="row">

                    <div class="col-xxl-12">
                        <div class="card card-max-height mb-0 shadow-none">
                            <div class="card-body text-center d-flex flex-column justify-content-center">
                                <div class="animation-ripple avatar avatar-xxxl d-flex mx-auto mb-3 rounded-circle mb-3">
                                    <img src="assets/img/users/user-01.jpg" class="img-fluid rounded-circle" alt="img">
                                </div>
                                <h5>Anthony Lewis</h5>
                                <p>Calling...</p>
                                <div class="d-flex align-items-center justify-content-center">
                                    <a href="javascript:void(0);" class="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"><i class="ti ti-video fs-20"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"><i class="ti ti-microphone fs-20"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-danger btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"><i class="ti ti-phone-off fs-20"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center me-3"><i class="ti ti-user-plus fs-20"></i></a>
                                    <a href="javascript:void(0);" class="btn btn-light btn-icon rounded-circle p-0 d-flex align-items-center justify-content-center"><i class="ti ti-volume fs-20"></i></a>
                                </div>
                            </div><!-- end card body -->
                        </div><!-- end card -->
                    </div><!-- end col -->
                    
                </div>
                <!-- end row  -->

            </div>
